### ISSUE TITLE
Define NOMINMAX before windows.h

### ISSUE THREAD

**Issue by AlexMax** [Dav1dde/glad#100]
I ran into an issue where GLAD included `windows.h`.  I've read #42, and I understand why you thought it was a good idea to keep it, but one thing that would help a whole bunch is defining `NOMINMAX` before including `windows.h`.  This specifically is a major pain-point when including `windows.h`, as the min and max macros conflict with `std::min` and `std::max`, which seems like behavior you would want to avoid in most cases.  Those who needed Microsoft's min/max could simply include `windows.h` before GLAD.

For what it's worth, `SDL_opengl.h` appears to do exactly what I describe.

**Comment by Dav1dde** [comment]
I will look into it tonight, seems like I missed that change as it was proposed in #42. Thanks for bringing that up again.
