### ISSUE TITLE
Double definition of GL_RGB in glad.h

### ISSUE THREAD

**Issue by EndysGit** [Dav1dde/glad#108]
I downloaded the archive using http://glad.dav1d.de/ with following configurations:
Language: C/C++
Specification: OpenGL
Profile: Core
API: gl(version 3.3)
When I tried to add a texture using  glTexImage2D() function it hadn't work than it's turned out that in glad.h exists two definition of GL_RGB with different values.
The function works fine with GL_RGB 0x1907 (line 908) and not works with GL_RG8 0x822B (line 1419).
My system: 
OS X Sierra 10.12.6
IDE: CLion

**Comment by Shimmen** [comment]
`GL_RGB` and `GL_RG8` are two different things and are not interchangeable. Note that there is an **8** instead of a **B** in the second instance (0x822B).

**Comment by Dav1dde** [comment]
Thanks @Shimmen for looking into this so quickly!

@EndysGit does this solve your problem? If not, feel free to re-open the issue.

**Comment by EndysGit** [comment]
@Shimmen, I noticed this but thought that it's some kind of mistake. I'm a new one in OpenGL and others related things so I don't know difference between them. 
@Dav1dde, Yeah, I've solved this problem. 
Thanks both of you!
