### ISSUE TITLE
glad2 Documentation

### ISSUE THREAD

**Issue by Dav1dde** [Dav1dde/glad#109]
### C
- [x] Examples
- [ ] Quick Start
- [x] Options

### Rust
- [ ] Examples
- [ ] Quick Start
- [ ] Options

Related issues:

* #161

**Comment by BlGene** [comment]
One question to glad2, am I doing this right? ```gladLoadGLSimple(GLADsimpleloadproc())```

**Comment by Dav1dde** [comment]
Still deciding on the API, currently it's:

```
typedef void* (* GLADloadproc)(const char *name, void* userptr);
typedef void* (* GLADsimpleloadproc)(const char *name);

GLAPI int gladLoadGL(GLADloadproc load, void* userptr);
GLAPI int gladLoadGLSimple(GLADsimpleloadproc load);
GLAPI int gladLoadGLInternalLoader();
```

Maybe naming the functions according to what arguments they take is the better solution. My only set goal is to get rid of the `gladLoadGL()` which uses the internal loader, I want the default usage to be without loader (basically every windowing framework has a `GetProcAddress` implementation).

**Comment by BlGene** [comment]
...So if I call gladLoadGLInternalLoader I don’t have to call gladLoadGLSimple?

**Comment by Dav1dde** [comment]
Correct, you only need to call one of those three (calling these functions in total more than once may result in weird results).

**Comment by BlGene** [comment]
ProTip: When calling the glad executable add `--loader`

The loader function names have also changed:
`gladLoadEGLInternalLoader` -> `gladLoaderLoadEGL`
`gladLoadGLInternalLoader` -> `gladLoaderLoadGL`

**Comment by BlGene** [comment]
@Dav1dde 
I just spent a while figuring out that `gladLoaderLoadGL()` was failing on certain machines because it didn't find the `libGL.so.1` file. It would be nice to have more informative error information from this function.

**Comment by Dav1dde** [comment]
Thanks, I am still working on the documentation, the wiki should be accurate: https://github.com/Dav1dde/glad/wiki/C 

Interesting that libGL.so isn't available, what else is available?

I am not sure how I would do a better error handling. Return code 0 (false) is failure, return code > 0 is the loaded version, negative return codes would break the `if (!load())` "idiom".

**Comment by BlGene** [comment]
@Dav1dde:
It looks like the problem wasn't with `dlopen`.

So when a colleague in another department tries to run my code he gets errors when calling try to run the following code error when calling `gladLoaderLoadGL`. This occurs on all his Ubuntu 16 machines, not his Ubuntu 14 machines. For me it works fine on several Ubunut 16 machines.

https://gist.github.com/BlGene/b78e237efb65086de3ef9e8aafdbef02#file-egl_gl2-cpp-L167

Is there anything we could do to give more meaningful debug information?

**Comment by Dav1dde** [comment]
What error does he get, return value of 0? Glad would usually only fail if it cannot load an essential function (a function required to get very basic information, like `glGetString`), on a failed allocation (`malloc`, `calloc` etc.) or `glGetString` returning `NULL` where it shouldn't.  For now the easiest to figure that out is to add a `printf()` (or breakpoint) where glad would return 0 (just ctrl-f for `return 0`).

I'll try to reproduce this in the next few days and add a pre-processor flag that provides additional information why the loader is failing.

**Comment by BlGene** [comment]
It looks like the error occurs in the function `gladLoadGLUserPtr` on the line `glGetString(GL_VERSION) == NULL`. 

We tried get an error message by calling `glGetError` but this did not produce any results.
Doing `cout << load("glGetString", userptr) << endl;` returns `1`.

**Comment by Dav1dde** [comment]
This usually happens if there is no active/current context.

**Comment by Dav1dde** [comment]
Mh that actually makes sense that it doesn't work, glad uses a glx function to retrieve gl pointers and you're using egl not glx. Try passing `eglGetProcAddress` to `gladLoadGL`.

**Comment by BlGene** [comment]
@Dav1dde: Looks like this solved it. Thanks!

My test file is located here in case you want to include it. (no build script) https://github.com/BlGene/glad/tree/glad2-egl-example

By the way, I'm still for adding the option to load X11 functions dynamically. It would only change ~50 lines of code, see `glx_dyn.c` in https://gist.github.com/BlGene/add866798e551424a75315099196b53d

**Comment by Dav1dde** [comment]
I just saw you're still using `version % 10` and `version / 10`, this does not work with the latest glad version anymore, you should use the macros `GLAD_VERSION_MAJOR(version)` and `GLAD_VERSION_MINOR(version)` instead.

I don't think I am going to dynamically load X11 functions, it's just something I don't wanna take care of (what if X11 is not available, what if the X11 so is named differentely on a platform etc.), I'll probably add a macro though which disables the usage of those 3 X11 functions (since they are just convenience) and you simply have to pass a valid screen and display instead of `NULL`.

**Comment by Dav1dde** [comment]
@BlGene try compiling with `-DGLAD_GLX_NO_X11`, glad will not call X11 functions anymore, but you need to pass a valid display/screen to `glad*LoadGLX`.

**Comment by fiblit** [comment]
Shouldn't this be in the "glad **space** 2" milestone not the "glad2" milestone?

**Comment by surafel911** [comment]
Should I bother to call glXQueryExtension when using glad2 or is it unnecessary? I see that glXQueryVersion is used.

**Comment by Dav1dde** [comment]
You don't have to, glad loads all extensions that were specified automatically. In order to check if an extension is supported you can use the global variable named after the extension and prefixed with `GLAD_`, e.g. to check if `GLX_ARB_create_context_profile` is supported:

```c
If (GLAD_GLX_ARB_create_context_profile) {
    // supported
} 
```

**Comment by surafel911** [comment]
I can't find any of those global variables you're talking about. Is this something I have to query using a function?

**Comment by Dav1dde** [comment]
They do exist:

```c
#define GLX_VERSION_1_0 1
GLAD_API_CALL int GLAD_GLX_VERSION_1_0;
#define GLX_VERSION_1_1 1
GLAD_API_CALL int GLAD_GLX_VERSION_1_1;
#define GLX_VERSION_1_2 1
GLAD_API_CALL int GLAD_GLX_VERSION_1_2;
#define GLX_VERSION_1_3 1
GLAD_API_CALL int GLAD_GLX_VERSION_1_3;
#define GLX_VERSION_1_4 1
GLAD_API_CALL int GLAD_GLX_VERSION_1_4;
#define GLX_3DFX_multisample 1
GLAD_API_CALL int GLAD_GLX_3DFX_multisample;
#define GLX_ARB_create_context_profile 1
GLAD_API_CALL int GLAD_GLX_ARB_create_context_profile;
```

**Comment by surafel911** [comment]
I don't have anything past GLX_VERSION in my glx.h. I've added my glx.h file if you want proof. 

[glx.txt](https://github.com/Dav1dde/glad/files/2408894/glx.txt)

**Comment by Dav1dde** [comment]
You didn't add any extensions (from the header you attached):

```
/**
 * <snip>
 * Extensions: 0
 *
 * <snip>
 *
 * Commandline:
 *    --api='glx=1.4' --extensions='' c --loader --alias
 *
 * <snip>
 *
 */

If you want support for an extension you have to add it, on the website you can just click the extensions - on commandline you have to add them to the extension argument.

**Comment by Zingam** [comment]
Khronos specifies the headers as <GLES3/gl32.h>. What confused me is the web service here: https://gen.glad.sh/ as all of the GL version are bunched together but the GLES are separated.
I think it would be beneficial gles versions and platforms are mentioned in the documentation.

**Comment by Dav1dde** [comment]
I agree this should be added to the docs.

**Comment by Zingam** [comment]
The sample doesn't have the cast but I can't compile without it: gladLoadGL((GLADloadfunc)SDL_GL_GetProcAddress);

**Comment by Dav1dde** [comment]
Can you link me the example? I don't remember having more than just [this](https://github.com/Dav1dde/glad/blob/glad2/example/c/gl_sdl2.c) SDL exmaple.

**Comment by Zingam** [comment]
Sorry for the confusion. I copied this line from my source. What I mean is:
https://github.com/Dav1dde/glad/tree/glad2
Shouldn't that example contain the cast too for the sake of clarity:
```
int version = gladLoadGL(glfwGetProcAddress);
    if (version == 0) {
        printf("Failed to initialize OpenGL context\n");
        return -1;
    }
```
https://github.com/Dav1dde/glad/blob/glad2/example/c%2B%2B/hellowindow2.cpp

**Comment by Dav1dde** [comment]
The cast here is not required because the types match, I actually prefer it without the cast (when possible), it makes sure you're not accidentally casting the wrong function and imo it looks a lot cleaner.

**Comment by Zingam** [comment]
I agree but for tutorial's the cast needs to be documented as this will save some learner's headbanging.

**Comment by surafel911** [comment]
I noticed that when using GLAD glXCreateContextAttribsARB hasn't been loaded (confirmed by GLAD_GLX_create_context and GLAD_GLX_create_context_profile being 0), but when I use the shared library version, the function is available and works fine in my project. Any ideas?

**Comment by surafel911** [comment]
I have called `gladLoaderLoadGLX`, but it seems I don't have `glxinfo` installed. What package does it come from?

**Comment by Dav1dde** [comment]
@surafel911 fixed in https://github.com/Dav1dde/glad/commit/e5090adad5319b4ff130963c3c03be74de5a7cab - I broke extension detection.

Thanks!

**Comment by surafel911** [comment]
Will this patch be available in the extension loader or do I have to wait for the next release?

**Comment by Dav1dde** [comment]
You can already re-generate from http://gen.glad.sh - For the glad2 branch I'll continuously update the web generator.

**Comment by surafel911** [comment]
I got some compiler errors. Don't think it has anything to do with me.

https://gist.github.com/surafel911/46a8add9d1e79e7dbde7a790a4953b21

**Comment by Dav1dde** [comment]
What options did you use to generate (should be listed on top of the header file)? Or please upload a zip containing the C and header files.

**Comment by surafel911** [comment]
Don't have a lot of spare time. Here is my up-to-date repo. Feel free to look at it.

https://github.com/surafel911/qubit-engine/blob/master/

**Comment by surafel911** [comment]
Don't have a lot of spare time. Here is my up-to-date repo. Feel free to look at it.

https://github.com/surafel911/qubit-engine/blob/master/

**Comment by Dav1dde** [comment]
Seems like you accidentally typed into the source file:

![image](https://user-images.githubusercontent.com/255721/46579178-7a97ff00-ca0c-11e8-94b7-72fcee9ab471.png)

At least I cannot reproduce this with the options you used, also this is basically impossible to be generated by glad since all those variables are generated at the same place within one for loop. 

Removing the marked line and the `if` at the beginning of the next makes the file compile.
