### ISSUE TITLE
Auto-complete friendly function prototypes

### ISSUE THREAD

**Issue by siavashserver** [Dav1dde/glad#11]
Is it possible to mimic same behavior like `glcorearb.h` with `GL_GLEXT_PROTOTYPES` defined? Current implementation hides function prototypes and makes auto-complete feature of IDEs almost useless.

![out](https://cloud.githubusercontent.com/assets/1075690/4023310/dea8f5b4-2b85-11e4-8681-4b0a424c4650.png)

Thanks!

**Comment by Dav1dde** [comment]
You can try to create a minimal example (without glad):

Something like this:
```c
typedef void (PFNGLVIEWPORTPROC)(int x, int y, int width, int height);
GLAPI PFNGLVIEWPORTPROC glad_glViewport;
#define glViewport glad_glViewport

int main(void) {
    glViewport(0, 0, 0, 0);
    return 0;
}
```

In this example the completion should also not work (if it does it gets more complicated), then report it as error  or ask in the forums. A description could be something along the lines of 

> function pointers do not show argument names when aliased using a #define macro

PS: Maybe this also happens for the function pointer it self `glad_glViewport` and is not related to the macro.

**Comment by hamoid** [comment]
@Dav1dde You're right: it also happens without the #define macro

![qtcreator-with-glad](https://user-images.githubusercontent.com/108264/39462628-fef0eaae-4d12-11e8-8ca3-e456acc1ee1a.png)
