### ISSUE TITLE
glad does not build correctly when BUILD_SHARED_LIBS is ON

### ISSUE THREAD

**Issue by l0calh05t** [Dav1dde/glad#113]
When the CMake variable `BUILD_SHARED_LIBS` is `ON`/`TRUE`/`1`, `add_library` calls that do not specify `STATIC` or `SHARED`, are built as shared libraries. The produced dll does not export any symbols.

**Comment by Dav1dde** [comment]
Does this still happen with : https://github.com/Dav1dde/glad/pull/111/commits/43fc13b746d09443d87b9cd9f23d943f395a3b9b

**Comment by l0calh05t** [comment]
I manually added that to my CMake and while an export lib is now generated, using the library (also via CMake) leads to a bunch of warnings like

````
src\glad.c(126): warning C4273: 'gladLoadGL': inconsistent dll linkage
include\glad/glad.h(88): note: see previous definition of 'gladLoadGL'
````

and finally to linker errors like `error LNK2001: unresolved external symbol glad_glClear`.

However, if I make `GLAD_GLAPI_EXPORT` public instead of private, linking works (while the warnings persist).

**Comment by l0calh05t** [comment]
with the following it works without warnings:

```
target_compile_definitions(glad PUBLIC GLAD_GLAPI_EXPORT PRIVATE GLAD_GLAPI_EXPORT_BUILD)
```
