### ISSUE TITLE
Lacking GL_BLEND_COLOR

### ISSUE THREAD

**Issue by ferreiradaselva** [Dav1dde/glad#115]
The macro GL_BLEND_COLOR is said [here](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glBlendColor.xhtml) to be available on OpenGL 2.0 to OpenGL 4.5.

On my system `gl.h` it's available, but it's not generated on `glad.h`.

The file was generated with this command:
`--profile="core" --api="gl=3.3" --generator="c" --spec="gl" --extensions=""`

**Comment by Dav1dde** [comment]
This appears to be a XML Bug. In the [current gl.xml](https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/xml/gl.xml) GL_BLEND_COLOR is not `<require>`'d by GL 2.0. It is for `gles` though.

Please try opening an issue at https://github.com/KhronosGroup/OpenGL-Registry
