### ISSUE TITLE
glGenerateMipmap is in OpenGL 2.0, but glad only initializes in OpenGL 3.x?

### ISSUE THREAD

**Issue by erwincoumans** [Dav1dde/glad#116]
I'm new to glad, tried it out in my app that can run in GL2 or GL3.x mode. There was a crash in GL 2.x mode (using glfw to initialize the 2.x context), due to:
glad_glGenerateMipmap = (PFNGLGENERATEMIPMAPPROC)load("glGenerateMipmap");
to be in the 3.x section, not 2.x (hence a NULL pointer crash).
I manually moved the line into 2.x section of glad.c and it works.

Is there a way to generate a glad with glGenerateMipmap in GL2?

**Comment by Dav1dde** [comment]
[`glGenerateMipmap`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGenerateMipmap.xhtml) was added to core in version 3.0.

You might want to add the `GL_ARB_framebuffer_object` extension if you want to use `glGenerateMipmap` with OpenGL < 3.0.

**Comment by erwincoumans** [comment]
Thanks, then it was a user mistake.
