### ISSUE TITLE
Using GLAD with OpenVR

### ISSUE THREAD

**Issue by bucetil** [Dav1dde/glad#117]
Hi! I've heard about GLAD recently, and I'm interested in using it with OpenVR on virtual reality purposes. Is there any way to make Glad work with OpenVR? If so, is there any example on the internet?
Thanks!

**Comment by Dav1dde** [comment]
hey.

I am not aware of any OpenVR examples with Glad. Looking at the OpenVR git repository it should be really simple to use glad to initialize a context for OpenVR.

Going by this example:
https://github.com/ValveSoftware/openvr/blob/ebdea152f8aac77e9a6db29682b81d762159df7e/samples/hellovr_opengl/hellovr_opengl_main.cpp#L407

Just replace the glew lines (407-413) with:

```c
    if (!gladLoadGLLoader((GLADloadproc) SDL_GL_GetProcAddress))
    {
        printf("Failed to initialize OpenGL context");
        return false;
    }
```

and you should be set.
