### ISSUE TITLE
Conan-Center package.

### ISSUE THREAD

**Issue by p-groarke** [Dav1dde/glad#118]
Having glad in Conan would be very helpful, especially since it is a build requirement for other libraries.

**Comment by p-groarke** [comment]
So I ended up making a recipe because I really wanted it. I've offered it to bincrafters, it remains to be seen whether they accept it or not. I hope you don't mind. At the very least, if you one day decide to support conan officially, you'll have a good starting example.

https://github.com/p-groarke/conan-glad

To use:
```
conan remote add p-groark https://api.bintray.com/conan/p-groarke/conan-public
```

Further instructions are on the recipe repo. Cheers.

**Comment by Dav1dde** [comment]
Thank you very much!

 I dont want to officially support external packages I am not very familiar with, already having my troubles to keep the CMake up to date.

I'll gladly put a link to your package in the documentation.

**Comment by p-groarke** [comment]
Bincrafters are interested in including and maintaining the package. I'll let you know when everything is finalized. :)

**Comment by p-groarke** [comment]
The package is up on bincrafters, you can use this badge if you want to link on your readme :
[![Download](https://api.bintray.com/packages/bincrafters/public-conan/glad%3Abincrafters/images/download.svg) ](https://bintray.com/bincrafters/public-conan/glad%3Abincrafters/_latestVersion)

Cheers!

**Comment by Dav1dde** [comment]
Thank you, this looks very useful! I'll add it when I am back at home!
