### ISSUE TITLE
Generate functions with 0 arguments using "(void)"

### ISSUE THREAD

**Issue by ferreiradaselva** [Dav1dde/glad#119]
Some functions in the C output, that have no arguments, are generated with `()` instead of `(void)`. The syntax `()` means that the function takes an arbitrary number of arguments, while the `(void)` means that the function doesn't take any argument.

The syntax `()` will generate warnings in GCC/MinGW when the warning flag `-Wstrict-prototypes` is activated. Example:
```
./glad.h:1078:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
 typedef void (APIENTRYP PFNGLFINISHPROC)();
 ^~~~~~~
```

This goes for the OpenGL functions and the function `close_gl()` in `glad.c`.

**Comment by Dav1dde** [comment]
Thanks! Fixed now, should be live today as v0.1.16
