### ISSUE TITLE
error C4996: 'strncpy' unsafe

### ISSUE THREAD

**Issue by incendor** [Dav1dde/glad#122]
Hi!

Today I generated a glad.c file and includes for C++ and OpenGL 4.4 using your webservice.

When I tried to include it in my C++ Project (#include as well as adding the glad.c file to my project) and building that, I got the following two errors:

`e:\files\opengl\glad.c(173): error C4996: 'strncpy': This function or variable may be unsafe. Consider using strncpy_s instead. To disable deprecation, use _CRT_SECURE_NO_WARNINGS. See online help for details.`

`c:\program files (x86)\windows kits\10\include\10.0.16299.0\ucrt\string.h(343): note: see declaration of 'strncpy'`

I tried reinstalling this exact windows kit but that didn't help.

Is there any way I can solve this problem? Or did i make a mistake when generating the files / integrating them into my project?

~ Incendor

**Comment by Dav1dde** [comment]
Thanks for bringing that up, that's a thing I should fix asap.

**Comment by incendor** [comment]
Since I don't want to rush you to create a fixed release, is there a simple way I can fix the generated glad.c file myself?

**Comment by Max-ChenFei** [comment]
I also meet this bug,

**Comment by Dav1dde** [comment]
Workaround is defining:

```c
#define _CRT_SECURE_NO_WARNINGS
```

before including glad. I will release an updated version within a few hours.

**Comment by incendor** [comment]
Cool, thank you very much! I'll try later today. Sorry if asking for a workaround seemed stupid, I'm super new to C++ and just following a tutorial on OpenGL right now. Thank you for your amazing generator, quick support and help! :)

~ Incendor

**Comment by Dav1dde** [comment]
Should be fixed in master, can you confirm that for me?

Try generating glad from here: http://cglad.dav1d.de/ (not that is not yet live and a different subdomain).

Thanks!

**Comment by incendor** [comment]
Worked great! :)

Now I'm getting a LINK error but I don't think that has to do with glad.

**Comment by Dav1dde** [comment]
Thanks again, I finally managed to setup a project in VC++ - works also on my end :)
