### ISSUE TITLE
Multiple drivers for different OpenGL versions.

### ISSUE THREAD

**Issue by reduz** [Dav1dde/glad#123]
What would be the best advise in the case we need to have two separate rendering backends, one for OpenGL 2.1  and one for OpenGL 3.3 core ? Is it possible to generate two binders and two includes, one for each, or should we generate a OpenGL 3.3 compatibility even if we open it in core mode?

**Comment by Dav1dde** [comment]
Depends if you need to choose at runtime (e.g. based on device capabilities):
best way is to generate OpenGL 3.3 Compatibility and limit yourself to either subset you want to use/can use at runtime (you can use the booleans provided by glad, e.g. `GLAD_GL_EXT_framebuffer_multisample`, `GLAD_GL_VERSION_3_0` etc to check if an extension/version is available.).

If you want to choose at compiletime I would generate two separate loaders and include the respective files with some buildtime magic.

**Comment by reduz** [comment]
So, generating opengl 3.3 compatibility but opening the context as core should work?

**Comment by reduz** [comment]
Would it be possible to ask GLAD to generate internal code with a prefix. so each driver can have it's own include?

**Comment by Dav1dde** [comment]
> So, generating opengl 3.3 compatibility but opening the context as core should work?

Yes. Core only restricts the functions you can use, so all functions not supported by core will either be NULL or have a garbage addres assigned to them (expect segfaults if you use them).

> Would it be possible to ask GLAD to generate internal code with a prefix. so each driver can have it's own include?

How would that look? `coreGlClear()` and `compatGlClear()` or do you have something different in mind?

**Comment by reduz** [comment]
Oh, if functions are null it should work fine then, thanks!

**Comment by Dav1dde** [comment]
> Oh, if functions are null it should work fine then, thanks!

They won't necessarily be null! Drivers tend to return garbage queried for non-supported (by the context) function!

**Comment by erwincoumans** [comment]
If we want to use glad for both EGL and OpenGL 2.x and 3.x in the same executable (switch at runtime), is that possible? Is there a way to pick a prefix, to select the right glad loader, or can we use a single glad configured with multiple --spec switches (--spec gl and --spec egl)?

**Comment by Dav1dde** [comment]
You need to generate once for every spec but you can use them together, loaders are prefixed by the spec.

**Comment by ericoporto** [comment]
I am having trouble figuring out how to have multiple glad headers in a project (say OpenGL 3 and OpenGL ES2). Things were building fine in Linux and MacOS and appeared to run. But once I tried to build on MSVC I started to get object conflicts on Windows.

**Comment by teburt** [comment]
> I am having trouble figuring out how to have multiple glad headers in a project (say OpenGL 3 and OpenGL ES2). Things were building fine in Linux and MacOS and appeared to run. But once I tried to build on MSVC I started to get object conflicts on Windows.

For this I use a single glad header that can load a number of versions of OpenGL and also each version of GLES.
I also do not link any OpenGL libs into the application and do not use more than one of the API's for a given process.
