### ISSUE TITLE
g++/gcc STATUS_ACCESS_VIOLATION on gladLoadGLLoader((GLADloadproc) glfwGetProcAddress)

### ISSUE THREAD

**Issue by BtheDestroyer** [Dav1dde/glad#124]
I've been writing a program that compiles with g++/gcc and temporarily switched over to Visual Studio for its debugger. I got OpenGL working perfectly with VS and then tried to compile the same code with g++/gcc and it crashed with the following stackdump:

```
Exception: STATUS_ACCESS_VIOLATION at eip=6116E7EE
eax=20057338 ebx=0063CC7C ecx=00000021 edx=61227D70 esi=00000021 edi=20057338
ebp=00000022 esp=0063CBC0 program=D:\3dshacking\BrewTools\Testing\Testingwin.exe, pid 17048, thread main
cs=0023 ds=002B es=002B fs=0053 gs=002B ss=002B
Stack trace:
Frame     Function  Args
```

I used gdb to find the line of the crash and it's when I call `gladLoadGLLoader((GLADloadproc) glfwGetProcAddress)`:

![gdb](https://user-images.githubusercontent.com/6555773/34180118-61f89b24-e4c2-11e7-81cd-2332cbed5542.png)

To check if it was just my code I copied the c++ example from this repo over my `main.cpp` and it gave the same result. Anyone have any ideas?

**Comment by Dav1dde** [comment]
Works with VS but not mingw gcc/g++, or on Linux? Does it crash on that exact line or in the loader function (worst case add some printf's if the debugger doesn't show properly).

What are the exact commands you use to compile and can you paste a minimal example?

**Comment by BtheDestroyer** [comment]
I'll run some tests with gdb. For now, here's the lines I'm using to compile (I've shortened verbose folder names)
main.cpp:
```
g++ -MMD -MP -MF build/Windows/main.d -g -D_WIN32 -Wall -Werror -Wextra -ansi -pedantic -c -Iinclude -Ilibs/include -fno-rtti -fno-exceptions -std=gnu++11 -c source/main.cpp -o main.o
```
for glad.c I've tried
```
gcc -MMD -MP -MF build/Windows/glad.d -Iinclude -Iinclude -Ibuild/Windows -g -D_WIN32 -c glad.c -o glad.o
```
and
```
g++ -x c -MMD -MP -MF build/Windows/glad.d -Iinclude -Iinclude -Ibuild/Windows -g -D_WIN32 -c glad.c -o glad.o
```
Linking:
```
gcc-ar -rc lib/libglad.a glad.o
g++ main.o -Llib -lglad -lglfw3 -lopengl32 -lgdi32 -o Testingwin.exe
```
I'm manually defining `_WIN32` because gcc and g++ weren't for some reason (I am indeed on Windows)

**Comment by BtheDestroyer** [comment]
So I just stepped through `gladLoadGLLoader` and then `find_extensionsGL` with gdb and here's what I found:

1. get_exts() (called at glad.c:1040) checks `if (max_loaded_major < 3)` which returns false as `max_loaded_major = 3`
2. `num_exts_i` is set to `231` by `glGetIntegerv(GL_NUM_EXTENSIONS, &num_exts_i);` (glad.c:160) so `exts_i` got set to `(const char **) 0x2003f1b0` by `(const char **)realloc((void *)exts_i, (size_t)num_exts_i * (sizeof *exts_i))`
3. glad.c:173 correctly mallocs `local_str` with a size of `(len+1) * sizeof(*exts_i)` bytes. On the first pass, this is `strlen("GL_3DFX_texture_compression_FXT1") + 1 * sizeof(char*)` or `132` bytes
4. glad.c:178 crashes as `strncpy` attempts to copy the first 33 (len+1) bytes of `gl_str_tmp` which has a size of 32 bytes to `local_str` which has a size of 132 bytes causing it to crash on the last byte.

Currently messing around to see if I can find a solution

**Comment by BtheDestroyer** [comment]
It seems like there are even weirder things going on for some reason. I checked `len` when `strncpy` was being called and it had been changed to 1 at some point. See len's value at glad.c:173 compared to glad.c:174 ![weird len](https://i.imgur.com/2wgfkKQ.png)

Replacing the `malloc(n)` call at glad.c:173 with `calloc(n,1)` to initalize local_str to be filled with 0s and changing `strncpy` at glad:178 to `strcpy` caused the first pass to be successful, but the second pass resulted in `gl_str_tmp` being set to `0x70` for some reason, so I'm back to being lost

**Comment by BtheDestroyer** [comment]
I just tried using `g++ source/main.cpp source/glad.c -Ilibs/include -o Test.exe -std=c++11 -Llibs -lglfw3 -lopengl32 -lgdi32` to compile with as little as possible and `Test.exe` still crashes. Either something's up with g++, glfw, or glad. I've already tried redownloading glfw and glad, so I'll see if I can update g++

**Comment by BtheDestroyer** [comment]
Turns out it was g++'s fault all along.

Note to anyone else with this problem: Make sure gcc/g++ is up to date.
Compiling worked when I used mingw-g++ version: (MinGW.org GCC-6.3.0-1) 6.3.0
Compiling failed when I used cygwin's g++ version: (GCC) 5.4.0

**Comment by Dav1dde** [comment]
Thanks for looking into it.
