### ISSUE TITLE
missing GL_FLAT, glNormal3f, GL_QUAD_STRIP, and a bunch of other symbols

### ISSUE THREAD

**Issue by jmbldwn** [Dav1dde/glad#125]
I am trying to use the webservice-generated glad with glfw3 and opengl.  I ran into several missing symbols when trying to compile.

I dug around, and the glad that you get when you download glfw3 as a zip (I installed my with brew) has these symbols.

Am I misusing the webservice?  How did GLFW3 create its glad module?

I'm on macOS, High Sierra, C++.  
Selected OpenGL 4.1 core and grabbed all extensions in the webservice.

**Comment by Dav1dde** [comment]
These functions are part of the 'deprecated' OpenGL profile. Simply choose Compatibility as the profile and glad will include them.

**Comment by jmbldwn** [comment]
Thanks.  For some reason I misunderstood what "compatibility" meant.  OpenGL requires learning a lot of history. :-P
