### ISSUE TITLE
Where is this documentation?

### ISSUE THREAD

**Issue by sveencoop** [Dav1dde/glad#128]
I need a more detailed information as possible on the gladLoadGLLoader function, especially with all possible errors and results

**Comment by ferreiradaselva** [comment]
`gladLoadGLLoader` is just a function that takes a pointer to a `GLADloadproc` function. This function (of typedef `GLADloadproc`), takes a string and uses one of the functions available in the OS to return a pointer to the OpenGL implementation function that has the same name in that string. You can see all that in the generated `glad.c`.
