### ISSUE TITLE
Overallocation in function get_exts()

### ISSUE THREAD

**Issue by simonfxr** [Dav1dde/glad#129]
There seems to be an oversized allocation in ```get_exts()``` at glad/lang/c/loader/gl.py, see line 57:
```char *local_str = (char*)malloc((len+1) * sizeof(*exts_i));```
The variable ```exts_i``` is of type ```const char **```, so ```sizeof (*exts_i)``` is equivalent to ```sizeof (const char *)```, but we just need ```sizeof (char)```. I would suggest to replace the line in question with:
```char *local_str = (char*)malloc((len+1) * sizeof(*local_str));```

**Comment by Dav1dde** [comment]
Thanks on first glance you seem to be correct, nice catch - I'll look into it.

**Comment by Dav1dde** [comment]
Thanks again, it is fixed now!

**Comment by simonfxr** [comment]
Thanks, that's great!
