### ISSUE TITLE
Are EGL libraries automatically loaded?

### ISSUE THREAD

**Issue by BlGene** [Dav1dde/glad#130]
I'm using glad_egl in an application. If I don't link with EGL during the build I get the runtime error:
 `undefined symbol: eglGetProcAddress`

After looking in the `glad_egl.c` I found that it didn't have the dlopen/dlsym calls that I would expect and that `glad.c` has.

For details please see: https://github.com/bulletphysics/bullet3/pull/1565#pullrequestreview-98795159

**Comment by teburt** [comment]
No, it doesn't load them.

In practice I've found that the best way to get the symbols depends on the platform or deployment scenario.

**Comment by BlGene** [comment]
@Dav1dde: Thanks, this does answer my question.
