### ISSUE TITLE
Build Error using CMake in Linux

### ISSUE THREAD

**Issue by tmarrinan** [Dav1dde/glad#134]
I am getting the following error while configuring using CMake in Linux:

```
CMake Error at CMakeLists.txt:3 (if):
   if given arguments:

     "CMAKE_VERSION" "VERSION_GREATER_EQUAL" "3.0"

   Unknown arguments specified
```

I am using Linux Mint and have CMake version 3.5.1 installed.

**Comment by tmarrinan** [comment]
A little extra digging turns up that VERSION_GREATER_EQUAL is not a valid comparison for CMake 3.5. There is only VERSION_GREATER up until CMake 3.7.

I believe the code could be changed to:

```
if (NOT CMAKE_VERSION VERSION_LESS 3.0)
```

**Comment by Dav1dde** [comment]
Thanks, definitely a bug.

**Comment by Dav1dde** [comment]
Thanks again for the quick report, I tried with versions 3.0, 3.5 and 3.10 and all seem to work.

Interestingly enough, this issue didn't exist with CMake 3.10.
