### ISSUE TITLE
Invalid statement when no extension is loaded in Nim.

### ISSUE THREAD

**Issue by krux02** [Dav1dde/glad#136]
When no extension is selected for loading glad generates an emtpy var section, which is illegal in Nim.
`findExtensionsGL` needs a discard statement when it is empty.

```nim
# Extensions
var
  # without a single entry this is illegal

#[...]#

proc findExtensionsGL() =
  discard
```

Alternatively if you do not want to treat _no extensions_ as a special case, you can give each variable it's own var section and add a doc comment to `findExtensionsGL`.

```nim
var GLAD_GL_ARB_bindless_texture*: bool
var GL_UNSIGNED_INT64_ARB*: GLenum = GLenum(0x140F)
var GLAD_GL_ARB_direct_state_access*: bool
var GL_TEXTURE_TARGET*: GLenum = GLenum(0x1006)
var GL_QUERY_TARGET*: GLenum = GLenum(0x82EA)
var GL_TEXTURE_BINDING_CUBE_MAP_ARRAY*: GLenum = GLenum(0x900A)

#[...]#

proc findExtensionsGL() =
  ## Some doc comment to make this valid even when it is empty. But it is probably 
  ## better if you put a real meaningful doc comment here.
  GLAD_GL_ARB_bindless_texture = hasExt("GL_ARB_bindless_texture")
  GLAD_GL_ARB_direct_state_access = hasExt("GL_ARB_direct_state_access")
```

**Comment by Dav1dde** [comment]
Hey,

I added the discard statement to `findExtensionsGL` also am skipping the var for `# Extensions`.

Would be great if you could try the fix, this is was generated with `--out-path=build --generator="nim" --api="gl=4.0" --spec="gl" --extensions=""`
[gl.zip](https://github.com/Dav1dde/glad/files/1782566/gl.zip) (so you don't have to generate).

**Comment by krux02** [comment]
I tried it. The files compiles. I still did not write an application with this, but it really looks like I will do it very soon. One thing I noticed though is, in the file you provided in the gl.zip, the indentation of the discard statement is four spaces, while everything else is endented with two spaces. I mean it's a generated file that does not need to be too pretty, but it is visible.

**Comment by Dav1dde** [comment]
Thanks!  Will change the indentation tonight.
