### ISSUE TITLE
problems in the Nim backend that I encountered.

### ISSUE THREAD

**Issue by krux02** [Dav1dde/glad#139]
What I fond so far when I ported over to GLAD is the following

there is no `GL_VERTEX_ARRAY`, I need it for `glObjectLabel`.

I used these arguments: `--profile="core" --api="gl=4.5" --generator="nim" --spec="gl" --extensions=""`.

It would have been nice, if you would have suggested to use SDL_GL_GetProcAddress for the load function. 

For now the first example is "ported" to work with with glad. And it works flawlessly. Thanks for making glad.

**Comment by Dav1dde** [comment]
`GL_VERTEX_ARRAY` was removed with the core profile in OpenGL 3.2. It was later reintroduced with OpenGL 4.3, it is also part of the `GL_KHR_debug` extension. So you may need to include the `GL_KHR_debug` extension.

Yes unfortunately the documention is in a horrible state.

Awesome to hear!
