### ISSUE TITLE
Clang warning -Wreserved-id-macro

### ISSUE THREAD

**Issue by ianhattendorf** [Dav1dde/glad#142]
Names beginning with double underscores are reserved by the standard. Compile with Clang and `-Wreserved-id-macro` results in warnings.

For example, in `glad.h`: `#ifndef __glad_h_`. In `khrplatform.h`: `__khrplatform_h_`.

**Comment by Dav1dde** [comment]
I can get around defining `__glad_h_` but not `__khrplatform_h_`, `__gl_h_`, `__egl_h_` etc. these macros are defined by the respective header files, e.g. [`egl.h`](https://github.com/KhronosGroup/EGL-Registry/blob/master/api/EGL/egl.h#L1) I am purposefully redefining the header guards to check if such a header has been included before and to prevent accidental inclusion after glad was included (useful for third party libraries that would include the header if it wasn previously included).

**Comment by cstoitner** [comment]
I know this is an old bug... but it's still bugging me. Could you please use `#pragma clang diagnostic` to disable the warning for this line?
```
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-id-macro"
#define __gl_h_ 1
#pragma clang diagnostic pop
```

**Comment by Dav1dde** [comment]
Might as well

**Comment by Dav1dde** [comment]
Fixed in glad2. It's just not worth doing in glad1, glad uses `__`-prefixed defines internally and it's rather complicated to fix in that code base.
