### ISSUE TITLE
GLintptr and GLsizeiptr not defined

### ISSUE THREAD

**Issue by jube** [Dav1dde/glad#149]
I generate a loader with the following command line:

```
glad --api gles2=2.0 --profile core --generator c --spec gl --out-path out --no-loader
```

But I can not compile the resulting file because `GLintptr` and `GLsizeiptr` are not defined. This bug appeared between version 0.1.13a and 0.1.14a. I think it may be related to the change of registry in commit 2e24db13434d2a802d8126549880f434e618a7bb.

I have the same bug with `--api gl=3.3`.

**Comment by Dav1dde** [comment]
I think this is related to: https://github.com/Dav1dde/glad/issues/148

Can you pull the latest version from github/pypi and try again? The website has been updated as well (if that's easier for you).

**Comment by jube** [comment]
Your fix works perfectly. Thanks a lot for this great tool!
