### ISSUE TITLE
C: Missing typedefs are causing compilation errors

### ISSUE THREAD

**Issue by matkam7** [Dav1dde/glad#150]
I am having the same problem as the person in this [reddit post]( https://www.reddit.com/r/opengl/comments/8m8h1m/trying_to_setup_opengl_with_glfw3_and_glad/).

Here is a copy of the post:

---
<p>I was following this tutorial : <a href="https://learnopengl.com/Getting-started/Creating-a-window">https://learnopengl.com/Getting-started/Creating-a-window</a> and I built GLFW and included it, downloaded GLAD for OpenGL 3.3 (tried with 4.x also), and did all the linking mentioned in the article. I also included glad.c as a source file in the project (VS2017). </p>

<p>I'm trying to compile this simple program : </p>

<pre><code>#include &lt;glad/glad.h&gt;
#include &lt;GLFW/glfw3.h&gt;

int main()
{
    return 0;
} 
</code></pre>

<p>I'm getting errors like : </p>

<pre><code>identifier "GLintptr" is undefined
identifier "GLsizeiptr" is undefined 
</code></pre>

<p>I think the issue is with GLAD but I have no clue how to fix it. Here is a screenshot for reference : <a href="https://i.imgur.com/NOlHptO.png">https://i.imgur.com/NOlHptO.png</a></p>

<p>Edit: I just added a couple of lines into glad.h and it seems to work but I'm not sure if this is a good fix</p>

<pre><code>typedef long GLintptr
typedef long GLsizeiptr    
</code></pre>

**Comment by Dav1dde** [comment]
Please update to the latest glad version (or regenerate on the website). 

If after updating/re-generating this is still a problem please reopen the issue.

Related: 

* #148 
* #149
* KhronosGroup/OpenGL-Registry#162
* KhronosGroup/OpenGL-Registry/issues/184
