### ISSUE TITLE
Static linking?

### ISSUE THREAD

**Issue by zajo** [Dav1dde/glad#152]
Trying to use glad with emscripten, is there a way to configure glad to use static linking rather than looking up functions dynamically? Dynamic lookup in emscripten doesn't work. It would be acceptable if glad simply generated a loader function which returns static function pointers based on the name passed.

Or is there some other way to make that work?

**Comment by Dav1dde** [comment]
I am assuming you're also using SDL or GLFW. You can pass either `SDL_GL_GetProcAddress` or `glfwGetProcAddress` to `gladLoadGLLoader` and it should work.

**Comment by zajo** [comment]
I am not using either, but I guess I could. The issue is that I need it to work in a "headless" configuration in emscripten on node, and last I checked `GLFW` doesn't support that. But I suppose I can pass `glfwGetProcAddress` to `gladLoadGLLLoader` anyway? Thanks.

**Comment by Dav1dde** [comment]
You can also write a loader that uses `emsrcipten_GetProcAddress` and pass it to `gladLoadGLLoader` or pass the function directly to glad, this should work.

**Comment by zajo** [comment]
Thank you, I should have seen this.
