### ISSUE TITLE
Binding OpenGL functions based on glGetString on iOS

### ISSUE THREAD

**Issue by zajo** [Dav1dde/glad#153]
I am using functions that technically require `GL_VERSION` 3.3, but `GL_VERSION` on iOS reports a lower version, which causes glad to not bind these functions even though they are in fact supported on iOS. I currently use a nasty hack to make things work, where I bind my own `glGetString` to trick glad into thinking that the supported version is 3.3, implemented as:

```
GLubyte const * (*real_glGetString)( GLenum name );

GLubyte const * glGetString_( GLenum name )
{
	if( name==GL_VERSION )
		return (GLubyte const *)("3.3 hack see " __FILE__);
	else
		return real_glGetString(name);
}
```

I'm hoping there is a better way.

**Comment by teburt** [comment]
>I am using functions that technically require GL_VERSION 3.3, but GL_VERSION on iOS reports a lower version

Isn't GL_VERSION one of 2.0, 3.0, or 3.1 on iOS?

> which causes glad to not bind these functions even though they are in fact supported on iOS

Just curious, which ones? I have been using glad on iOS for a while now but I didn't notice this yet.

**Comment by zajo** [comment]
Yeah, I knew I should have specified which functions. :) The problem is that I forgot, I don't even remember which version iOS reports; I dug up this issue from notes I had taken a month ago, and right now I'm not in a position to run my code on iOS to test. I can try to get to this in the weekend.

**Comment by teburt** [comment]
In my application code I'm using `GLAD_GL_VERSION_xxx` for desktop and `GLAD_GL_ES_VERSION_xxx` on iOS, that may be what you need to do.

**Comment by Dav1dde** [comment]
As @teburt already noted, iOS does not support OpenGL, only OpenGL ES - both versions share quite a bunch of symbols but at the end of the day they are not the same. To further look into this, can you show me the output of `glGetString(GL_VERSION)` and the symbols you expect to be there but glad doesn't load?

**Comment by Dav1dde** [comment]
I am assuming this has been resolved, please re-open/comment if it hasn't.
