### ISSUE TITLE
Initialize the functions pointers in glad.c

### ISSUE THREAD

**Issue by Kangz** [Dav1dde/glad#158]
When using glad as a static library on OSX, the linker will ignore the uninitialized variables during link, causing linking errors. See this [stackoverflow](https://stackoverflow.com/questions/19398742/os-x-linker-unable-to-find-symbols-from-a-c-file-which-only-contains-variables) for background on the issue. Can we add `= NULL;` to every declaration of a function pointer to solve this?

**Comment by Dav1dde** [comment]
Sure.

**Comment by Dav1dde** [comment]
Fixed, I'll release a new version and update the web generator as well.

**Comment by Kangz** [comment]
Thanks a lot for the quick fix!
