### ISSUE TITLE
rust&glad

### ISSUE THREAD

**Issue by whaqzhzd** [Dav1dde/glad#159]
How to use glad in rust

**Comment by Dav1dde** [comment]
This is currently still a WIP, you can checkout the [glad-rs](https://github.com/Dav1dde/glad/tree/glad-rs) branch and go from there, it also contains an [example](https://github.com/Dav1dde/glad/blob/glad-rs/example/rust/gl_glfw.rs).

```rust
    gl::load(|e| glfw.get_proc_address_raw(e) as *const std::os::raw::c_void);
```

I'll try to get that branch done and merge it back to glad2 which has the online generator available. The main issues right now are with platform dependent symbols in WGL, GLX and Vulkan.

**Comment by whaqzhzd** [comment]
Thanks.
