### ISSUE TITLE
Running glad twice is not reproducible

### ISSUE THREAD

**Issue by madebr** [Dav1dde/glad#162]
Running the following commands:
```
glad --out-path glad1 --generator c --profile core --omit-khrplatform --spec gl --api gl=3.3
glad --out-path glad2 --generator c --profile core --omit-khrplatform --spec gl --api gl=3.3
```
will generate 2 glad opengl 3.3 core loaders in the directories `glad1` and `glad2`.

The two directory trees are different however:
- they contain a different timestamp; and
- the order in which some global variables are defined in `glad.c` is different.

I would suggest to:
- add no timestamp by default or add a `--reproducible`/`--notimestamp` command line option; and
- explicitly order all variables.

Using `pip 0.1.26` from pypi

**Comment by madebr** [comment]
I have added a cmake target that regenerates the glad files when needed.
Other developers can regenerate the bindings when needed and check whether the bindings are valid.

**Comment by Dav1dde** [comment]
Fair enough.

**Comment by Dav1dde** [comment]
I just added the `--reproducible` flag which removes the current date and time from the header comment and additionally also does not fetch the specifications from Khronos but instead uses the ones packaged with the module (no danger of breaking the build when Khronos breaks the specification).

**Comment by Dav1dde** [comment]
Done, build just fails because of a Jenkins plugin upgrade which broke the Jenkinsfile.

**Comment by stgatilov** [comment]
Could someone please clarify this warning:

    if ns.omit_khrplatform:
        logger.warn('--omit-khrplatform enabled, with recent changes to the specification '
                    'this is not very well supported by Khronos anymore and may break your build.')

It was added in one of these commits.

P.S. Sorry to revive an old thread.

**Comment by Dav1dde** [comment]
"recent" changes to the sepcification(s) removed a lot of types and instead reference the types from khrplatform.h, telling glad not to include khrplatform is, depending on the selected feature set, going to produce non-compilable files.

@stgatilov in the future please just open a new issue, if the question is not related to the topic.
