### ISSUE TITLE
Doesn't work with OSMesa

### ISSUE THREAD

**Issue by u3shit** [Dav1dde/glad#167]
I don't know if glad is supposed to work with OSMesa, but currently currently it doesn't. Including `GL/osmesa.h` before glad doesn't work, because `osmesa.h` includes `GL/gl.h`. Reversing the order, it doesn't work because glad doesn't define `GLAPIENTRY` and `osmesa.h` expects it. I've managed to workaround it with
```c++
#include <glad/glad.h>
#define GLAPIENTRY APIENTRY
#include <GL/osmesa.h>
```
but it's not ideal.

Using mesa 18.1.5 and https://glad.dav1d.de/#profile=core&language=c&specification=gl&api=gl%3D3.3 (version 0.1.26) to generate glad header.

**Comment by Dav1dde** [comment]
Thanks, this is a bug. Glad should define `GLAPI` and `GLAPIENTRY`.

**Comment by Dav1dde** [comment]
Thanks, this is fixed in master/next version.

**Comment by genpfault** [comment]
Could this be extended to `GL_APIENTRY` for the OpenGL ES generators too?
