### ISSUE TITLE
glad2: GL_CLIP_DISTANCE / CLIP_PLANE and other symbols don't work with core profile

### ISSUE THREAD

**Issue by rikusalminen** [Dav1dde/glad#171]
When generating a loader with glad2 for GL 4.6 core profile, some new core profile symbols are defined in terms of old symbols only available in compatibility profile. The output header file does not work correctly (ie. using any of these flags will result in compile errors).

The following is output to gl.h:

```
#define GL_CLIP_DISTANCE0 GL_CLIP_PLANE0
#define GL_MAX_CLIP_DISTANCES GL_MAX_CLIP_PLANES
```

But `GL_CLIP_PLANEn` and `GL_MAX_CLIP_PLANES` are defined only in the compatibility profile.

There are a handful of other symbols that have the same issue, for example `#define GL_COMPARE_REF_TO_TEXTURE GL_COMPARE_R_TO_TEXTURE`.

This behavior is the same with and without "alias" flag.

Suggested fix: change the behavior so that all defines have a hexadecimal numeric constant rather than using the old name for the new symbol (this is how it is in glcorearb.h).

Sorry that I didn't fix this myself and submit pull request, I don't have python devtools at hand right now.

**Comment by rikusalminen** [comment]
I think this should fix it:

```
diff --git a/glad/generator/c/templates/template_utils.h b/glad/generator/c/templates/template_utils.h
index 0965790..0bf2796 100644
--- a/glad/generator/c/templates/template_utils.h
+++ b/glad/generator/c/templates/template_utils.h
@@ -69,7 +69,7 @@ typedef {{ type.category }} {{ type.name }} {% if type.members %}{
 {% macro write_enumerations(enumerations) %}
 {% for enum in enumerations %}
 {% call protect(enum) %}
-#define {{ enum.name }} {{ enum.alias if enum.alias else enum.value }}
+#define {{ enum.name }} {{ enum.value }}
 {% endcall %}
 {% endfor %}
 {% endmacro %}
```

**Comment by Dav1dde** [comment]
Fixed.

Thanks for the help!
