### ISSUE TITLE
Wrong names in gladLoaderLoadGLX

### ISSUE THREAD

**Issue by surafel911** [Dav1dde/glad#175]
The names listed when I downloaded glad2 using the generator I noted that the names were for the GL shared libraries rather than the GLX libraries. Hopefully I'm not missing something about how all this works but I've had programs run fine when directly linking with GLX.

**Comment by Dav1dde** [comment]
Loading is done through `glXGetProcAddressARB` which is exposed by the OpenGL shared libraries and can be used to query GLX functions. See https://www.khronos.org/registry/OpenGL/extensions/ARB/GLX_ARB_get_proc_address.txt.

If you think this should be done differently/better, let me know so I can take a look at that.

**Comment by surafel911** [comment]
I think what you use is better since, according to the page, it can load functions that may not be available to the link library. I've always linked with  libGLX and never had any issues on multiple systems so I assumed it was the best option. Looks like I have some ways to go.
