### ISSUE TITLE
WGL: wglDeleteContext not defined in wgl.h

### ISSUE THREAD

**Issue by surafel911** [Dav1dde/glad#180]
'PFNWGLDELETECONTEXTPROC' is defined in the header file but the function hasn't been defined for use. I generated a new header to make sure I hadn't accidentally deleted it.

**Comment by surafel911** [comment]
Same thing for wglGetProcAddress.

**Comment by Dav1dde** [comment]
These symbols are defined in wgl.h and can be used by linking with (iirc) `gdi32`.

**Comment by surafel911** [comment]
I am linking with gdi32. This is my Makefile.

https://gist.github.com/surafel911/138bc12d8e8211730fc172ee9bc166af

**Comment by Dav1dde** [comment]
In order to use these functions you also have to include wgl.h

**Comment by surafel911** [comment]
Here is my code and error message.

https://gist.github.com/surafel911/c10e2b0c8ddae31c43d6c7fa13071c79

`
MESSAGE: Entering directory `D:\coding\qubit-engine'
C:\Windows\system32\cmd.exe /C make
----------Building project:[ qubit-engine - Debug ]----------
clang -g -m64 -Wall -Werror -std=c99  -Iinclude/  -lgdi32 -luser32 src/*.c src/winapi/*.c src/opengl/*.c src/vulkan/*.c \
		test/*.c -o bin/qubit
opengl-0a37ee.o : error LNK2019: unresolved external symbol __imp_wglDeleteContext referenced in function platform_opengl_context_destroy
wgl-284332.o : error LNK2019: unresolved external symbol __imp_wglGetProcAddress referenced in function gladLoaderLoadWGL
bin/qubit : fatal error LNK1120: 2 unresolved externals
clang.exe: error: linker command failed with exit code 1120 (use -v to see invocation)
make: *** [test] Error 96
====1 errors, 0 warnings====
`

**Comment by Dav1dde** [comment]
Try linking with both `opengl32` and `gdi32`.

**Comment by surafel911** [comment]
It works, but I thought that glad would handle `opengl32` symbols and link them at run-time, like with `glXGetProcAddress`?

**Comment by Dav1dde** [comment]
It does, the thing is `wglGetProcAddress` which is used to load WGL is defined in `opengl32` (I mistakenly thought it was part of `gdi32` above), the rest is all done at runtime, dynamically.

**Comment by surafel911** [comment]
Thanks man. You may want to consider having a page with information like this, similar to what glfw has for your code.

**Comment by Dav1dde** [comment]
Agreed there should be and it's on my TODO, for quite a while now .. :(
