### ISSUE TITLE
WGL: GLAD_WGL_VERSION_1_0 always 0

### ISSUE THREAD

**Issue by surafel911** [Dav1dde/glad#182]
Undefined references to `wglDeleteContext` and, returned for round two, `wglGetProcAddress`. Last time I made an issue for `wglGetProcAddress` I was using clang and compiling with  `-lgdi32 -lopengl32 -luser32` libraries. Now I've switched to mingw-w64 with the `-mwindows -lgdi32 -lopeng32`.

Last time adding `-lopengl32` worked fine but my program would always crash when trying to call `gladLoaderLoadWGL` and would fail trying to get the extension strings.

`wglDeleteContext` isn't defined in the `wgl.h` even though both kinds of create context functions are defined. I thought the solution was going to be similar to how I solved the issues with `wglGetProcAddress` by including `-lgdi32` in my Makefile but it hasn't worked.

Any ideas?

**Comment by surafel911** [comment]
Also sorry you keep hearing from me xD

**Comment by Dav1dde** [comment]
Not sure if I understand your problem.

 `wglDeleteContext` is part of WGL 1.0 like `wglGetProcAddress`, WGL 1.0 is not included in glad and comes from Windows (`wingdi.h` to be exact, which is included by `windows.h`). Compiling with `-lgdi32 -lopengl32` for mingw does work, note compiler flags are not order independent so maybe you're passing them too early or for the wrong files.

Glad 2 has a test for this, maybe this helps you: https://github.com/Dav1dde/glad/blob/glad2/test/c/run/wgl/default/001/test.c 

It includes the sources and compiler flags.

**Comment by surafel911** [comment]
It was the compiler flag order. It compiles but now when I runs, `GLAD_WGL_VERSION_1_0 is 0.

**Comment by Dav1dde** [comment]
This is a bug, but you can safely ignore that flag since WGL 1.0 is *always* available on Windows (and doesn't come from glad).

**Comment by surafel911** [comment]
Does this bug also affect other WGL flags because `GLAD_WGL_ARB_make_current_read` and `GLAD_WGL_ARB_create_context` are also not working for me.

**Comment by Dav1dde** [comment]
No extensions symbols should work, if you have either the `WGL_ARB_extensions_string` or the `WGL_EXT_extensions_string` extension. You might wanna debug into `has_ext` to see what is going on or check if your extensions are supported. If you should have those extensions and it still doesn't show up please let me know what happens in `has_ext`.

**Comment by surafel911** [comment]
I debugged into `gladLoadWGLUserPtr` and the first if statement is failing.

**Comment by surafel911** [comment]
Any news or are you gone for the holiday lol?

**Comment by surafel911** [comment]
Hey dude, anything going on?

**Comment by surafel911** [comment]
Hey dude, anything going on?

**Comment by Dav1dde** [comment]
Sorry, I currently don't have much time for glad.

This if is failing? `if(wglGetExtensionsStringARB == NULL && wglGetExtensionsStringEXT == NULL) return 0;`

This seems to be a bug, this if should look like `if(wglGetExtensionsStringARB == NULL || wglGetExtensionsStringEXT == NULL) return 0` - `||` instead of `&&`. Can you try updating the condition?

**Comment by surafel911** [comment]
Behavior is the same; function still returns 0.

**Comment by Dav1dde** [comment]
Thanks, can you check if your system supports either `wglGetExtensionsStringARB` or `wglGetExtensionsStringEXT`?

**Comment by Dav1dde** [comment]
Closing for no more activity, feel free to re-open.
