### ISSUE TITLE
D generated bindings are missing some symbols

### ISSUE THREAD

**Issue by AndrejMitrovic** [Dav1dde/glad#184]
Just ran it now after installing with `pip` (sorry there's no `-v` or `--version` so I'm not sure which version of glad this is).

I ran it with:

```
$ glad --generator=d --out-path=.
```

But then it doesn't compile:

```
C:\dev\glad-generated>rdmd --build-only --main glad\gl\all.d
glad\gl\ext.d(1466): Error: undefined identifier GLeglClientBufferEXT
glad\gl\ext.d(1839): Error: undefined identifier GLVULKANPROCNV
glad\gl\ext.d(1467): Error: undefined identifier GLeglClientBufferEXT
```

This is on Windows, using DMD v2.082.1

**Comment by Dav1dde** [comment]
Symbols of newly added extensions are missing, definitely a bug, but as a workaround if you only select the extensions what you actually need it may work.

**Comment by AndrejMitrovic** [comment]
Thanks @Dav1dde, will give it a shot.
