### ISSUE TITLE
glGetNamedBufferParameteriv missing from glad.c

### ISSUE THREAD

**Issue by matwatson** [Dav1dde/glad#187]
Visual Studio auto complete finds glGetNamedBufferParameteriv while code editing, the code compiles without errors, but the linker fails with unresolved symbol glad_glGetNamedBufferParameteriv.

While debugging, I ran across a Visual Studio feature that shows which functions were inside glad.c, but glad_glGetNamedBufferParameteriv was missing; glad_glGetBufferParameteriv was in the list and builds fine. I wish I could name the feature, but my VS skill is low. So I think the function is missing from glad.c, but I am not sure.

This is a bug report only. I am working around by using the non Named version of the function.

Here is the version info copied from the header (or c) file that I generated using the web interface.
    Commandline:
        --profile="core" --api="gl=4.6" --generator="c" --spec="gl" --extensions=""

**Comment by Dav1dde** [comment]
I cannot reproduce this problem:

```
lutetium :: workspaces/python/glad ‹master› % python -m glad --out-path=build --profile="core" --api="gl=4.6" --generator="c" --spec="gl" --extensions="" && cd build && gcc -c -o glad.o src/glad.c -Iinclude -ldl
[11/12/2018 22:56:16][INFO  ][glad      ]: using local specification: 'gl.xml'
[11/12/2018 22:56:16][INFO  ][glad      ]: generating 'gl' bindings
[11/12/2018 22:56:16][INFO  ][glad.opener   ]: saving: 'file:/home/dav1d/workspaces/python/glad/khrplatform.h' to '/home/dav1d/workspaces/python/glad/build/include/KHR/khrplatform.h'
[11/12/2018 22:56:16][INFO  ][glad      ]: generating 'gl' bindings - done

lutetium :: python/glad/build ‹master› % grep -r "glad_glGetNamedBufferParameteriv\|glad_glGetBufferParameteriv"
Binary file glad.o matches
include/glad/glad.h:GLAPI PFNGLGETBUFFERPARAMETERIVPROC glad_glGetBufferParameteriv;
include/glad/glad.h:#define glGetBufferParameteriv glad_glGetBufferParameteriv
include/glad/glad.h:GLAPI PFNGLGETNAMEDBUFFERPARAMETERIVPROC glad_glGetNamedBufferParameteriv;
include/glad/glad.h:#define glGetNamedBufferParameteriv glad_glGetNamedBufferParameteriv
src/glad.c:PFNGLGETBUFFERPARAMETERIVPROC glad_glGetBufferParameteriv = NULL;
src/glad.c:PFNGLGETNAMEDBUFFERPARAMETERIVPROC glad_glGetNamedBufferParameteriv = NULL;
src/glad.c: glad_glGetBufferParameteriv = (PFNGLGETBUFFERPARAMETERIVPROC)load("glGetBufferParameteriv");
src/glad.c: glad_glGetNamedBufferParameteriv = (PFNGLGETNAMEDBUFFERPARAMETERIVPROC)load("glGetNamedBufferParameteriv");

lutetium :: python/glad/build ‹master› % nm glad.o | grep "glad_glGetNamedBufferParameteriv\|glad_glGetBufferParameteriv"
00000000000006a0 B glad_glGetBufferParameteriv
0000000000000768 B glad_glGetNamedBufferParameteriv
```

The first command builds glad with your selected parameters and compiles the glad source into a binary, the second command looks for the string `glad_glGetNamedBufferParameteriv` or `glad_glGetBufferParameteriv` anywhere in the sources - for both GL commands the same code was generated. The third command searches through the compiled binary as it is seen by the linker and the output shows both symbols exist.

Can you upload your glad sources (glad.c and glad.h), so I can check your sources (you can pack them into a zip and upload to this issue tracker)?

Alternatively you can try re-generating the files and trying again, maybe something corrupted your files (very unlikely but worth a try).

**Comment by matwatson** [comment]
Thank you. I attached the files that produced the error on my system. Now that I've seen what you did, I will try to find glad.o and then see if I can find a Windows command that does what nm does.
[issue-187-files.zip](https://github.com/Dav1dde/glad/files/2583223/issue-187-files.zip)

**Comment by Dav1dde** [comment]
Sorry for looking into it just now, but it seems like the symbols are there in the file you uploaded.

![image](https://user-images.githubusercontent.com/255721/48978827-2f1bdc00-f0b2-11e8-8990-8fb6a46dde90.png)

![image](https://user-images.githubusercontent.com/255721/48978832-3e028e80-f0b2-11e8-983c-78cf67ff0cfc.png)

And using the files you uploaded I can build and run an example application:

![image](https://user-images.githubusercontent.com/255721/48978874-dd278600-f0b2-11e8-9b2a-1e2ae3f9efad.png)

**Comment by matwatson** [comment]
Thank you.

I wanted to point out that I too have the definition (= NULL as you show), and Visual Studio shows the symbol in violet, which indicates it is defined.
![image](https://user-images.githubusercontent.com/12010232/48980547-6f159b80-f07f-11e8-9bf6-ddd525ef22e7.png)
This is as earlier.

Earlier the linker failed (several tries over a period of days), but now it compiles, links, and runs fine. But I did not change my headers since submitting this report. I am so confused. And happy that it works now.

My apologies for reporting a problem that just vanished without cause.  Thanks again for your help. I was duplicating what you tried when the problem solved itself.

**Comment by Dav1dde** [comment]
Good to hear that it works now!
