### ISSUE TITLE
The glad web service does not include WGL or GLX in the drop-down.

### ISSUE THREAD

**Issue by chapmanworld** [Dav1dde/glad#190]

**Comment by Dav1dde** [comment]
![image](https://user-images.githubusercontent.com/255721/49341276-568f1d80-f64b-11e8-8372-ec84cab7bf25.png)

I cannot reproduce this on http://glad.dav1d.de any more information?

**Comment by chapmanworld** [comment]
I've been having this issue for days, only "OpenGL" would appear in the drop-down (FireFox & Edge).
After you replied that you cannot reproduce, I now no longer get this issue.
I do not know if you changed anything, or perhaps there was a caching issue? 
Never the less, the problem now appears resolved and I will close this issue. Thank you.

**Comment by chapmanworld** [comment]
++ More information.
It's when selecting 'Pascal' for output, the available specifications drop-down reduces to OpenGL only.

**Comment by Dav1dde** [comment]
The pascal generator currently only supports OpenGL that's why I removed the other options for Pascal, hope that clears it up.
