### ISSUE TITLE
Compressed Image Extensions

### ISSUE THREAD

**Issue by tmarrinan** [Dav1dde/glad#194]
When using glad and compressed DXT1 textures, I get an error that `GL_COMPRESSED_RGB_S3TC_DXT1_EXT` is undefined. However, my system does support them and if I manually add the following (taken from glcorearb.h), my program works fine:

```
#ifndef GL_EXT_texture_compression_s3tc
#define GL_EXT_texture_compression_s3tc 1
#define GL_COMPRESSED_RGB_S3TC_DXT1_EXT   0x83F0
#define GL_COMPRESSED_RGBA_S3TC_DXT1_EXT  0x83F1
#define GL_COMPRESSED_RGBA_S3TC_DXT3_EXT  0x83F2
#define GL_COMPRESSED_RGBA_S3TC_DXT5_EXT  0x83F3
#endif
```

Is their a reason these are not defined in glad?

**Comment by Dav1dde** [comment]
You need to tell glad to include the extension, on the web generator you can just click on it (search for the name), via command line you have to include it in the `--extensions` argument.

**Comment by tmarrinan** [comment]
I used CMake to build / install glad. Under GLAD_EXTENSIONS, the description says "Path to extensions file or comma separated list of extensions, if missing all extensions are included".
I took this to mean that if I left it blank, then all extensions would be included. Is this an incorrect interpretation of "if missing all extensions are included"?

**Comment by Dav1dde** [comment]
@tmarrinan That's an open issue with CMake https://github.com/Dav1dde/glad/pull/160 

As annoying it may seem for now it's usually better/preferred to add only the extension you need/want to support. 

I'll see if I figure out a good way how to solve this over the holidays.

**Comment by tmarrinan** [comment]
Aha! I looked through issues before posting, but didn't look at pull requests.
Thanks!
