### ISSUE TITLE
glad -h help for API argument

### ISSUE THREAD

**Issue by maartenuni** [Dav1dde/glad#196]
The documentation that the argparse module gives for the API is a little bit misleading.

I'm using the following version of glad:
```
$pip3 show glad
Name: glad
Version: 0.1.28
```
Argparse shows the following doc:
```
  --api API             API type/version pairs, like "gl=3.2,gles=", no
                        version means latest
```
However, when I use that in the following example:

```
glad    --omit-khrplatform      \
        --local-files           \
        --profile core          \
        --generator c           \
        --extensions /dev/null  \
        --api gl=3.3,gles=2.0  \
        --out-path .            \
        --spec gl
```
This raises the following error:
```
ValueError: Unknown API "gles" for specification "gl"
```
The however, if I use --api gl=3.3,gles**2**, glad does it's job successfully. I'm quite new to opengl, and perhaps this is very clear to someone with more opengl experience than I have. For me as newcomer to opengl/glad its very nice when I can use the examples from argparse, without ValueErrors

Best regards,

**Comment by Dav1dde** [comment]
Yeah this should/could be better!

For now if you want to see all available combinations you can check the [web service](https://glad.dav1d.de/)-

**Comment by maartenuni** [comment]
Thanks yes, I know, that is how I found out, that appending the "2" to gles worked :)

**Comment by fluffrabbit** [comment]
GLES1 is a separate API. GLES3 builds on GLES2, like how Glad loads newer GL but Windows only shipped with GL 1.1. GLES2 is the baseline version of the current mobile API.

**Comment by maartenuni** [comment]
@fluffrabbit Many thanks for the additional info. I would like to add support for the raspberrypi in my project which supports GLES2 if I'm not mistaken. Additionally, I would like to support regular x86(_64) platforms as well where OpenGL version > 3.3 with the core profile. Hence, I'm very glad, there are projects like glad/glew that help me in this process.

**Comment by fluffrabbit** [comment]
Okay, no problem.

**Comment by Dav1dde** [comment]
This is a bit of a chicken-egg problem. Glad only knows the available APIs after parsing the XML, in order to parse the XML options are required or files need to be downloaded (which is not desirable for `-h`).

I improved the error message to include the available APIs.
