### ISSUE TITLE
gladLoadGLLoader() fails randomly

### ISSUE THREAD

**Issue by Elmi77** [Dav1dde/glad#200]
I have a situation where gladLoadGLLoader() fails - but not reproducible. It works perfectly when using Windows. It fails in about 10% of the tries with Ubuntu running in a VM. And it fails in about 90% of the tries with Ubuntu running on a real hardware.

The reason for the failure is the call to "if(glGetString(GL_VERSION) == NULL)" - but the OpenGL context exists at this point, elsewhere it would fail in 100% of all cases/platforms.

Any idea what could cause this?

**Comment by Dav1dde** [comment]
`glGetString` should generate an error which you can retrieve with `glGetError`, what does it say?

**Comment by Elmi77** [comment]
Sorry for the delayed answer: glGetError() does not return an error code, it comes back with GL_NO_ERROR.

**Comment by Dav1dde** [comment]
Is it possible for it to  be a driver issue? Old driver, non mainstream etc.?

Alternatively the loader function passed to gladLoadGLLoader may return a wrong handle for `glGetString`.

**Comment by Elmi77** [comment]
It happens on Ubuntu 18.04 as well as on 14.04 - but only on one users side. I never have seen this issue, neither on Windows nor on Ubuntu 14.04/18.04. So no idea if it is a driver mashup...thanks for the information!

**Comment by Dav1dde** [comment]
I assume this is done, if you have more information and this isn't resolved, feel free to re-open. If you found a solution, feel free to add it for others.
