### ISSUE TITLE
Add a way to get the glad version

### ISSUE THREAD

**Issue by PlanetVaster** [Dav1dde/glad#204]
I like to log version info, and it doesn't seem glad has a way to get the glad version (ex. 0.1.29). Could you add a way to get it, please?

**Comment by Dav1dde** [comment]
You need the glad version logged when launching it via commandline?

If you're using glad as a python module you can import the version.

**Comment by PlanetVaster** [comment]
I'm using it in a C++ application, not python. Most things I use have a way to get the version, which I like to log for debugging purposes. For example, I use glad in conjunction with glfw, which has the method glfwGetVersionString(). Something similar to that would be nice, it's not important but shouldn't be that much extra work/code.

**Comment by Dav1dde** [comment]
I added this to glad2, I decided not to add it to glad1.
