### ISSUE TITLE
Incorrect Feature Items Included

### ISSUE THREAD

**Issue by ForeverZer0** [Dav1dde/glad#207]
While writing my own similar application for generating C# bindings, I was using this as a baseline for checking the correct items were being generated in my own application, and my own results were consistently getting slightly fewer results.

After doing some comparing, I noticed the problem was actually this generating some items that should not be. I have not done in-depth testing to see if this happens for all configurations, but the following example will illustrate the issue.

Example:
> **Language:** `C/C++`
> **Specification:** `OpenGL`
> **API:** `GL_VERSION_3_3`
> **Profile:** `Core`
> **Extensions:** `None`

This generates accurately up to one point: It includes the 29 commands that should only be included if using compatibility profile, show here in the registry `g;.xml` file (end of `GL_VERSION_3_3` feature set):

```xml
    <require profile="compatibility" comment="Reuse ARB_vertex_type_2_10_10_10_rev compatibility profile">
      <command name="glVertexP2ui"/>
      <command name="glVertexP2uiv"/>
      <command name="glVertexP3ui"/>
      <command name="glVertexP3uiv"/>
      <command name="glVertexP4ui"/>
      <command name="glVertexP4uiv"/>
      <command name="glTexCoordP1ui"/>
      <command name="glTexCoordP1uiv"/>
      <command name="glTexCoordP2ui"/>
      <command name="glTexCoordP2uiv"/>
      <command name="glTexCoordP3ui"/>
      <command name="glTexCoordP3uiv"/>
      <command name="glTexCoordP4ui"/>
      <command name="glTexCoordP4uiv"/>
      <command name="glMultiTexCoordP1ui"/>
      <command name="glMultiTexCoordP1uiv"/>
      <command name="glMultiTexCoordP2ui"/>
      <command name="glMultiTexCoordP2uiv"/>
      <command name="glMultiTexCoordP3ui"/>
      <command name="glMultiTexCoordP3uiv"/>
      <command name="glMultiTexCoordP4ui"/>
      <command name="glMultiTexCoordP4uiv"/>
      <command name="glNormalP3ui"/>
      <command name="glNormalP3uiv"/>
      <command name="glColorP3ui"/>
      <command name="glColorP3uiv"/>
      <command name="glColorP4ui"/>
      <command name="glColorP4uiv"/>
      <command name="glSecondaryColorP3ui"/>
      <command name="glSecondaryColorP3uiv"/>
    </require>
```

Those specific commands should be included in a Compatibility profile, though Core profile was chosen.

**Comment by Dav1dde** [comment]
Thanks, the profile attribute on require tags does not get evaluated.

Maybe glad2 (Branch in this repository) may be something for your C# project. You can write generators more easily now and provide them as an [extensions](https://github.com/Dav1dde/glad/wiki/Extending-Glad).

E.g. the [Rust generator](https://github.com/Dav1dde/glad/blob/glad2/glad/generator/rust/__init__.py) and [template](https://github.com/Dav1dde/glad/blob/glad2/glad/generator/rust/templates/impl.rs), which doesn't have to deal with generating header files.

**Comment by ForeverZer0** [comment]
Will definitely take a look at the templates, really like that idea. My Python-foo is a bit lacking as I rarely use it, but I am sure I could stumble my way through it lol.

Was originally using the C/C++ headers generated from this, and using elaborate regular expressions to pick out info and generate C# bindings for a hobby project, and although it (mostly) worked, was not pretty at all. Ended up writing a generator that parses the XML, which is much cleaner, though still working on writing it out to files in a coherent manner and covert the pointer types appropriately to managed code. Will check out glad2 templates and see if they offer an easier solution, thanks. :)

**Comment by hypercyl** [comment]
ss

**Comment by Dav1dde** [comment]
I don't think this is something to fix for glad 1, unfortunately there are just too many edge cases which were not considered for glad 1.
