### ISSUE TITLE
Problem running examples on OSX

### ISSUE THREAD

**Issue by hoonkai** [Dav1dde/glad#212]
Basic Info:
system: macOS High Sierra(10.13.6)
editor : vs code(latest version)
Compiler: g++ (Xcode 9.4)
Target：deploy GLFW + GLAD

**Question Description:**
I'm getting started with glad and wanted to try the example `example/c++/hellowindow2.cpp` and `example/c++/sdl.cpp`. I've installed GLFW and run

`g++ example/c++/hellowindow2.cpp -Iinclude src/glad.c -lglfw -ldl`

But all I get is a warning message `clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]`. Am I meant to see a window displayed rather than nothing at all?

Also, I've tried `g++ example/c++/sdl.cpp -Iinclude src/glad.c -lglfw -ldl`, but I get
```
clang: warning: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Wdeprecated]
Undefined symbols for architecture x86_64:
  "_SDL_CreateRenderer", referenced from:
      _main in sdl-341aa5.o
  "_SDL_CreateWindow", referenced from:
      _main in sdl-341aa5.o
  "_SDL_DestroyRenderer", referenced from:
      _main in sdl-341aa5.o
  "_SDL_DestroyWindow", referenced from:
      _main in sdl-341aa5.o
  "_SDL_GL_CreateContext", referenced from:
      _main in sdl-341aa5.o
  "_SDL_GL_DeleteContext", referenced from:
      _main in sdl-341aa5.o
  "_SDL_GL_GetProcAddress", referenced from:
      _main in sdl-341aa5.o
  "_SDL_GL_SwapWindow", referenced from:
      _main in sdl-341aa5.o
  "_SDL_GetError", referenced from:
      _main in sdl-341aa5.o
  "_SDL_Init", referenced from:
      _main in sdl-341aa5.o
  "_SDL_PollEvent", referenced from:
      _main in sdl-341aa5.o
  "_SDL_Quit", referenced from:
      _main in sdl-341aa5.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I already have `sdl2 2.0.9_1` installed though.

Any help appreciated.

**Comment by Dav1dde** [comment]
Did you run the executable that was produced after compiling? There should be a file called `a.out` after running the gcc command.

For the SDL example, you need to link with SDL instead of glfw (`-lsdl` or `-lsdl2`). This will also produce a `a.out` file which you can run.
