### ISSUE TITLE
Can't compile GLAD for GLES 2.0; redeclared as different kind of symbol

### ISSUE THREAD

**Issue by devvoid** [Dav1dde/glad#213]
Trying to compile a simple OpenGL application with GLAD, but I get a ton of warnings about things being "redeclared as a different kind of symbol".

Here are my settings on the online generator:

Language: C/C++
GL: None
GLES1: None
GLES2: 2.0
GLSC2: None
Specification: OpenGL
Profile: Compatability
No extensions.
Generate a Loader is checked, the other two checkboxes are not.

This happens with a completely empty main.c that does nothing but `#include "glad/glad.h"` and immediately `return 0;`. Replacing the ES 2.0 version with 3.3 causes it to compile perfectly.

**Comment by Dav1dde** [comment]
I can't reproduce this.

![image](https://user-images.githubusercontent.com/255721/58746365-c137df00-845d-11e9-83cc-d265f32fa8f6.png)

**Comment by devvoid** [comment]
Here's a minimal reproduction of the issue:

[glad.zip](https://github.com/Dav1dde/glad/files/3244034/glad.zip)

**Comment by Dav1dde** [comment]
I still cannot reproduce the issue with your build.

![image](https://user-images.githubusercontent.com/255721/58752455-4b5c6380-84af-11e9-8765-c6514c5f85a0.png)

![image](https://user-images.githubusercontent.com/255721/58752461-5c0cd980-84af-11e9-9c38-c51051bd1aac.png)

Please share the complete command you're using to compile and all files.

**Comment by devvoid** [comment]
I'm using the included makefile from the zip I uploaded. GCC version is 7.4.0

**Comment by devvoid** [comment]
Here's the full error log I get from trying to build, putting it in a text file because it's pretty long.

[errorlog.txt](https://github.com/Dav1dde/glad/files/3244189/errorlog.txt)

**Comment by devvoid** [comment]
After some additional experimentation, I think I've found the actual issue. It seems like including GLAD, and then including GLFW/glfw3.h immediately afterwards is what causes this to happen. If I include one or the other, it works fine.

**Comment by Dav1dde** [comment]
That's to be expected, glfw includes the gl headers by default. See: https://www.glfw.org/docs/latest/build.html#build_include and define `GLFW_INCLUDE_NONE` before including glfw.

**Comment by devvoid** [comment]
That worked, thanks for the help!
