### ISSUE TITLE
Please add the cmake variables to supply the pre-downloaded files

### ISSUE THREAD

**Issue by yurivict** [Dav1dde/glad#216]
File downloads aren't allowed during package build.

Please allow to supply these files via cmake variables.

**Comment by Dav1dde** [comment]
You can workaround this buy supplying the specifications in the cwd. Glad will look for a file called `{spec}.xml` in the cwd. Alternatively you can use a reproducible build, glad will use packaged specifications (`--reproducible` or `GLAD_REPRODUCIBLE` in cmake).

**Comment by yurivict** [comment]
This works, thanks!
