### ISSUE TITLE
Including glad.h in multiple files causes build error

### ISSUE THREAD

**Issue by Llcoolsouder** [Dav1dde/glad#218]
In order to use GL functions in more than one cpp file, I have included `glad.h` in two separate cpp files. Without glad.h, the `gl<whatever>` functions are undefined and cause a build error, but if I include glad.h in both files, the following code from `glad.h` triggers an error.
```
#ifdef __gl_h_
#error OpenGL header already included, remove this include, glad already provides it
#endif
#define __gl_h_
```

My application builds and works fine if I comment out the `#error` line

**Comment by fluffrabbit** [comment]
Forgive my ignorance, but it seems a bit strange that defines would persist across different object files.

**Comment by Llcoolsouder** [comment]
@fluffrabbit I'm not sure if I understand what you mean, so forgive me if I'm explaining something obvious to you.

In C and C++, once the compiler hits a `#define FOO`, `FOO` is then defined for the duration of compilation. So in this case, if the compiler hits 
```
#ifndef __glad_h_
#define __glad_h_
```
the first time it sees this file, `__glad_h_` will not be defined so the compiler should continue compiling this file. The next time around, `__glad_h_` should already be defined even though glad.h is being included from a different file, thus the compiler should skip over and never hit this error message. Or so I thought.

**Comment by fluffrabbit** [comment]
Wouldn't it depend on compilation steps? You compile thing1.o with one command, thing2.o with another, and link them. Defines do not carry over in that case.

**Comment by teburt** [comment]
> In C and C++, once the compiler hits a #define FOO, FOO is then defined for the duration of compilation

Yes, but the duration of compilation does not span across multiple cpp file. Each file becomes it's own translation unit; unless maybe if one cpp file includes another cpp file or something odd.

**Comment by Dav1dde** [comment]
I assume you have an include like glfw placed before glad which defines __gl_h, move glad up in the include list and include it first.

**Comment by Dav1dde** [comment]
I'll close this for inactivity if you still have this problem feel free to comment.
