### ISSUE TITLE
is it possible to conv glad in Android for gl?

### ISSUE THREAD

**Issue by lic5663** [Dav1dde/glad#221]
I want to make a logic that can run on android and Windows.
i can make extend apple with GL and GLES compiles, but yours doesn't support android GL.
i wonder youre goin to support android or not

**Comment by Dav1dde** [comment]
As far as I am aware "Android GL" is simply OpenGL ES. Glad does infact support generating and loading OpenGL ES.

Does that answer your question?

**Comment by fluffrabbit** [comment]
All of my Glad-dependent code in theory works on Android, and it runs pretty well on the web via Emscripten. But Android is a little weird when it comes to context initialization, and so far I haben't attempted to crack it. Generally using Glad in conjunction with SDL is the preferred route on that platform, though maybe SFML supports Android now as well.
