### ISSUE TITLE
glad2 loader is closing library immediately

### ISSUE THREAD

**Issue by ctenter-scs** [Dav1dde/glad#222]
The generated glad2 C code automatically unloads the opengl library after loading all the function pointers.

Consider keeping the library loaded until the application is done and explicitly calls gladLoaderUnloadGL().

I used these options in the generator (multicontext + loader):

* Loader generated by glad 2.0.0-beta on Mon Jul  8 09:32:32 2019
 *
 * Generator: C/C++
 * Specification: gl
 * Extensions: 603
 *
 * APIs:
 *  - gl:compatibility=4.6
 *
 * Options:
 *  - MX_GLOBAL = False
 *  - ON_DEMAND = False
 *  - LOADER = True
 *  - ALIAS = False
 *  - HEADER_ONLY = False
 *  - DEBUG = False
 *  - MX = True

**Comment by Dav1dde** [comment]
Is this actually a problem for you, this should be fine for OpenGL, because all symbols come from the loader function and not the DLL.

This is different for GLES and all other APIs.

**Comment by ctenter-scs** [comment]
Ah I see now. That makes sense. All good :-)
