### ISSUE TITLE
glad_wgl.c / APIENTRYP : compilation issue in version 1.32 & 1.31

### ISSUE THREAD

**Issue by shadd3** [Dav1dde/glad#226]
Hi,

In vs2017 c++; with the lastest version of glad (1.32); a compilation issue occurs:

```
glad_wgl.c(90): error C2143: syntax error: missing ')' before '*'
````
Recently  the macro APIENTRY has been undefined by your generator:

```
#if defined(_WIN32) || defined(__CYGWIN__)
#undef APIENTRY    <===============================
#include <windows.h>
static HMODULE libGL;
```

From my side , the version 1.28 is correct; and apprently it's ok up to 1.30 :

```
#if defined(_WIN32) || defined(__CYGWIN__)
#include <windows.h>
static HMODULE libGL;
```
Many thanks

**Comment by Dav1dde** [comment]
Thanks, this should be fixed now. 

the diff is:

```
#if defined(_WIN32) || defined(__CYGWIN__)
#ifndef _WINDOWS_
#undef APIENTRY
#endif
#include <windows.h>
static HMODULE libGL;
```

This is unfortunately a bit tricky, glad redefines a few `windows.h` macros (actually only `APIENTRY`) if `windows.h` was not previously included. If you include `windows.h` after, this breaks with the existing symbols.
