### ISSUE TITLE
Add extern "C" guard in the generated glad.c

### ISSUE THREAD

**Issue by blackball** [Dav1dde/glad#227]
I am not sure if this is a good idea. 

I was compiling glad.c with my C++ codes using g++. It caused lots of link errors because compiling glad.c as C++ codes generated totally different function signatures compare against the ones defined in glad.h. 

Simply add an extern "C" in glad.c could resolve this issue. Also compiling glad.c with gcc and link it against to other C++ objects will work as well.

Adding extern "C" in glad.c will not affect anything when we use a C compiler. But I am not sure if it will cause some different behavior when we use a C++ compiler. If it's also fine, then I think adding the extern guard will save us a bit of time, sometimes. 

Note that this is not strong suggestion, but maybe some minor enhancement in my point of view.

**Comment by Dav1dde** [comment]
Implemented for glad2
