### ISSUE TITLE
Impossible to specify all extensions using CMake

### ISSUE THREAD

**Issue by jackrabbit128** [Dav1dde/glad#230]
The documentation claims that it should be possible not to specify (a file containing ) a list of extensions for which to generate code.

However, `CMakeLists.txt` always passes `--extensions=${GLAD_EXTENSIONS}` to the Python program. As far as I understand, this makes it impossible to use cmake and not have to specify the list of extensions.

**Comment by jackrabbit128** [comment]
I just noticed that PR #160 was supposed to fix this issue. However, it looks to me like that code never made it into the master branch.

**Comment by Dav1dde** [comment]
The code is a breaking change, I would prefer a change only within the cmake which is at least somewhat compatible with existing setups (at max a very minimal change required for users). I'll see what I can do tomorrow, I have an relatively easy fix in mind.

**Comment by jackrabbit128** [comment]
I think I have got a decent patch. Will try to make a pull request.

**Comment by jackrabbit128** [comment]
See PR 232.

**Comment by Dav1dde** [comment]
Thanks!

This has been fixed with #232 in commit https://github.com/Dav1dde/glad/commit/2a5ac49ba7b5275e6f0f6d1fa07bfb0e6875ce18
