### ISSUE TITLE
Please add a file gladConfig.cmake

### ISSUE THREAD

**Issue by AlexandrParkhomenko** [Dav1dde/glad#231]
Need integration with CMake
For Linux is quite suitable:
(https://github.com/AlexandrParkhomenko/aur/blob/master/glad/src/glad/gladConfig.cmake)

**Comment by Dav1dde** [comment]
From what I understand a config is used together with `find_package`. Installing glad globally or for multiple packages doesn't really make sense, the intended usage is to generate/download a loader for each of your projects.

Is there another usecase I am missing?

**Comment by AlexandrParkhomenko** [comment]
Thank. I saw that a global library is being created in the installation package. It became clear to me why it does not work even with examples.

**Comment by Dav1dde** [comment]
I assume this is resolved then, if not feel free to comment/re-open.

**Comment by jjYBdx4IL** [comment]
cmake has ExternalProject_Add. This can be used to set up (install) glad per project. And while find_package is not strictly required to do so, it would still be beneficial to pull in configuration variables through that method instead of setting them up manually.
