### ISSUE TITLE
Add OpenXR support to loader

### ISSUE THREAD

**Issue by rabbit-ecl** [Dav1dde/glad#233]
OpenXR reached 1.0 about a month ago. Are there any plans to support it?

**Comment by Dav1dde** [comment]
Sure, should be possible with the XML spec here: https://github.com/KhronosGroup/OpenXR-Docs/blob/master/specification/registry/xr.xml

**Comment by Dav1dde** [comment]
I currently don't have plans to add it, a plugin should have the access to all that's needed to add this separately
