### ISSUE TITLE
gladLoadVulkan returns 0 with -O3 and GCC

### ISSUE THREAD

**Issue by fluffrabbit** [Dav1dde/glad#235]
I've just begun to learn Vulkan, and I'm encountering strange behavior. It may be my code or it may be Glad. With `-O2` the test case runs without giving an error. With `-O3` it exhibits the behavior mentioned above.

[vktest.zip](https://github.com/Dav1dde/glad/files/3824815/vktest.zip)

**Comment by fluffrabbit** [comment]
@Dav1dde Not to bug you or anything, but it would be nice to know your thoughts, even general ones. I see you had no GitHub activity last month, and I can relate as there are periods when I don't use certain sites at all. Glad is peerless, so you're kinda the go-to guy for everything.

**Comment by Dav1dde** [comment]
@fluffrabbit I'll look into it, it's just been really busy recently. I'll get there.

**Comment by fluffrabbit** [comment]
[Possibly related.](https://github.com/BeRo1985/pasvulkan/issues/12) This thing I'm trying to rig is a workaround for a problem I didn't even know I was dealing with. I'm still fuzzy on how driver initializers and extension loaders interact; it's quite possibly not your fault.

**Comment by Dav1dde** [comment]
@fluffrabbit mh I don't see it, isn't that just an SDL issue?

**Comment by fluffrabbit** [comment]
That is just an SDL issue. I was thinking it might have something to do with SDL getting the handle pointer thing in the Glad call, but I'd assume SDL has been patched all the way back to Ubuntu 18.04 to fix any Vulkan issues it may have. So, don't listen to my idiotic suggestions. I think I need more rest. :D

**Comment by Dav1dde** [comment]
Do you have the same issue with: https://github.com/Dav1dde/glad/tree/glad2/example/c/vulkan_tri_glfw ?

**Comment by fluffrabbit** [comment]
It works! `gladLoaderLoadVulkan` works in my case where SDL's loader does not. I see why you had me test the GLFW version. Pretty triangles. So, anyone using SDL should probably use Glad's loader because it seems to work better. Should go in the wiki or something.

However, the issue I opened is about `gladLoadVulkan` (dependent on someone else's loader function) rather than `gladLoaderLoadVulkan`, and while I am happy with the solution, I wonder if you consider this resolved.

**Comment by Dav1dde** [comment]
@fluffrabbit Honestly I don't know if this is resolved. I only played around with it a little and couldn't reproduce it. Glad itself is so simple, literally just calling a function 15000 times and assigning the result, that I wonder if it's a glad problem. Then again if it's a SDL issue but I can workaround it in glad, I am happy to do so.

**Comment by fluffrabbit** [comment]
If you couldn't reproduce it, it has to be specific to my SDL, which must have since been fixed. Therefore, I am calling this resolved. There is still no mention of Vulkan on the wiki, but that's a separate issue and everything on Glad's side seems to work.
