### ISSUE TITLE
gladLoadGL() fail with osmesa

### ISSUE THREAD

**Issue by HeeJoong** [Dav1dde/glad#239]
Hi.
I'm trying to render 3D mesh object with osmesa on my ubuntu server (off-screen render).
I'm not sure if I'm doing correctly but I couldn't make GLAD to work with osmesa so far...
Here are my source code snippets
```cpp
// include libs
#include <glad/glad.h>
#include <GL/osmesa.h>

// OSMesa setup
OSMesaContext ctx;
ctx = OSMesaCreateContext (OSMESA_RGBA, NULL);
if (!ctx) {
  cout << "OSMesaCreateContext failed" << endl;
  return;
}
void * buffer;
buffer = malloc( SCR_WIDTH * SCR_HEIGHT * 4 * sizeof(GLubyte) );
if (!OSMesaMakeCurrent( ctx, buffer, GL_UNSIGNED_BYTE, SCR_WIDTH, SCR_HEIGHT )){
  cout << "OSMesaMakeCurrent failed" << endl;
  return ;
}

// glad setup
if(!gladLoadGL()) {
  cout << "glad loading failed" << endl;
  return ;
}
```
Am I missing something? if it's not a problem with glad, please help
I was also wondering if there is any working example of GLAD + OSMesa
Thank you in advance

**Comment by Dav1dde** [comment]
The glad internal loader only works for the most common desktop setups, not for offscreen rendering. You need to use `gladLoadGLLoader` and pass glad a function that knows how to load OpenGL functions.

Looking through the OSMesa headers, it looks like you can just pass `OSMesaGetProcAddress` to `gladLoadGLLoader`.

Or alternatively, maybe using [glfw](https://www.glfw.org/docs/latest/news.html#osmesa_33) is an option and then passing `glfwGetProcAddress` to `gladLoadGLLoader`.

**Comment by HeeJoong** [comment]
Thank you!
Now the program is running but it spits this error message when it's passing the section with shaders
I guess GLSL cannot work in non-desktop environment. I will try other ways, Thanks!!
```
ERROR::SHADER_COMPILATION_ERROR of type: VERTEX
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
 -- --------------------------------------------------- -- 
ERROR::SHADER_COMPILATION_ERROR of type: FRAGMENT
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES
 -- --------------------------------------------------- -- 
ERROR::PROGRAM_LINKING_ERROR of type: PROGRAM
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
 -- --------------------------------------------------- -- 
```

**Comment by fluffrabbit** [comment]
#version 300 es
