### ISSUE TITLE
DepthRangeArraydvNV and DepthRangeIndexeddNV not being defined

### ISSUE THREAD

**Issue by ReinUsesLisp** [Dav1dde/glad#242]
The interaction with `NV_depth_buffer_float` of `ARB_viewport_array` is not being defined in glad. These functions being `DepthRangeArraydvNV` and `DepthRangeIndexeddNV`.

The steps to reproduce are to generate from the [webservice](https://glad.dav1d.de/) an OpenGL 4.6 compatibility file with those two extensions explicitly enabled.

A generated example can be found [here](http://glad.dav1d.de/#profile=compatibility&api=gl%3D4.6&api=gles1%3Dnone&api=gles2%3Dnone&api=glsc2%3Dnone&extensions=GL_ARB_viewport_array&extensions=GL_NV_depth_buffer_float&language=c&specification=gl&loader=on).

The extension [specification](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_viewport_array.txt) defines these functions below `Interactions with NV_depth_buffer_float`.

**Comment by Dav1dde** [comment]
This seems like a bug in the specification, these functions are not defined in [gl.xml](https://raw.githubusercontent.com/KhronosGroup/OpenGL-Registry/master/xml/gl.xml).

You might want to open an issue here: https://github.com/KhronosGroup/OpenGL-Registry?

**Comment by ReinUsesLisp** [comment]
Sure, will do. Should I keep this open until it's fixed there? I'm fine closing it if it's not related to glad itself.

**Comment by Dav1dde** [comment]
Thanks, I'll close it for now, once Khronos adds the symbols and glad can't generate them (for some reason) please comment or make a new issue.
