### ISSUE TITLE
Vulkan 1.2

### ISSUE THREAD

**Issue by Zingam** [Dav1dde/glad#243]
https://www.khronos.org/news/press/khronos-group-releases-vulkan-1.2
Thanks for the tool! I just want to express my gratitude and also interested in the recently released Vulkan 1.2. Will it take a long time to include support for it in glad2?

**Comment by Dav1dde** [comment]
Done, should work now please report back if something is still broken

**Comment by Zingam** [comment]
That was quick! Thanx!
