### ISSUE TITLE
[Feature] CMake support

### ISSUE THREAD

**Issue by Zingam** [Dav1dde/glad#244]
A suggestion: the web service could generate a ready to consume CMakeLists.txt library project along with the loader code that can be then easily included in a CMake project as a module and used via the standard configuration methods.

**Comment by Dav1dde** [comment]
I don't think I want to add even more cmake. It makes sense for the whole project to help call the generator, the web generator already does that for you.

I feel this would just work better as an example or documentation if someone wants to add it.
