### ISSUE TITLE
Vulkan: vkEnumerateInstanceVersion support

### ISSUE THREAD

**Issue by Zingam** [Dav1dde/glad#246]
Glad could export a function to enumerate the Vulkan Loader support if we don't use the glad's loader part. Something like:

```
PFN_vkEnumerateInstanceVersion my_EnumerateInstanceVersion =
    (PFN_vkEnumerateInstanceVersion)vkGetInstanceProcAddr(
        VK_NULL_HANDLE, "vkEnumerateInstanceVersion");
if (nullptr != my_EnumerateInstanceVersion) {
    // Command is present and defined.
} else {
    // Command is not present, treat as Vulkan 1.0 only
}
```

**Comment by Dav1dde** [comment]
I dont quite follow, you mean a function which returns the currently available Vulkan version?

Is there a reason **not** to use the glad loading functions (which then would give you that version)?

**Comment by Zingam** [comment]
I think , one may need to test if the system supports a minimal Vulkan version before proceeding.

**Comment by Dav1dde** [comment]
But you can just call the loader, check what comes back and continue from there?

**Comment by Dav1dde** [comment]
@Zingam I'll close this for now, if you have anymore questions, feel free to comment
