### ISSUE TITLE
Remove the khrplatform.h header

### ISSUE THREAD

**Issue by bcmpinc** [Dav1dde/glad#25]
Nothing that is defined in the `khrplatform.h` header seems to be used. So, that header file does not need to be included when you remove the following line from the glad.h output:

    #include <KHR/khrplatform.h>

**Comment by Dav1dde** [comment]
EGL uses datatypes of `khrplatform.h` also the "official" headers for GLES2 and GLES3 include it, glad tries to offer the same types and functions as the official headers to work as a drop in replacement for these and other solutions.

Is there a disadvantage to including `khrplatform.h` even if it might not be used by glad?
