### ISSUE TITLE
CMakeLists.txt in cmake subdirectory

### ISSUE THREAD

**Issue by ghuser404** [Dav1dde/glad#250]
In glad2 CMakeLists.txt is located in cmake subdirectory. I may be wrong, but all projects tend to put it in the root directory. Is there a good reason to do that?

**Comment by Dav1dde** [comment]
It's just to keep things more organized, all the cmake related files are in the cmake directory.

**Comment by ghuser404** [comment]
Usually additional cmake files, such WriteFile.cmake in glad2's example, are in cmake subdirectory, but CMakeLists.txt is always in the root.

**Comment by Dav1dde** [comment]
Sure, but is this an issue or just an inconvenience, so far it seems like it doesn't really matter where it is.

**Comment by ghuser404** [comment]
It's a slight inconvenience. It's a matter of writing `add_subdirectory(glad/cmake)` instead of `add_subdirectory(glad)`. Also, for a moment I got confused whether the library supports cmake, as there wasn't CMakeLists.txt in the usual place.

But as I said, it's only a slight inconvenience, it's up to you how to organise the library sources.

**Comment by Dav1dde** [comment]
Thanks I'll keep it in mind. For now I prefer cmake in it's own directory, if the need arises I'll move it.
