### ISSUE TITLE
Undefined reference to 'gladLoadGLLoader'

### ISSUE THREAD

**Issue by mlistemann** [Dav1dde/glad#251]
I have a pre-compiled GLFW3 shared library and want to use it with glad to build a really basic OpenGL dev environment. Basically, I'm following [this tutorial](https://learnopengl.com/Getting-started/Creating-a-window) on **Ubuntu 18.04**. The `glad.c` is located within my project tree whereas `glad.h` is located in a separate folder under my HOME directory together with the GLFW headers. My CMake file looks more or less like this:
``` cmake
cmake_minimum_required(VERSION 3.8)

project(opengl LANGUAGES CXX)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/CMake/Modules/")

find_package(GLFW3 3.3 REQUIRED)

set(EXT_SOURCE_DIR "${CMAKE_SOURCE_DIR}/external/src")

add_executable(${PROJECT_NAME} "${EXT_SOURCE_DIR}/glad.c" "${CMAKE_SOURCE_DIR}/src/main.cpp")

target_include_directories(${PROJECT_NAME} PUBLIC "${EXT_INCLUDE_DIR}/glad" "${EXT_INCLUDE_DIR}/KHR" ${GLFW3_INCLUDE_DIR})

target_link_libraries(${PROJECT_NAME} ${CMAKE_DL_LIBS} ${GLFW3_LIBRARY})
```
CMake builds this simple project whose 'main.cpp' basically contains [this code](https://learnopengl.com/code_viewer_gh.php?code=src/1.getting_started/1.1.hello_window/hello_window.cpp). However, `make` throws `main.cpp:(.text+0xee): undefined reference to 'gladLoadGLLoader'` as the first error. 
Actually, I don't really understand why something like `find_package(OpenGL)` is not needed in several glad examples, but even if I use this together with `${OPENGL_LIBRARIES}` in the `target_link_libraries` it throws the same error.

**Comment by Dav1dde** [comment]
Not really a CMake Wizard, I came up with this:

```cmake
cmake_minimum_required(VERSION 3.8)
project(opengl LANGUAGES C CXX)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/CMake/Modules/")

find_package(glfw3 REQUIRED)


set(EXT_SOURCE_DIR "${CMAKE_SOURCE_DIR}/external/src")
set(EXT_INCLUDE_DIR "${CMAKE_SOURCE_DIR}/external/include")
add_library(glad "${EXT_INCLUDE_DIR}/glad/glad.h" "${EXT_SOURCE_DIR}/glad.c")
target_include_directories(glad PUBLIC ${EXT_INCLUDE_DIR})


add_executable(${PROJECT_NAME} "${CMAKE_SOURCE_DIR}/src/main.cpp")


target_link_libraries(${PROJECT_NAME} PUBLIC glfw glad PRIVATE ${CMAKE_DL_LIBS})
```

Here the whole project/setup as a zip: [sample_glad_cmake.zip](https://github.com/Dav1dde/glad/files/4301486/sample_glad_cmake.zip)


On why `find_package(OpenGL)` isn' t needed: The problem with OpenGL is, it's different on basically every platform and computer, it depends on a lot of variables like the driver, driver version, windowing system ..., but not only that it also depends on runtime variables, e.g.:

```c
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 3);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 3);
    glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);
```

So this makes it pretty much impossible to statically link directly against OpenGL and means it must be dynamically loaded. That's what glad does, define and export OpenGL symbols you can statically link against but at runtime it takes care of loading all of the function pointers (through gladLoad*).

Furthermore glad is customizable, so you can select just the OpenGL features and extensions you want to target with your application, makes loading marginally faster, binaries marginally smaller and you get compiler errors when you try to use a function which is not in your targeted set of features and extensions.

**Comment by mlistemann** [comment]
Thank you @Dav1dde, you were pointing me at the right place. It was actually just due to the language definition in my CMakeLists. Instead of providing `project(opengl LANGUAGES CXX)` I'm better off leaving out the language definition at all. Thank you also for the detailed explanation on OpenGL linking.
