### ISSUE TITLE
glad2: `glad_add_library` EXTENSIONS parameter is handled incorrectly

### ISSUE THREAD

**Issue by Hopobcn** [Dav1dde/glad#252]
Hi, i was trying the `glad_add_library` present in branch `glad2` and then found an issue with the `EXTENSIONS` parameter.
Here:
https://github.com/Dav1dde/glad/blob/bba732efa30523b51527de66d6bbe8e9b66413b7/cmake/CMakeLists.txt#L200
There's is a problem with the `if` condition because if `NONE` is not found, then it's erasing all `GG_EXTENSIONS` contents instead of just forwarding the parameters to the python generator.

**Comment by Dav1dde** [comment]
Should be fixed, thanks!
