### ISSUE TITLE
glad2 Rust Multicontext

### ISSUE THREAD

**Issue by solarane** [Dav1dde/glad#254]
As far as I can see, multicontext is implemented and working for C/C++ in glad2; something similar should be possible for Rust as well. (see: [`gl_generator` "Struct Generator"](https://github.com/brendanzab/gl-rs/tree/master/gl_generator))

I am unfamiliar with glad's internals, but this like it would be pretty trivial to implement—at first glance. If no immediate work is being done/is planned, I *might* be able to eventually take a go myself; nevertheless, opening this issue because I feel like this is something that should be implemented eventually.

**Comment by Dav1dde** [comment]
yeah this should be relatively straight forward, I'd have to look into how to properly generate the struct, just wrapping everything that is generated into a struct might not be enough.

With the current infrastructure this should only be a change in the [rust template](https://github.com/Dav1dde/glad/blob/glad2/glad/generator/rust/templates/impl.rs) with minimal infrastructure in the generator (mainly just to add the option to the config).

If you want to work on it, feel free to reach me on Freenode, you can find me in the Rust, OpenGL and glad channels there.

I won't be able to do this in the next week(s) probably, but this would be a feature I don't mind supporting and maintaining (and adding at some point).

**Comment by Dav1dde** [comment]
Supported with 91c7599
