### ISSUE TITLE
Is it possible to use GL ES 3.1 loader on desktop?

### ISSUE THREAD

**Issue by NukeBird** [Dav1dde/glad#262]
I'm writing applications for Android and iOS, but I prefer to develop things on Windows and only after that port and test it on mobile devices

I know it's not possible to have ES context on desktop, but... Functions are pretty much the same as they were from dektop GL, differs only extension names (ARB instead of OES?)

**Comment by fluffrabbit** [comment]
It is possible to run ES contexts on desktop, but it mainly depends on what your OS supports. AFAIK ES 2.0 works everywhere, even on Windows.

There is a lot of overlap between regular and ES contexts, usually without having to use EXT/ARB suffixes. ES 2.0 is based on GL 2.0 but without the fixed-function pipeline and with framebuffers as part of the core. ES 3.0 is based on GL 3.3 Core Profile. I haven't used ES 3.1 so I can't speak for that, but ES 3.0 works great on Ubuntu, since it's basically just using a modified GL 3.3 driver.

**Comment by Dav1dde** [comment]
For using GLES on Desktop, you might be able to make it work with [ANGLE](https://chromium.googlesource.com/angle/angle/+/master/README.md).

Otherwise as noted by fluffrabbit, GL ES shares quite a few symbols and functionallity with GL, glad allows you to generate GL and GLES at the same time and you can at runtime decide which one to use, obviously the rest of your app needs to support this as well (it's more than just calling the correct loader).

**Comment by fluffrabbit** [comment]
Isn't there something in the OpenGL spec about OpenGL 4.1+ implementations being required to support various GLES contexts? ANGLE strikes me as an implementation-dependent driver that fills a similar role to Mesa in YMMV cases as opposed to standards.

**Comment by NukeBird** [comment]
Thank you for quick response! 

> There is a lot of overlap between regular and ES contexts, usually without having to use EXT/ARB suffixes. ES 2.0 is based on GL 2.0 but without the fixed-function pipeline and with framebuffers as part of the core. ES 3.0 is based on GL 3.3 Core Profile. I haven't used ES 3.1 so I can't speak for that, but ES 3.0 works great on Ubuntu, since it's basically just using a modified GL 3.3 driver.

as you said, I can see a lot of common parts too, even wiki says that ES 3.0 is basically GL 3.3 but without shaders... But what about ES 3.1 and 3.2 - no one knows? 
I mostly interested in ES 3.1 + some optional features from ES 3.2 which I can test via OES and ARB extensions

> at the same time and you can at runtime decide which one to use

you mean test current platform and include different headers via ifdef? I'm a bit confused by "at runtime". Or you meant its possible to generate both ES and GL functions at same file? :o 

Mostly I wanted to use GLAD as a protector for myself, I just don't wanna see functions which aren't available on android phones 

If it can help, I'm using conan as my package manager. Here's options accessible for me: 
```python
options = {
        "shared": [True, False],
        "fPIC": [True, False],
        "no_loader": [True, False],
        "spec": ["gl", "egl", "glx", "wgl"], # Name of the spec
        "extensions": "ANY", # Path to extensions file or comma separated list of extensions, if missing all extensions are included
        # if specification is gl
        "gl_profile": ["compatibility", "core"],
        "gl_version": ["None", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5", "2.0",
                       "2.1", "3.0", "3.1", "3.2", "3.3", "4.0", "4.1", "4.2",
                       "4.3", "4.4", "4.5", "4.6"],
        "gles1_version": ["None", "1.0"],
        "gles2_version": ["None", "2.0", "3.0", "3.1", "3.2"],
        "glsc2_version": ["None", "2.0"],
        # if specification is egl
        "egl_version": ["None", "1.0", "1.1", "1.2", "1.3", "1.4", "1.5"],
        # if specification is glx
        "glx_version": ["None", "1.0", "1.1", "1.2", "1.3", "1.4"],
        # if specification is wgl
        "wgl_version": ["None", "1.0"]
    }
```

defaults are:
```python
    default_options = {
        "shared": False,
        "fPIC": True,
        "no_loader": False,
        "spec": "gl",
        "extensions": "''",
        "gl_profile": "compatibility",
        "gl_version": "3.3",
        "gles1_version": "None",
        "gles2_version": "None",
        "glsc2_version": "None",
        "egl_version": "None",
        "glx_version": "None",
        "wgl_version": "None"
    }
```

what will happen if I will set both "gl_version": "3.3" and "gles2_version":  "3.2"?

Also I'm curious  about extensions. Can I check OES ones? My phone (Redmi Note 4 (Helio x20)) has some OES without ARB alternatives

**Comment by Dav1dde** [comment]
> you mean test current platform and include different headers via ifdef? I'm a bit confused by "at runtime". Or you meant its possible to generate both ES and GL functions at same file? :o

Yes. glad2 has an explicit "merge" option for it, glad (as on master branch and glad.dav1d.de) just does it if you select GL and GLES.

> you mean test current platform and include different headers via ifdef? I'm a bit confused by "at runtime".
Compile-Time works as well. `#ifdef` or `if (...)`

> what will happen if I will set both "gl_version": "3.3" and "gles2_version": "3.2"?
You'll get a glad which includes all symbols of OpenGL 3.3 and all symbols of GLES2, symbols with the same name only exist once.

> Also I'm curious about extensions. Can I check OES ones? My phone (Redmi Note 4 (Helio x20)) has some OES without ARB alternatives
You can checkt whatever you want, but prepared that they are not available at runtime (you can check for support with the GLAD_ booleans after loading glad)

**Comment by NukeBird** [comment]
oh, sweet! it makes a lot of sense now! 

I will just set ES 3.0 and desktop GL 3.3 and dd some extra features from ES 3.1 and 3.2 on top if needed (when checking availability I'll test both ARB and OES) 

Thank you a lot! Now I understand more how GLAD works and I love it!

**Comment by NukeBird** [comment]
before closing this issue, is here any glad-related things I should know? maybe possible bugs in this windows + android approach?

**Comment by Dav1dde** [comment]
Glad has no bugs ;)

On a serious note, you should not use the builtin loader, you should do it properly and use the correct function from your context-creation library, like `glfwGetProcAddress`. Glads approach may work, but you shouldn't rely on it, especially for ES. I improved this a lot in the `glad2` branch, but still you should use the function provided by your context-creation library.

**Comment by fluffrabbit** [comment]
Same experience here with glad2. Use SDL or whatever you're using to load the library, passing Glad the function pointer. It works better.

All bets are off when using Glad for Vulkan though; there seem to be a couple minor unresolved library compatibility issues that I had to work around last time I tried it.

**Comment by NukeBird** [comment]
> Glad has no bugs ;)
Glad - no, but me - yes! :D

Thank you guys once again! Will try SDL_GL_GetProcAddress

**Comment by Dav1dde** [comment]
@fluffrabbit hijacking this, what were your Vulkan Issues, they should have been resolved, at least there are none on my todo right now.

**Comment by fluffrabbit** [comment]
@Dav1dde Sorry, it's been so long that I don't know if the problems I'm seeing are real or imagined. No functional difference between a glad2 Vulkan header generated now and one from November 2019. If it works for you, that's good enough for me.
