### ISSUE TITLE
Missing --alias option

### ISSUE THREAD

**Issue by Akaricchi** [Dav1dde/glad#264]
The glad.sh service includes an "alias" option, which seems very useful, but is missing from the `glad2` branch. Is the service running a yet unpublished version?

**Comment by Dav1dde** [comment]
The option is there, it's just a generator option not a global one, here are all the C generator options: https://github.com/Dav1dde/glad/blob/glad2/glad/generator/c/__init__.py#L203

`python -m glad --api='gl:core=' c --alias`

`c` is the generator, everything after is considered a generator option, you can also query them through `python -m glad c --help`.

**Comment by Akaricchi** [comment]
Ah, that makes sense, thanks. However, it would be nice to mention the existence of `glad {generator} --help` in the top-level `--help` output, to avoid confusion.
