### ISSUE TITLE
Rust MX Context Object Cannot Be Sent Across Threads

### ISSUE THREAD

**Issue by solarane** [Dav1dde/glad#265]
## Summary
As far as I'm aware, GL contexts in MX should be transferrable across threads, so that multithreaded & multi-context GL is achievable in a cross-platform manner.

Currently in the glad2 Rust generator, function pointers are stored as `*const std::ffi::c_void`. The problem is, raw pointers are not `Sync`, which means `FnPtr` (and thus `Gl` in MX) cannot be sent across threads. Although this isn't a critical issue, it's definitely something that should be supported.

## Possible Fix
References are guaranteed to have the same memory layout as their raw pointer alternatives, and *are* `Sync`. So AFAICT, the issue would be no more were all instances of `*const std::ffi::c_void` replaced with `&std::ffi::c_void`.

I'll hopefully get around to submitting a fix PR very soon. Until then, here's a tracking issue. (cc: @Dav1dde)

**Comment by Dav1dde** [comment]
I don't think going with references is the way here, that would mean the (GL) struct has to have a lifetime, which is wrong.

It seems like [`AtomicPtr`](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicPtr.html) is what it should be

**Comment by Dav1dde** [comment]
Simply implementing `Send` and `Sync` should work maybe too

**Comment by Dav1dde** [comment]
@solarane I implemented `Send` and `Sync` for `FnPtr` manually in fba0119, this should fix your issues.

**Comment by solarane** [comment]
Cool! Thanks :)
