### ISSUE TITLE
What is the relationship between this glad and https://github.com/arrayfire/glad ?

### ISSUE THREAD

**Issue by jiapei100** [Dav1dde/glad#269]
A naive question:

What is the relationship between this [**glad**](https://github.com/Dav1dde/glad) and [https://github.com/arrayfire/glad](https://github.com/arrayfire/glad) ?

**Comment by teburt** [comment]
https://github.com/Dav1dde/glad contains a script to generate code. There is also a web service which wraps this script.

It looks like https://github.com/arrayfire/glad contains the result of running the web service to generate code.

**Comment by Dav1dde** [comment]
As teburt said, this repository contains the code to generate a loader and the linked repository looks like the result of running the code from this repository, which is what you would need for your OpenGL application.

You can generate the code using the web generator at https://glad.dav1d.de or checking out this repository and running glad via commandline `python -m glad`.
