### ISSUE TITLE
Web generator for GL-ES is missing GLAPI int gladLoadGL(void);

### ISSUE THREAD

**Issue by AlessandroBorges** [Dav1dde/glad#28]
Hi,
I'd like to report that web generator for GL-ES doesn't generate the function 

 GLAPI int gladLoadGL(void);

in glad.c .
Regards,
Alessandro

**Comment by Dav1dde** [comment]
`gladLoadGL` is only a convenience function for OpenGL contexts, GLES contexts do not have this function, either use the loading function provided by your context creation library (e.g. `glfwGetProcAddress`) or `eglGetProcAddress`.

**Comment by Dav1dde** [comment]
I think I know what you mean, the function exists in the header but not the source file. Good catch!
