### ISSUE TITLE
Per-Device Function Loading Vulkan

### ISSUE THREAD

**Issue by nickclark2016** [Dav1dde/glad#280]
Vulkan supports loading functions per-device function loading, but it appears that the generated headers only support loading for one device at a time.  Would it be possible to add function lookup tables at a per-device level?

**Potential Solution:** `gladLoaderLoadVulkan` returns a pointer to a function table, as well as setting the global function pointers.  This allows the current usage of the code to continue to work, while allowing a path forward for multi-gpu solutions.

**Comment by Dav1dde** [comment]
Did you try the MX option? It generates all function pointers into a struct.

**Comment by nickclark2016** [comment]
I didn't see that flag. That will do what I'm looking for. Thanks!
