### ISSUE TITLE
Including `Windows.h` after `glad.h` raises "macro redefinition" warning

### ISSUE THREAD

**Issue by lethal-guitar** [Dav1dde/glad#283]
When compiling the following code snippet on Windows:

```cpp
#include <glad/glad.h>
#include <Windows.h>

int main() {}
```

I get the following warning:

```
[...]\minwindef.h(130,1): warning C4005: 'APIENTRY': macro redefinition (compiling source file [...])
[...]\include\glad/glad.h(32): message : see previous definition of 'APIENTRY' (compiling source file [...])
```

This is with glad 0.1.33, using the webservice: https://glad.dav1d.de/#profile=core&language=c&specification=gl&api=gl%3D3.0

I have enabled warnings as errors in my project, which means I need to undefine `APIENTRY` after including `glad.h` in order to have a successful build. Undefining the macro at the end of `glad.h` would prevent that problem.

**Comment by Dav1dde** [comment]
Include `windows.h` before glad.

**Comment by lethal-guitar** [comment]
@Dav1dde thanks for getting back to me. That would indeed work for this reduced example, but my actual code is more complicated than that. I don't directly include `Windows.h` myself, it's another third party library that does it. And the structure of my code is not such that it would make sense to always include that other library before including `glad`.

It seems there is already a `#undef APIENTRY` at the end of the loader code, but it's not present when not generating a loader.

**Comment by Dav1dde** [comment]
In order to undefine correctly, we need to take care if we defined it in the first place (can't undefine the `APIENTRY` from windows). I am not a fan of it, the glad2 branch does it properly and uses a custom define instead of `APIENTRY` alltogether.

Btw. the official `gl.h` has the exact same problem, but instead of defining just `APIENTRY` it includes `windows.h` (glad used to do that as well and that caused more issues than it was helpful).

I think an undefine, if we defined it, is an okay solution.

PRs and opinions as always welcome

**Comment by lethal-guitar** [comment]
Just made a PR, let me know what you think.

> Btw. the official gl.h has the exact same problem, but instead of defining just APIENTRY it includes windows.h (glad used to do that as well and that caused more issues than it was helpful).

Yeah I was quite happy to see that glad doesn't include `Windows.h` 🙂

**Comment by Dav1dde** [comment]
Since I dont know how to properly address this in glad1, you can try the `glad2` branch (`https://glad.sh`) which does not define `APIENTRY` at all anymore.

**Comment by Dav1dde** [comment]
I am closing this, since there doesnt seem to be an easy solution for it in glad1 and glad2 already provides a working alternative,
