### ISSUE TITLE
On demand should have a default loader

### ISSUE THREAD

**Issue by duzenko** [Dav1dde/glad#286]
Right now it seems the on-demand path crashes unless client calls `gladSetGLOnDemandLoader()`
I think it's a nuisance and should be handled by GLAD internally, like the regular path does (which has a default `get_proc` function)

**Comment by Dav1dde** [comment]
It does if you enable the internal loader.

**Comment by duzenko** [comment]
https://github.com/Dav1dde/glad/issues/279
> You have ON_DEMAND loading enabled, when on demand is enabled there is no gladLoad* function anymore and you have to set the loader via gladSetGLOnDemandLoader.

**Comment by Dav1dde** [comment]
You can just try it out, select the loader and the on_demand option:

Glad generates this code:
```c
static GLADapiproc glad_gl_internal_loader_get_proc(const char *name);
static GLADloadfunc glad_global_on_demand_gl_loader_func = glad_gl_internal_loader_get_proc;
```

Where `glad_global_on_demand_gl_loader_func` is the function used to load the symbols and would be overwritten by a user supplied function.

**Comment by Dav1dde** [comment]
To expand on this a little, if you previously used `gladLoad*` together with `glfwGetProcAddress`, you now have to set `glfwGetProcAddress` as the loader using `gladSetGLOnDemandLoader`. For the internal loader this is done automatically if it is exists, but can still be overwritten with `gladSetGLOnDemandLoader`.
