### ISSUE TITLE
[Question] multiple glad.g/c in static libraries

### ISSUE THREAD

**Issue by duzenko** [Dav1dde/glad#287]
I have a MSVC solution with one executable and two static libraries.
Each library has its own copy of glad: 1.1 and 2.0.
When I try to build the main executable it fails with a bunch of 
```
error LNK2005: _glad_XXX already defined in GLTest11.lib(glad.obj)
```
I have spent reasonable time on the Internet trying to work around this but all advice is usually limited to moving the duplicated symbols to a third static lib. 
My problem, however, is that I want to use different versions of GLAD so as to force limit each static lib to particular GL version. 
Is there any good fix for this?

**Comment by Dav1dde** [comment]
If you build both libraries and have the code in your hand you can search and replace for glad_ and replace it with something unique.

Something like:
```
sed -i -e 's/glad_/glad_asd_/g glad.h
```

**Comment by duzenko** [comment]
@Dav1dde 
Do you think I can use glad.c from 2.0 for both 1.1 and 2.0 versions of glad.h?

**Comment by Dav1dde** [comment]
@duzenko yes, glad 2.0 includes all symbols of 1.1
