### ISSUE TITLE
Compilation Problems

### ISSUE THREAD

**Issue by bluesushi** [Dav1dde/glad#288]
Using a generated glad.c file from the web service for opengl 3.3 doesn't compile and gives me errors like so:
`glad.c:280:1: error: unknown type name ‘PFNGLBINDFRAGDATALOCATIONINDEXEDPROC’; did you mean` `‘PFNGLBINDFRAGDATALOCATIONPROC’?`
  `280 | PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glad_glBindFragDataLocationIndexed = NULL;`
     ` | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~`
     ` | PFNGLBINDFRAGDATALOCATIONPROC`
`glad.c:280:75: warning: initialization of ‘int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]`
  `280 | PFNGLBINDFRAGDATALOCATIONINDEXEDPROC glad_glBindFragDataLocationIndexed = NULL;`
      `|                                                                           ^~~~`
`glad.c:283:1: error: unknown type name ‘PFNGLBINDSAMPLERPROC’; did you mean ‘PFNGLBINDBUFFERPROC’?`
  `283 | PFNGLBINDSAMPLERPROC glad_glBindSampler = NULL;`
      `| ^~~~~~~~~~~~~~~~~~~~`
      `| PFNGLBINDBUFFERPROC`
`glad.c:283:43: warning: initialization of ‘int’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]`
  `283 | PFNGLBINDSAMPLERPROC glad_glBindSampler = NULL;`
      `|                                           ^~~~`
`glad.c:307:1: error: unknown type name ‘PFNGLCOLORP3UIPROC’; did you mean ‘PFNGLCOLORMASKIPROC’?`
  `307 | PFNGLCOLORP3UIPROC glad_glColorP3ui = NULL;`
      `| ^~~~~~~~~~~~~~~~~~`
      `| PFNGLCOLORMASKIPROC`
If I choose versions 3.2 and below it compiles fine. My computer has a "VGA compatible controller: Intel Corporation UHD Graphics 620 (rev 07)" and a "3D controller: NVIDIA Corporation GM108M [GeForce 940MX] (rev a2)"
According to [this](https://www.intel.com/content/www/us/en/support/products/126789/graphics/graphics-for-8th-generation-intel-processors/intel-uhd-graphics-620.html) I should have support for opengl up to 4.5 so why am I getting these errors for 3.3 and up? Sorry I'm a complete beginner and I'm on linux

**Comment by Dav1dde** [comment]
Compiles fine for me. Please attach your glad files as a zip and show your compilation command.

This works fine with multiple versions:
```
$ g++ example/c++/hellowindow2.cpp /tmp/src/glad.c -I/tmp/include -ldl -lglfw
```

**Comment by bluesushi** [comment]
Thanks to your compiler flags I figured out the problem. I wasn't specifying the include directory with -I which was causing all those errors. I had thought before that replacing <glad/glad.h> with "glad/glad.h" would work but it had to be "../include/glad/glad.h". I never recognized it because the tutorials I was looking at were showing only windows setup in detail, and since it was compiling for files generated for opengl 3.2 and down it confused me more. Thanks
