### ISSUE TITLE
Multi-threading

### ISSUE THREAD

**Issue by zajo** [Dav1dde/glad#292]
I understand that on some platforms the function pointers are context-specific, however it should be possible to initialize one context per thread and then run independent renderers in each thread.

If I understand correctly, glad doesn't support this use case. However, I think it would be easy to support if the global function pointers, as well as any other static object in glad, is converted to use `thread_local` (C++11). This should be a straight-forward change if there is a macro that glad defines, which can then be used to inject `thread_local` in each definition.

Would that be possible?

**Comment by Dav1dde** [comment]
This discussion has started in https://github.com/Dav1dde/glad/issues/259 before. I looked into having glad deal with the thread locals, but this doesn't seem to be possible across platforms and compilers.

Please add your ideas to the linked issue on how glad should provide support for this.

Also [glad2](https://glad.sh) can be used concurrently with the multi context option (function pointers arent generated globally but in a struct).

**Comment by Akaricchi** [comment]
FWIW `thread_local` is also C11.
