### ISSUE TITLE
[glad2] Possible memory leak in glad_vk_get_extensions()

### ISSUE THREAD

**Issue by gk7huki** [Dav1dde/glad#293]
In `glad_vk_get_extensions()`, there is an early return where `ext_properties` doesn't get freed.

In this part (`glad/generator/c/templates/vk.c`):
```
    if (physical_device != NULL) {
        result = {{ 'vkEnumerateDeviceExtensionProperties'|ctx }}(physical_device, NULL, &device_extension_count, ext_properties);
        if (result != VK_SUCCESS) {
            for (i = 0; i < instance_extension_count; ++i) {
                free((void*) extensions[i]);
            }
            free(extensions);
            return 0;
        }
```
There must be a `free((void*) ext_properties);` before the return.

I noticed #209 mentioned a few other warnings, all in this function. I believe you should be checking for non-zero return value from those `malloc`s, and maybe for non-zero `instance_extension_count + device_extension_count`.

What do you think about using `goto` for clearer error handling in this function?

**Comment by Dav1dde** [comment]
Yeah this indeed looks like a memory leak + all the other things you noted.

Do you want to open a PR for these improvements?

**Comment by gk7huki** [comment]
There you go

**Comment by Dav1dde** [comment]
Fixed with the PR!
