### ISSUE TITLE
[Nim] Several consts are generated with the same name

### ISSUE THREAD

**Issue by RecruitMain707** [Dav1dde/glad#295]
This causes an error, for example:
```nim
const
  GL_FALSE* = 0
  ...
  GL_FALSE*: GLenum = GLenum(0)
```

A possible solution would be to add an E of Enum to this repeated definitions

**Comment by JulStrat** [comment]
May be https://github.com/Dav1dde/glad/issues/290 is related? Same behavior?

**Comment by Dav1dde** [comment]
@JulStrat exactly the same problem, I assume it was caused by an update to the specs.

**Comment by RecruitMain707** [comment]
@Dav1dde how often are this changes added to the web?

**Comment by Dav1dde** [comment]
@RecruitMain707 you mean changes to the repository? This should already be up to date and live.

The offifical specs are pulled in every 24 hours and usually stuff does not break.
