### ISSUE TITLE
[Nim] `GL_TIMEOUT_IGNORED` is of type GLenum (uint32), but a value of -1 is assigned

### ISSUE THREAD

**Issue by RecruitMain707** [Dav1dde/glad#296]
This causes an error at compile time:
`Error: -1
 can't be converted to GLenum`

Possible solution would be to use a dirty/unsafe cast:
` GL_TIMEOUT_IGNOREDE*: GLenum = cast[GLenum](0xFFFFFFFFFFFFFFFF)`

note that i added an E to the end of the name because of an error i explained on the other issue

**Comment by Dav1dde** [comment]
This should be fixed now with the fix in #295, the constant already had a special handling it just got generated twice (see #295) and once without the special handling.

**Comment by Dav1dde** [comment]
Feel free to comment or open a new issue if you have other problems or the issue still persists.

**Comment by RecruitMain707** [comment]
ok thanks, awesome job
