### ISSUE TITLE
glad with EGL on Github workflows

### ISSUE THREAD

**Issue by BlGene** [Dav1dde/glad#297]
Hi,
This is more of a specific usage question than a issue with glad specifically.

I would like to create a glad EGL context within a github workflow virtual machine.
Somehow this is not working for me, please see:
1. https://github.com/BlGene/egl_check
2. https://github.com/BlGene/egl_check/runs/1082663509

It fails right at the beginning: `int egl_version = gladLoaderLoadEGL(NULL);`

I have the feeling that this should work in theory, e.g. using mesa, but I'm not sure about this.
I don't want to do any real rendering, just to see if my programs can load correctly.

In case you have any tips on how to get this to work, please let me know.

**Comment by BlGene** [comment]
On further inquiry, it looks like this could be mangled in virtual machines.
See: https://github.com/travis-ci/travis-ci/issues/5645

**Comment by Dav1dde** [comment]
Glad only fails if there is either:

1. No EGL library (libEGL.so.1, libEGL.so)
2. No default display `eglGetCurrentDisplay()`/`eglGetDisplay(EGL_DEFAULT_DISPLAY)`

I dont know in what environment the action is running/on what system, a default ubuntu image for actions would not have graphics drivers.

You can add a few `printfs` in glad to see where it aborts, I assume egl is simply missing.

I have working docker container that sets up a virtual X server using `xvfb-run` and it can load GL/GLX/EGL/Vulkan etc.

**Comment by BlGene** [comment]
@Dav1dde 

Thank you for the quick reply. For some reason I expected the mesa OpenGL to be installed by default, I've gotten it to work now.

P.S. here is the github workflow file in case you are interested: 
https://github.com/BlGene/egl_check/blob/master/.github/workflows/c-cpp.yml

Best,

**Comment by lixinyao11** [comment]
> Glad only fails if there is either:
> 
> 1. No EGL library (libEGL.so.1, libEGL.so)
> 2. No default display `eglGetCurrentDisplay()`/`eglGetDisplay(EGL_DEFAULT_DISPLAY)`
> 
> I dont know in what environment the action is running/on what system, a default ubuntu image for actions would not have graphics drivers.
> 
> You can add a few `printfs` in glad to see where it aborts, I assume egl is simply missing.
> 
> I have working docker container that sets up a virtual X server using `xvfb-run` and it can load GL/GLX/EGL/Vulkan etc.

@Dav1dde hi, I think I'm facing the second situation No default display `eglGetCurrentDisplay()/eglGetDisplay(EGL_DEFAULT_DISPLAY)`, since an error is raised when `eglGetDisplay(EGL_DEFAULT_DISPLAY)`. But how should I fix this problem? I have to run in headless mode so DISPLAY is unset, what should i do to fix the getDisplay problem? Thank you!
