### ISSUE TITLE
Web Generated glad.h uses wrong define to check GL-ES 2  api

### ISSUE THREAD

**Issue by AlessandroBorges** [Dav1dde/glad#30]
Hi !

The generated glad.h for GL-ES 2 uses the following check :
#ifdef __gl_h_
#error OpenGL header already included, remove this include, glad already provides it
#endif

But I guess it should be 
#ifdef __gl2_h_  // as stated at /GLES2/gl2.h
#error OpenGL ES header already included, remove this include, glad already provides it
#endif

Regards !

**Comment by Dav1dde** [comment]
That's a good point, thanks, I will look into fixing that if I have more time.
