### ISSUE TITLE
Functions loaded by GLAD trigger Data Execution Prevention on Windows

### ISSUE THREAD

**Issue by Fruitsalad** [Dav1dde/glad#301]
I recently bought a new Windows laptop that apparently has Data Execution Prevention on its most strict setting by default, and when running my program on that laptop it always throws a DEP exception on the first call to some function loaded by GLAD, crashing the program.

Now, I'm aware I can just turn DEP off, but because users are probably going to have DEP on its strictest setting too, I would prefer to be able to solve this properly. I also tried turning DEP off for the process with SetProcessDEPPolicy and the linker setting `/NXCOMPAT:NO`, but it seems Windows won't let you disable it when it's on its strictest setting.

So am I doing something wrong, or is GLAD maybe not meant to be compatible with DEP?

**Comment by Dav1dde** [comment]
I've never heard this before, can you narrow it down to what causes the problem exactly?

**Comment by Fruitsalad** [comment]
Data Execution Prevention is a Windows safety measure that prevents running code from memory pages that aren't marked with the executable bit. I'm not very familiar with how GLAD works, but I can only suppose that it loads OpenGL functions in such a way that something about it isn't marked as it should be. I don't know if that's the actual function text that's been loaded in or something with the function pointers, it doesn't really give many details with its exception besides letting you know that it's DEP that's killing your program.

Mind you that I'm not a DEP expert either, so I wouldn't actually know how to do it right. MSDN indicates that you can use VirtualProtect to mark memory as executable, not sure if that helps.

I'll see if I can give you more details about the device and the exceptions tomorrow, and I'll try some other OpenGL programs to see if it's not a driver program. It's kind of late right now.

**Comment by Dav1dde** [comment]
Which line of glad code triggers it? I have a suspicion, it is the loading of a 1.1 GL function.

**Comment by Fruitsalad** [comment]
GLAD code itself doesn't trigger it. Instead, the first time that I invoke a function that was loaded by GLAD it gets triggered. One time that was glGetString(GL_VERSION) and after I commented that out it was glClearColor...

Actually, since these are old OpenGL functions that supposedly don't need to be loaded, I'm starting to second guess whether it's GLAD's fault now, although GLAD is still the only suspect I have for this. I'll look at it some more tomorrow and report back with whatever I find.

**Comment by Dav1dde** [comment]
The old gl 1.1 functions may be loaded from opengl.dll instead of indirectly through `wglGetProcAddress`, it would be good if we can maybe track it down to that.

**Comment by Fruitsalad** [comment]
Turns out it was just dereferencing null pointers because I had called gladLoadWGL but not gladLoadGL so none of the function pointers were loaded yet, and that just happened to trigger DEP instead of a normal illegal access exception. I feel pretty silly now.
