### ISSUE TITLE
Dealing with Languages I cannot properly maintain in glad2

### ISSUE THREAD

**Issue by Dav1dde** [Dav1dde/glad#302]
I've been thinking on how I want to deal with language I cannot maintain myself properly (either because of not enough knowledge or simply time). I still want glad to provide multiple languages, but I also don't want to have multiple languages which I cannot properly maintain myself.

That's one of the reasons I made glad extendable with an extension system, which allows 3rd party packages to extend glad functionality by just being installed, the problem with this is I don't want to install packages on the website I do not own myself, simply because of the risk of someone pushing a bad update.

Any ideas how to deal with this are welcome.

**Comment by vladh** [comment]
Perhaps support for these additional languages could be structured as a module hosted in a different repository, with some straightforward and clearly documented mechanism for using glad and the language support repo together? At the very worst, something like `python -m glad --plugin-dir=../glad-mylang` is possible.

**Comment by Dav1dde** [comment]
There is already a plugin mechanism through [setup.py/setuptools](https://github.com/Dav1dde/glad/blob/glad2/setup.py#L39-L42). So stuff like this is already possible `pip install glad-mylang && python -m glad mylang`

For the online generator I would probably have to pin a specific git commit/hash and update on request (or check periodically myself).

**Comment by Dav1dde** [comment]
I decided now, I will accept languages through plugins for the web generator.
