### ISSUE TITLE
What does it mean when you specify two APIs?

### ISSUE THREAD

**Issue by tuket** [Dav1dde/glad#305]
This is what the documentation says:

```
  --api API             API type/version pairs, like "gl=3.2,gles=", no
                        version means latest
```

But I'm not sure what it means. Is it an intersection or union of APIs?

I'm making an app that supports GL3.3 and GLES3.0, and I was hoping that might help me adhere to the common set of features of both.

Cheers!

**Comment by tuket** [comment]
I've just tried generating one with GL+GLES and another with GL only. The GL+GLES one is bigger in KB. Am I right to assume it's the union of APIs? Could it be worth adding that info to the documentation?

**Comment by Dav1dde** [comment]
Sorry, I forgot about this then went on vacation.

Yes, selecting multiple APIs merges them, with glad2 this is more obvious (since separate files are generated and only merged with the explicit --merge function)
