### ISSUE TITLE
Is this Usable with Python itself

### ISSUE THREAD

**Issue by Woundrite** [Dav1dde/glad#309]
Hi I wanted to ask if I could use GLAD directly in python from this project and how could I do it?

**Comment by Dav1dde** [comment]
If you want to use glad to load OpenGL in python, this is currently not possible.

If you want to use glad as module, you can. I recommend using the glad2 branch which has a basic plugin system for specifications and custom generators: https://github.com/Dav1dde/glad/wiki/Extending-Glad

**Comment by Woundrite** [comment]
well that's a bummer... is there any plan of implementing it for python or will I have to do some workaround?

**Comment by Dav1dde** [comment]
No plans currently, most of the python windowing libraries bring OpenGL support already, like [pyglet](https://pyglet.readthedocs.io/en/latest/). [PyOpenGL](http://pyopengl.sourceforge.net/) could also be an alternative.
