### ISSUE TITLE
web generator : glad_egl.h miss definitions from egl.h

### ISSUE THREAD

**Issue by AlessandroBorges** [Dav1dde/glad#31]
Hi
glad_egl.h miss definitions for EGL 1.0 and forward.
i.e. unable to find things like  
#define EGL_NO_CONTEXT                    ((EGLContext)0)
#define EGL_NO_DISPLAY                    ((EGLDisplay)0)
#define EGL_NO_SURFACE                    ((EGLSurface)0)
#define EGL_PBUFFER_BIT                   0x0001

**Comment by Dav1dde** [comment]
Thanks! In fact a lot more definitions where missing, all of them should be there now.
