### ISSUE TITLE
how to build wgl from cmake

### ISSUE THREAD

**Issue by rymwf** [Dav1dde/glad#312]
I set GLAD_SPEC=wgl  and build project, but it only generated glad_wgl.h , glad_wgl.c and a glad.lib. However, the lib do not contain functions of wgl. 
Can it generate glad_wgl.lib or something similar?

**Comment by Dav1dde** [comment]
The cmake module is pretty limited in that regard and currently only works with GL.

The cmake module from glad2 shoudl work with wgl (example with egl, but also applies to wgl):
https://github.com/Dav1dde/glad/tree/glad2/example/c%2B%2B/multiwin_mx
