### ISSUE TITLE
Invalid source names generated when using CMake.

### ISSUE THREAD

**Issue by Aschratt** [Dav1dde/glad#314]
The current C/C++ generator [appends a suffix](https://github.com/Dav1dde/glad/blob/master/glad/lang/c/generator.py#L36), if the selected spec does not match "gl". This causes problems when the project is used with CMake, since the *CMakeLists.txt* does [only add *glad.c*](https://github.com/Dav1dde/glad/blob/master/CMakeLists.txt#L77) to the sources.

To be more precise on what I am trying to do: I want to update the portfile for vcpkg to make it use features to select the spec. Everything works fine, but the build fails when a different spec than "gl" is specified. This happens, because the build cannot find the proper *glad.c* file.

I suggest to either drop the suffix from the generator (or make it optional), or alternatively select the sources based on the selected specification. I think the second option would be a better solution, however, I do not know how it would interfer with PR #276. 

There's also issue #244, which I think addresses a similar (or the same?) issue. It is quite unspecific though, so I'm not quite sure.

A possible fix could look something like this:

```cmake
if("${GLAD_SPEC}" STREQUAL "gl")
  list(APPEND GLAD_SOURCES "${GLAD_OUT_DIR}/src/glad.c")
else()
  list(APPEND GLAD_SOURCES "${GLAD_OUT_DIR}/src/glad_${GLAD_SPEC}.c")
endif()

list(APPEND GLAD_SOURCES "${GLAD_INCLUDE_DIRS}/glad/glad.h")
```

I do not want to open a PR, since I may also be wrong, so please correct me, if I missed something. 🙂

**Comment by Dav1dde** [comment]
Fixed with #316
