### ISSUE TITLE
What configuration should I choose on GLAD generator/webservice?

### ISSUE THREAD

**Issue by FilipCZ** [Dav1dde/glad#318]
I'd like to use **GLAD** in my first **OpenGL/C++** project, but I'm not sure, which configuration should I choose on your generator/webservice. I'd like to create modern OpenGL app, based on modern OpenGL Core profile techniques, but I'd also like to keep some backwards compatibility with older GPUs and drivers (**I plan to keep compatibility from OpenGL 4.6 Core profile down to OpenGL 3.3 Core profile features and completely avoid the Legacy OpenGL**).

Which of these configurations should I set on your generator?
**A)** API (gl): Version 4.6, Profile: Core
**B)** API (gl): Version 4.6, Profile: Compatibility
**C)** API (gl): Version 3.3, Profile: Core
**D)** API (gl): Version 3.3, Profile: Compatibility

Is it worth to go for GLAD2 in my case or it doesn't really matter and original glad/glad.h is enough for me? I do not plan to use anything else than GL api this time.

Thank you very much for help.

**Comment by Dav1dde** [comment]
If you want to support OpenGL 3.3 you should go with that version, you also want to select core not legacy, core is more strict. Choose no extensions, except you already know you will need them.

If you later on realize you need more functionality, you have multiple options, either:

* increase your minimum required version and generate a new loader
* use the functionality through extensions and generate a new loader with these extensions

If you only generate the minimum set you want to support, you can't accidentally use functions from a different version!

Regarding glad1 or glad 2, if you're following a tutorial like (https://learnopengl.com/) you should use the version the tutorial uses (switching out glad is a 10 minute task later on).

If you're not using a tutorial, I recommend switching to glad 2, the [docs](https://github.com/Dav1dde/glad/wiki/C) are a bit better, the API is nicer, build integration is even easier (better cmake, header only support).
