### ISSUE TITLE
The "header only" option is invalid

### ISSUE THREAD

**Issue by Urada-source** [Dav1dde/glad#321]
Hello, I'm having some problems producing glad2 using the web server.  If I check the _header only_ option, I can't find gl functions (like glClearColor, all gl functions are missing, only some glad functions (like loader) and macros). I don't know what's going on.  I've done this seven or eight times with different options (such as checking mx and debug), but dealing with C/C ++ library dependencies is a pain in the ass, and I still want to use the Header Only library as much as possible. Thank you :)

**Comment by Dav1dde** [comment]
Have you defined `GLAD_GL_IMPLEMENTATION`?

See here: https://github.com/Dav1dde/glad/wiki/C#header-only

**Comment by Urada-source** [comment]
> 你定义好了`GLAD_GL_IMPLEMENTATION`吗？
> 
> 看到这里：[https](https://github.com/Dav1dde/glad/wiki/C#header-only) : [//github.com/Dav1dde/glad/wiki/C#header-only](https://github.com/Dav1dde/glad/wiki/C#header-only)

It's working, thank you! This is a rookie mistake.
