### ISSUE TITLE
Ambiguous callback symbols when using non-gl debug loaders.

### ISSUE THREAD

**Issue by crud89** [Dav1dde/glad#322]
Say I want to load GL and WGL extensions into my application. I do this with something like this:

```cxx
auto hRC = ::wglCreateContext(hDC);
	
::wglMakeCurrent(hDC, hRC);
::gladLoadGL();
::gladLoadWGL(hDC);
```

From my understanding, this requires both loaders, i.e. `glad.c` and `glad_wgl.c` to be generated. 

However, in debug-mode, both source files contain the same definitions for `_pre_call_callback_default`/`_post_call_callback_default` and `glad_set_pre_callback`/`glad_set_post_callback`, causing errors when linking the code. 

Am I missing something or using the code in a wrong way or is this a bug?

I noticed, that the [this line](https://github.com/Dav1dde/glad/blob/7ece538856bf124d798ab323c8e1e64ebb83cb50/glad/lang/c/debug.py#L71) already writes different implementations, so an easy fix (imo) would be to prefix the function names.

**Comment by Dav1dde** [comment]
Yeah this is a bug.

You might want to try glad2 if you need multiple generators/loaders ([example](https://github.com/Dav1dde/glad/blob/glad2/example/c/wgl.c)), it's a lot cleaner and built from ground up to support mulitple specifications at once.

**Comment by Aschratt** [comment]
Thanks for the confirmation! I will try to implement a fix and create a PR.

Regarding glad2 - I love it (especially the CMake integration), but our project uses vcpkg and there's still no port for it. I've already played around with it and would like to create one, but I want to wait for you to declare it stable. Until then, I am happy with keep using glad1 and push fixes to the vcpkg port, if necessary. 🙂
