### ISSUE TITLE
website redirects to wrong url

### ISSUE THREAD

**Issue by Frau2015** [Dav1dde/glad#323]
After pressing generate it redirects to the wrong url, if you change the url from http to https then it still works otherwise it redirects to a error not found page.

![Screenshot from 2021-05-02 23-45-17](https://user-images.githubusercontent.com/51972058/116822792-9225cd00-aba0-11eb-9fc0-63b78c6899f5.png)

**Comment by Dav1dde** [comment]
Thanks, should be working now.

Temporary fix that redirects from http to https, not sure what is going on. Migrated the hosting from my server to openshift und cloudflare, something seems to be broken..
