### ISSUE TITLE
Where is the documentation

### ISSUE THREAD

**Issue by GeorgeHu6** [Dav1dde/glad#328]
I can't find a documentation for glad2 to refer, some function is a little hard to understand

**Comment by Dav1dde** [comment]
Have you seen: https://github.com/Dav1dde/glad/tree/glad2#documentation, it links to the [wiki](https://github.com/Dav1dde/glad/wiki/C) here?

**Comment by GeorgeHu6** [comment]
> 
> 
> Have you seen: https://github.com/Dav1dde/glad/tree/glad2#documentation, it links to the [wiki](https://github.com/Dav1dde/glad/wiki/C) here?

All right, I got it! THANK YOU A LOT.
