### ISSUE TITLE
GLAD2: Is the "alias" option support "OES" extensions?

### ISSUE THREAD

**Issue by chirsz-ever** [Dav1dde/glad#334]
For example, if I want to use vertex array object in OpenGL ES 2.0, I could load the `GL_OES_vertex_array_object` and use functions like `glGenVertexArraysOES`. After reading the wiki, I think I could directly use `glGenVertexArrays` with the `alias` option, but I couldn't.

**Comment by Dav1dde** [comment]
Thanks for the report, should be fixed now!

**Comment by chirsz-ever** [comment]
Maybe not. When I execute:

```sh
glad --api="gles2=2.0" --out-path=$PWD --extensions=GL_OES_vertex_array_object c --alias
```

The generated code is still without the alias for `glGenVertexArrays`.

By the way, if I execute:

```sh
glad --api="gles2" --out-path=$PWD --extensions=GL_OES_vertex_array_object c --alias
```

The generated code will include 44 extensions, not only `GL_OES_vertex_array_object`. Is this the expected behavior?

**Comment by Dav1dde** [comment]
> ```
> glad --api="gles2=2.0" --out-path=$PWD --extensions=GL_OES_vertex_array_object c --alias
> ```
> The generated code is still without the alias for glGenVertexArrays.

`glGenVertexArrays` is not part of the 2.0 feature set (if you just generate `gles2=2.0` there is no `glGenVertexArrays`), so there is also no alias to set.

> ```
> glad --api="gles2" --out-path=$PWD --extensions=GL_OES_vertex_array_object c --alias
> ```
> The generated code will include 44 extensions, not only GL_OES_vertex_array_object. Is this the expected behavior?

Yes. Glad does not just add aliasing information for the selected extension you select, it automatically finds all extensions which have an alias to your selected feature set. So what you want to do is select the minimum feature set you need (in this case this would just be `gles2`) and glad finds all extensions which provide parts of this feature set, automatically adds them and creates the aliases for you.

**Comment by chirsz-ever** [comment]
So GLAD would generate aliases only if the function names are already included in the selected standard? This may need to  be explained in the wiki page.

**Comment by Dav1dde** [comment]
I am not sure how to handle this case, either if this is good behavior or not. `gles2=2.0 + GL_OES_vertex_array_object` would need to add `glGenVertexArrays` and at the same time resolved all other extensions that resolve to `glGenVertexArrays` (if there are any), but not pull in the higher feature set (`gles2=3.0`).

Also maybe glad pulling in all the other extensions automatically is not always the desired behavior. The initial intention was that the user selects the base version he wants supported (e.g. `3.0`) and glad pulls in the extensions that have features out of that feature set to provide backwards compatibility with earlier versions (e.g. `2.0`).
