### ISSUE TITLE
WIN32_KHR conditional missing on some extensions

### ISSUE THREAD

**Issue by muraj** [Dav1dde/glad#335]
The following generated loader doesn't have the #if USE_PLATFORM_WIN32_KHR around some of the win32 extension specific extensions and thus leads to compiler errors when the same header is used on non windows platforms.  Adding these conditionals manually, the issue goes away.

https://gen.glad.sh/#api=vulkan%3D1.1&extensions=VK_EXT_external_memory_dma_buf%2CVK_KHR_external_fence_capabilities%2CVK_KHR_external_memory%2CVK_KHR_external_memory_capabilities%2CVK_KHR_external_memory_fd%2CVK_KHR_external_memory_win32%2CVK_KHR_external_semaphore%2CVK_KHR_external_semaphore_capabilities%2CVK_KHR_external_semaphore_fd%2CVK_KHR_external_semaphore_win32%2CVK_KHR_get_physical_device_properties2%2CVK_KHR_timeline_semaphore&generator=c&options=DEBUG%2CHEADER_ONLY%2CLOA

**Comment by Dav1dde** [comment]
Should be fixed now, thanks!

**Comment by muraj** [comment]
Works! Thanks!
