### ISSUE TITLE
Feedback for the naming in Glad2

### ISSUE THREAD

**Issue by nitrix** [Dav1dde/glad#336]
Hello,

First of all, **thank you** for the amazing work on the Rust generator, it works incredibly well and I am very pleased with the integration and the surrounding tools (like the webservice).

I do, however, want to give a piece of feedback using it and maybe you can share your opinion with me on the matter.

I noticed all the constants kept their original `GL_` prefix but the functions didn't. `glClearColor()` for example became `ClearColor()` with the expectation that the user is going to write `gl::ClearColor()` and therefore import the module with `use glad_gl::gl`, but now you get ugly repetitions like `gl::GL_COLOR_BUFFER_BIT`, which is also unsatisfactory.

* **One solution** could be to remove the `GL_` prefix from the constants to make things more uniform everywhere.

* **A much better solution** is to bring back the `gl` prefixes for functions.

After a bit of thinkering, I realised what drawn me to Glad's API was the expectation that the generated bindings would be more truthful to the original C-like OpenGL API. In that sense, I personally ended up going with the second approach, adding a `gl` prefix to all the functions in my `gl.rs` file and then I import the module with `use glad_gl::gl::*;` so that everything becomes in the scope.

This leads to much more familiar C-like code in the Rust unsafe blocks. e.g. :

```
glClearColor(0.0, 0.0, 0.0, 1.0);
glClear(GL_COLOR_BUFFER_BIT);
```

It simplifies porting large amounts of existing engine code to Rust and has been working well for me.

What do you think?

**Comment by Dav1dde** [comment]
I agree, constants should lose their prefix as well.

Regarding the option to keep the prefixes, personally for me it was an upgrade to shift the prefix to the module name, but I can see where you're coming from, especially since glad avoids to make any abstractions over the functions.

I feel like it should be relatively easy to support both in the generator (prefix and no prefix), not sure if that makes sense and doesn't make it more confusing for people looking at examples using glad. 

PS: I am honestly surprised anyone is using it, glad2 is still very "hidden" and the Rust generator even more

**Comment by nitrix** [comment]
Losing the prefix on constants is fine too and having the option would be icing on the cake. :)

P.S.S. For some definition of "using". It's a side project and fairly aware it can break any time.

**Comment by Dav1dde** [comment]
I am not sure how to handle types, stripping the prefix is not quite as simple (used in signatures), it also may introduce conflicts with other rust types, which may just be confusing.

**Comment by nitrix** [comment]
Agreed. That's partly why I preferred the approach with the prefixes everywhere, but then the wildcard module import brings you a function named "load" in scope that isn't very descriptive either. I ended up renaming that too to the more familiar `gladLoadGL()` the C API had.

Pros and cons on both sides it seems. Also thank you for giving this a try, I see the commits :P

**Comment by Dav1dde** [comment]
That already works with glad, all types are in a types submodule, so you can star import them
