### ISSUE TITLE
Segmentation fault: 11 When running basic program

### ISSUE THREAD

**Issue by martinGITHUBER** [Dav1dde/glad#337]
Hi, so I made a basic program to open a new window with the title "Hello World", and it worked fine until I added GLAD. Here is my code:

```
#include <glad/glad.h>

#define GLFW_INCLUDE_NONE
#define GL_SILENCE_DEPRECATION
#include <GLFW/glfw3.h>

int main() {
	gladLoadGL();

	GLFWwindow* window;

	/* Initialize the library */
	if (!glfwInit()) return -1;

	/* Create a windowed mode window and its OpenGL context */
	window = glfwCreateWindow(640, 480, "Hello World", NULL, NULL);
	if (!window) {
		glfwTerminate();
		return -1;
	}

	/* Make the window's context current */
	glfwMakeContextCurrent(window);

	/* Loop until the user closes the window */
	while(!glfwWindowShouldClose(window)) {
        /* Render here */
		glClear(GL_COLOR_BUFFER_BIT);

		/* Swap front and back buffers */
		glfwSwapBuffers(window);

		/* Poll for and process events */
		glfwPollEvents();
	}

	glfwTerminate();
	return 0;
}
```

As soon as I added the GLAD include header, I got a segmentation fault 11

Yes I did some research, and people say I need to do `gladLoadGL();`, so I added that, and it still said segmentation fault. My compiler args are: `clang++ src/main.cpp -std=c++20 -O2 -Wall -Ilib/glad/include -Ilib/glfw/include -framework OpenGL -framework IOKit -framework CoreVideo -framework Cocoa`
Operating System: macOS Big Sur 11.5.2

**Comment by Dav1dde** [comment]
You need to initialize glad after creating and making your context current, compare with this example: https://github.com/Dav1dde/glad/blob/master/example/c%2B%2B/hellowindow2.cpp

**Comment by martinGITHUBER** [comment]
Oh ok thanks that worked 👍
