### ISSUE TITLE
glad does not work after compilation on release mode

### ISSUE THREAD

**Issue by gunpawder** [Dav1dde/glad#338]
I am trying to compile my app in Release mode but it does not work, it fails at the first opengl function. The same code, does not have a problem on Debug. I am missing something?

**Comment by Dav1dde** [comment]
Do you have a minimal example?

**Comment by gunpawder** [comment]
this also fails https://github.com/Dav1dde/glad/blob/master/example/c%2B%2B/hellowindow2.cpp in release mode

**Comment by Dav1dde** [comment]
I cannot reproduce this, works fine for me with `-O2` and `-O3`.

```
g++ example/c++/hellowindow2.cpp -Ibuild/include build/src/glad.c -lglfw -ldl -O3
```

You need to provide a better way to reproduce this, compiler, command line, glad build etc.
