### ISSUE TITLE
lld-link error:undefined symbol: eglGetCurrentContext  on windows 10 by vcpkg install glad

### ISSUE THREAD

**Issue by erickingxu** [Dav1dde/glad#339]
Hi @Dav1dde , 
Thanks for your good work first. I want to use glad to do some offscreen rendering works with EGL context ,gles functions.
When I use vcpkg install glad as default , and import glad lib and include files into my CMakelist.txt. And then build it in Clion, I get errors as above.  It seems glad can not contain some egl or some egl function symbol can not be exported ? ,So tell me how build a new glad library which contain EGL, Opengles2.0 ?
Thank you very much.

**Comment by Dav1dde** [comment]
You need to link against libEGL.

**Comment by erickingxu** [comment]
how to get libEGL.lib from glad , or your meaning is  download it from other library?

**Comment by Dav1dde** [comment]
It would come with your driver:
```
f%                                                                                                                                                                                                                                            lutetium :: ~ % ls -l /usr/lib/libEGL.*   
lrwxrwxrwx  11 root 25 Aug 10:53 /usr/lib/libEGL.so -> libEGL.so.1
lrwxrwxrwx  15 root 25 Aug 10:53 /usr/lib/libEGL.so.1 -> libEGL.so.1.1.0
.rwxr-xr-x 67k root 25 Aug 10:53 /usr/lib/libEGL.so.1.1.0
lutetium :: ~ % pacman -F libEGL.so.1                                                                                                                                                                     extra/libglvnd 1.3.2-1 [installed: 1.3.4-1]
    usr/lib/libEGL.so.1
multilib/lib32-libglvnd 1.3.2-1 [installed: 1.3.3-1]
    usr/lib32/libEGL.so.1
```

On Windows you probably need something like [ANGLE](https://chromium.googlesource.com/angle/angle)

**Comment by erickingxu** [comment]
@Dav1dde ,thanks very much.  ANGLE is ok.
