### ISSUE TITLE
generated documentation and link to online generator

### ISSUE THREAD

**Issue by seanmiddleditch** [Dav1dde/glad#34]
When needing a to add a new extension to glad, it is necessary to return to the generator. Unfortunately, this then requires reselecting all of the prior options manually, and (if you aren't keeping good documentation) trial-and-error to make sure you got all of the ones you need.

It would be extremely convenient if the generated source/header contained a comment that both (a) detailed clearly the specific options used in generation, (b) contained a command line that could be used to regenerate that exact source, and (c) contained a link to the online generator that would prefill all the corresponding options.

Of course, the online generator would need to support a way to set selected items via the URL itself for that last bit to actually be useful.

Something like this in the beginning of the generated `glad.h`:

    /* Generated OpenGL Loader
       by glad 0.1.8a on the 10th of Oct, 2015
         https://github.com/Dav1dde/glad
       License: ... what is the license of the generated output, anyway?
       Options:
         OpenGL 3.3 (Core)
         GL_ARB_sync
         GL_ARB_texture_barrier
         ...
       Command:
         glad --profile core --api gl=3.3 --generator c --spec gl --extensions GL_ARB_sync,GL_ARB_texture_barrier
       Online:
         http://glad.dav1d.de/?profile=core&api=gl%263.3&generator=c&extensions=GL_ARB_sync,GL_ARB_texture_barrier
    */

**Comment by Shimmen** [comment]
+1. Sounds like a great idea.

**Comment by Dav1dde** [comment]
It definitly is and it already was on my TODO, just no time at the moment, I will try to get it done by end of october.

**Comment by Dav1dde** [comment]
This works now, but the online generator only accepts so many exceptions since the URL doesn't provide enough space to list all extensions (browsers seem to limit URL lengths to ~2000 characters). There is still a small optimization to make (`extensions=a&extensions=b` -> `extensions=a,b`), which is on my TODO.

**Comment by seanmiddleditch** [comment]
One solution would be to just make the configuration documentation in the generated source easy to machine parse, and then allow a file upload field in the online generate that takes a generated source and prefills options from that.

**Comment by Dav1dde** [comment]
That's a good idea!
