### ISSUE TITLE
gladLoadGL is undefined

### ISSUE THREAD

**Issue by Kapilarny** [Dav1dde/glad#344]
I'm trying to use glad2 with CMake and MSVC but i ended up having an issue where my compiler says that gladLoadGL is undefined.

**Comment by Kapilarny** [comment]
Oh and im using C++17

**Comment by Dav1dde** [comment]
Does [this example](https://github.com/Dav1dde/glad/tree/glad2/example/c%2B%2B/multiwin_mx) work for you?

**Comment by Kapilarny** [comment]
it doesn't, for some reason my compiler compiles glad without GLAD_GL_IMPLEMENTATION

**Comment by Kapilarny** [comment]
Here is my CMakeFile if that helps
```cpp
cmake_minimum_required(VERSION 3.5)
project(nrdengine_cpp_engine VERSION 0.0.1 LANGUAGES C CXX)

set(CMAKE_CXX_STANDARD 17)

#add external libs
#find_package(OpenGL REQUIRED)

# install python and Jinja2
set(GLAD_SOURCES_DIR "${PROJECT_SOURCE_DIR}/external/glad")
add_subdirectory("${GLAD_SOURCES_DIR}/cmake" glad_cmake)

add_subdirectory(external/glfw)
add_subdirectory(external/glm)
add_subdirectory(external/assimp)

file(GLOB SOURCE_FILES "src/*.cpp", "src/*/*.cpp", "src/*/*/*.cpp", "src/*/*/*/*.cpp")

glad_add_library(glad_gl_core_mx_31 REPRODUCIBLE MX API gl:core=3.1)

add_library(nrdengine_cpp_engine ${SOURCE_FILES} ${INCLUDE_FILES})

target_include_directories(nrdengine_cpp_engine
    PUBLIC
        $<INSTALL_INTERFACE:include>
        $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/include>
        glm
    PRIVATE
        glfw
        assimp
)

target_link_libraries(${PROJECT_NAME}
    PUBLIC
        glm
    PRIVATE
        glad_gl_core_mx_31
        glfw
        assimp
)

**Comment by Dav1dde** [comment]
`GLAD_GL_IMPLEMENTATION` only exists in a header only build and [you have to define the macro in one file before including glad](https://github.com/Dav1dde/glad/wiki/C#header-only).

Your cmake file does not match what you said about `GLAD_GL_IMPLEMENTATION`.

**Comment by Kapilarny** [comment]
So, i need to use header build?

**Comment by Dav1dde** [comment]
No. But the situation you describe can only happen in a header only build, but the cmake file does not match that.

**Comment by Kapilarny** [comment]
Oh, ok im kinda dumb. So what i need to do to use it?

**Comment by Kapilarny** [comment]
What is the difference in header and api build btw?

**Comment by Dav1dde** [comment]
You don't need any options and probably want to use at least OpenGL 3.3 (remove the MX from your `glad_add_library`).

**Comment by Dav1dde** [comment]
> What is the difference in header and api build btw?

Header only does not generate a `.c` file only one `.h` file containing the entirety of glad, this makes it easier to just package with your own sources, since it is just one file. But this requires you to define `GLAD_GL_IMPLEMENTATION` in one [source file](https://github.com/Dav1dde/glad/wiki/C#header-only).

**Comment by Kapilarny** [comment]
Thanks for help @Dav1dde :D
