### ISSUE TITLE
Segfault when using GL calls across translation units

### ISSUE THREAD

**Issue by argentsileo** [Dav1dde/glad#345]
When using glad2 with GLFW, I am finding that, when using GL calls in any translation unit that is not the one containing main, it will immediately cause a segfault, even after glad had already been successfully initialized. glad will not even successfully initialize when `gladLoadGL` is called outside of the main translation unit. In all of those cases, the provided function pointers (and the pointer returned in the latter case) will all be null. Is this known behavior that must be worked around somehow, or have I set something up incorrectly?

OS: Arch Linux
Kernel: 5.15.6
NVIDIA Driver: 495.44
GLFW: 3.3.5

**Comment by Dav1dde** [comment]
Do you have a small/minimal example?

**Comment by argentsileo** [comment]
The relevant case is for GLFW event callbacks. I have the window resize callback implemented inside of a `window.h`/`window.cpp` pair. Basic recreation is as follows:

window.h
```cpp
#include <glad/gl.h>
#include <GLFW/glfw3.h>

struct Window
{
  GLFWwindow* nativeWindow;
  int width, height;

  void installMainCallbacks();
  static Window* createWindow(int _width, int _height, std::string title, bool fullscreen=false);
  static void freeWindow(Window* window);
};

static Window* gameWindow;

void windowSizeCallback(GLFWwindow* window, int width, int height);
```

window.cpp
```cpp
#include "window.h"

void Window::installMainCallbacks()
{
  if (nativeWindow != nullptr)
  {
    glfwSetWindowSizeCallback(nativeWindow, windowSizeCallback);
  }
}

Window* Window::createWindow(int _width, int _height, std::string title, bool fullscreen)
{
  glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 4);
  glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 6);
  glfwWindowHint(GLFW_OPENGL_PROFILE, GLFW_OPENGL_CORE_PROFILE);

  Window* res = new Window();
  GLFWmonitor* primaryMonitor = fullscreen ? glfwGetPrimaryMonitor() : nullptr;
  res->nativeWindow = glfwCreateWindow(width, height, title.c_str(), primaryMonitor, nullptr);
  if (res->nativeWindow == nullptr)
  {
    glfwTerminate();
    return nullptr;
  }
  res->width = width;
  res->height = height;
  glfwMakeContextCurrent(res->nativeWindow);

  return res;
}

void Window::freeWindow(Window* window)
{
  if (window)
  {
    glfwDestroyWindow(window->nativeWindow);
    delete window;
  }
}

void windowSizeCallback(GLFWwindow* window, int width, int height)
{
  gameWindow->width = width;
  gameWindow->height = height;

  glViewport(0, 0, width, height);
}
```

main.cpp
```cpp
#include <string>
#include "window.h"

int main()
{
  std::string title = "GLAD Test";
  
  gameWindow = Window::createWindow(640, 480, title);

  if (gameWindow == nullptr)
  {
    return -1;
  }
  gameWindow->installMainCallbacks();

  if (!gladLoadGL(glfwGetProcAddress))
  {
    return -1;
  }

  glViewport(0, 0, 640, 480);

  while (!glfwWindowShouldClose(gameWindow->nativeWindow)) 
  {
    glClearColor(0.0, 0.0, 0.0, 1.0f);
    glClear(GL_COLOR_BUFFER_BIT);

    glfwSwapBuffers(gameWindow->nativeWindow);
    glfwPollEvents();
  }

  Window::freeWindow(gameWindow);
  glfwTerminate();
  
  return 0;
}
```

**Comment by Dav1dde** [comment]
But this is all statically compiled into one binary and there is no multi-threading going on?

**Comment by argentsileo** [comment]
Yes, I'm not quite deep enough in the weeds just yet for that to be the cause of the issues

**Comment by Dav1dde** [comment]
Your example works for me if you add a missing `glfwInit()` at the top of main and uncomment `glfwPollEvents()`, not sure why poll events is segfaulting, I assume a faulty callback somewhere (but that doesnt seem to be your problem anyways?).

**Comment by Dav1dde** [comment]
Ah yeah `gameWindow->width = width;` in the callback, gameWindow is `null`, you're better off passing that in via a [glfw user pointer](https://www.glfw.org/docs/3.3/window_guide.html#window_userptr) instead of a global.

**Comment by argentsileo** [comment]
I didn't even know that was a feature of GLFW, I'm surprised I hadn't seen it before given how useful it is. I wonder what caused the issue with initializing glad outside the main translation unit then, as that was before I had used callbacks at all. Either way that fixed the issue I was having, thank you.

**Comment by Dav1dde** [comment]
Awesome!
