### ISSUE TITLE
GL_INTEL_performance_queries is missing.

### ISSUE THREAD

**Issue by StanleySweet** [Dav1dde/glad#346]
@0ad is currently[ trying to migrate](https://code.wildfiregames.com/D721) from custom made headers to glad2, thanks a lot for this opportunity. It seems however that Glad2 is missing an extension called `GL_INTEL_performance_queries` not to be confused with `GL_INTEL_performance_query` although adding the last one as an extension allows us to compile with no problem.

The only documentation that seems to exist about it seems to have been written by one of our former devs here: http://zaynar.co.uk/docs/gl-intel-performance-queries.html

Is it of any interest to you to add it?

**Comment by Dav1dde** [comment]
Glad get's its extensions from the original specification [here](https://github.com/KhronosGroup/OpenGL-Registry/blob/main/xml/gl.xml) and `GL_INTEL_performance_queries` seems to be missing in the spec!

You can open an issue in [KhronosGroup/OpenGL-Registry](https://github.com/KhronosGroup/OpenGL-Registry/issues), they are awesome people and usually quick to respond (e.g. I've done [that before](https://github.com/KhronosGroup/OpenGL-Registry/issues/94)).

Unfortunately there isn't really a workaround here I can recommend other than manually adding the definition until you get a response from the OpenGL team.

**Comment by StanleySweet** [comment]
Thanks for the fast reply! I opened the issue above.

**Comment by Dav1dde** [comment]
This seems to be resolved now (won't be added to the specs).

**Comment by StanleySweet** [comment]
Indeed. Thanks for your time :) On to the next milestone, detecting if we're running wayland or xorg to switch from glx to egl ;)
