### ISSUE TITLE
VK_KHR_dynamic_rendering is missing

### ISSUE THREAD

**Issue by skaarj1989** [Dav1dde/glad#347]
[VK_KHR_dynamic_rendering](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VK_KHR_dynamic_rendering.html) is missing (at least in **glad2** webservice)

**Comment by Dav1dde** [comment]
Thanks! It's there now:
![image](https://user-images.githubusercontent.com/255721/146980302-01b06a45-0949-4488-b66e-3aead560d3e1.png)

**Comment by skaarj1989** [comment]
> Thanks! It's there now

Today it disappeared.

![image](https://user-images.githubusercontent.com/34756939/147091101-0ec492a5-6f36-41a9-b2d7-b9b5dd9afddc.png)

**Comment by Dav1dde** [comment]
I am not sure what's going on, refreshing the files downloaded the correct files again. @skaarj1989 please try again.

**Comment by skaarj1989** [comment]
@Dav1dde It works now, but I am afraid that it might "expire" again, in the next 24h
