### ISSUE TITLE
[Vulkan] Missing enum values

### ISSUE THREAD

**Issue by skaarj1989** [Dav1dde/glad#350]
`glad` does not generate `VK_*_MAX_ENUM` for enumerated types.

https://github.com/KhronosGroup/Vulkan-Docs/issues/1722

**Comment by Dav1dde** [comment]
According to the spec:

>This special value exists only to ensure that C enum types are 32 bits in size. It is not part of the API, and should not be used by applications.

I am not sure if it makes sense to magically add that in, especially since it is not part of the spec. But I'll have to look into C enums, I assumed they are always 32bit, if it is required to force it to 32bit then there is a reason to add it.

**Comment by WSSDude420** [comment]
If those enums are used by some structures, MAX should probably be defined. But I dont think this is happening?

Because compilers may choose <32bit storage if values are not needing that much bytes which may be an issue.
But if they are ever used only as some constants, it should not matter.

**Comment by WSSDude420** [comment]
Taken from the [C Standard (C99)](http://www.open-std.org/JTC1/SC22/WG14/www/docs/n1256.pdf), same holds for newer ones though...
> 6.7.2.2 Enumeration specifiers
[...]
Constraints
The expression that defines the value of an enumeration constant shall be an integer constant expression that has a value representable as an int.
[...]
Each enumerated type shall be compatible with char, a signed integer type, or an unsigned integer type. The choice of type is implementation-defined, but shall be capable of representing the values of all the members of the enumeration.

**Comment by Dav1dde** [comment]
Thanks for this, glad should add these then.

**Comment by Dav1dde** [comment]
Glad generates the enums now.
