### ISSUE TITLE
Unable to generate Vulkan 1.3 with GLAD2

### ISSUE THREAD

**Issue by WSSDude420** [Dav1dde/glad#355]
Using GLAD2 as CMake project.

Adding its  `cmake` subdirectory and running command `glad_add_library(glad2_vulkan REPRODUCIBLE STATIC LOADER LANGUAGE C API vulkan=1.3)` fails with quite some hefty error message ending with `ValueError: Unknown version 1.3 for API vulkan (specification: vk)`.

Command `glad_add_library(glad2_vulkan REPRODUCIBLE STATIC LOADER LANGUAGE C API vulkan=1.2)` finishes without issues.

Looking at the web version hosted at https://gen.glad.sh/, it should be possible I believe in some way to use it or no?

**Comment by Dav1dde** [comment]
The `REPRODUCIBLE` option is using outdated files at the moment (comes with the advantage that your generated output doesn't randomly change).

I'll update the files when I get a few free minutes, until then you can just drop the reproducible for now.

**Comment by WSSDude420** [comment]
That seems to have fixed it for time being 👍 
Thank you for quick reply, will track progress of this 🙂

**Comment by Dav1dde** [comment]
@WSSDude420 you can update now, should work fine, the build failure is related to Rust, I fixed that for C already.

**Comment by WSSDude420** [comment]
Thank you, works now! ❤️ 
Also fixed warnings about MSVC-specific extensions being used which I was thinking about reporting later on so another good thing there 👍
