### ISSUE TITLE
c-debug output errors

### ISSUE THREAD

**Issue by zach2good** [Dav1dde/glad#36]
Hey, 
The library is great in normal C mode, but when I generate using the c-debug generator the output is unusable.

Inside glad.c the errors start at line 235:
APIENTRY PFNGLCOPYTEXIMAGE1DPROC glad_glCopyTexImage1D;
syntax error: identifier 'glad_glCopyTexImage1D'	

And there are about 100 or so. I've uploaded my output here:
https://github.com/zach2good/glad/tree/c-debug

But it appears to be the same as the debug output from your web generator. I've tried dropping the gl api level down and removing al lthe extensions but still no luck. Is there something I'm missing?

Cheers

**Comment by zach2good** [comment]
This is solved in this pull request:
https://github.com/Dav1dde/glad/pull/35

Thanks again for the excellent generator!

**Comment by MiniAl** [comment]
Glad I'm not crazy on this issue. Wasted like four hours thinking I was just insane.

**Comment by Dav1dde** [comment]
Thanks for the report and fix @MiniAl, this is fixed with 793e4f3f56851db954b3e656520165b6a2351ea7.
