### ISSUE TITLE
Adding SPDX headers to generated files

### ISSUE THREAD

**Issue by Tachi107** [Dav1dde/glad#365]
Hi, could you please consider adding [SPDX](https://spdx.org) headers to generated files? As you may (or may not) know, a growing number of large open source project is moving towards using this simple and machine-readable standard.

Adding the headers would help with clearing up doubts about the license of generated files, and also make life easier for projects aiming for [REUSE](https://reuse.software) compliance.

Thanks!

**Comment by Dav1dde** [comment]
The reason I haven't done this yet is because I actually don't know what the 100% correct license is, so I'd rather have no license listed than a wrong one, with a separate explanation in the readme.

**Comment by Tachi107** [comment]
What about applying a header that specifies something like

    SPDX-License-Identifier: (WTFPL OR CC0-1.0) AND Apache-2.0

except for Vulkan code, that has a specific exception for generated code? This _might_ result in a more restrictive license than needed, but Khronos not going after users who use code generated from Apache-2.0-licensed code is different from explicitly not having to license generated code under the Apache-2.0.

Being clear and expressing the worst possible case is better than hiding licensing information in my opinion, as applying more restrictive licensing terms is safer than letting users think that the code they're using is public domain.

**Comment by Dav1dde** [comment]
> Being clear and expressing the worst possible case is better than hiding licensing information in my opinion, as applying more restrictive licensing terms is safer than letting users think that the code they're using is public domain.

No license != public domain

**Comment by Tachi107** [comment]
> No license != public domain

Of course :)

I was referring to what is written in the readme (_"The glad generated code itself is any of Public Domain, WTFPL or CC0, the source files for the generated code are under various licenses from Khronos."_)

**Comment by Tachi107** [comment]
Thanks for the fix!
