### ISSUE TITLE
Glad generate a C file but is using C++ stl

### ISSUE THREAD

**Issue by ahmidou** [Dav1dde/glad#371]
https://github.com/ofiwg/libfabric/issues/7041#issuecomment-914839351

>We made this change very recently in https://github.com/microsoft/STL/pull/2148 which forbids including standard library headers from C programs.

I can't build glad anymore with VS 2022 17.1 and MSVC toolset 143

a simple fix would be to change the c extension to cpp

**Comment by Dav1dde** [comment]
Do you have the exact error, I don't think glad includes any C++ headers. Where does it come from? Changing the extension is not a fix.

**Comment by Dav1dde** [comment]
Duplicate #381
