### ISSUE TITLE
GLAD cmake command "ExternalProject_Add"

### ISSUE THREAD

**Issue by petrasvestartas** [Dav1dde/glad#376]
Hi,

How can I download GLAD using cmake function "ExternalProject_Add" for this specific configuration ?

I found some CMake code on the internet but it does not specify these options:

```cmake
# Download GLFW3 locally into the binary directory
if(DOWNLOAD_GLAD)
    message(STATUS "GLAD will be downloaded and built")
    # Download and build
    ExternalProject_Add(GLAD
        URL "https://github.com/Dav1dde/glad/archive/v0.1.29.zip"
        PREFIX ${GLAD_PREFIX}
        CMAKE_ARGS -DCMAKE_INSTALL_PREFIX=${GLAD_PREFIX} -DGLAD_INSTALL=${GLAD_INSTALL}
        UPDATE_COMMAND "")
endif(DOWNLOAD_GLAD)
```

![image](https://user-images.githubusercontent.com/18013985/183514318-9238372e-c76b-47d2-9062-bde0af6de9dd.png)

**Comment by drsnuggles8** [comment]
In case ExternalProject_Add doesn't work, you could try cmake's fetchcontent.
Make sure to put a `include(FetchContent)` somewhere before you insert the code below.
`FetchContent_Declare(
	glad
	GIT_REPOSITORY https://github.com/Dav1dde/glad.git
	GIT_TAG v0.1.36
	)
set(GLAD_PROFILE "core"	CACHE STRING "OpenGL profile")
set(GLAD_GENERATOR "c"	CACHE STRING "Language to generate the binding for")
FetchContent_MakeAvailable(glad)`

You can set more options, too, [here's an example](https://github.com/Hoshiningen/OpenGL-Template/blob/master/CMakeLists.txt).

**Comment by petrasvestartas** [comment]
Thank you, could you show how to download github repo and set these properties within external project command?

**Comment by petrasvestartas** [comment]
@drsnuggles8 

If I write this, weirdly only github repository is cloned without any glad.c , glad.h present.
Any idea why?

This is my code:

```cmake
  ExternalProject_Add(glad
  GIT_REPOSITORY https://github.com/Dav1dde/glad.git
	GIT_TAG v0.1.36
  CMAKE_ARGS
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}
    -DCMAKE_CXX_COMPILER=${CMAKE_CXX_COMPILER}
    -DGLAD_PROFILE="core"
    -DGLAD_GENERATOR="c"
  SOURCE_DIR   "${CMAKE_BINARY_DIR}/install/glad"
  CONFIGURE_COMMAND "" #do not configure
  BUILD_COMMAND "" #do not buld
  INSTALL_COMMAND "" #installer for now is empty
  )

```
