### ISSUE TITLE
Missing extensions in headers generated by GLAD2 webtool even tho "Add All" was used.

### ISSUE THREAD

**Issue by KitsuneAlex** [Dav1dde/glad#379]
I've been using GLAD2 to implement a backend for our graphics abstraction layer.
However, i noticed that a lot of ARB constants from the Core profile are missing.
To name an example, you seem to be missing **GL_ARB_gpu_shader_int64**.

**Comment by KitsuneAlex** [comment]
You also seem to be missing **GL_ARB_gpu_shader_int16** and **GL_ARB_gpu_shader_int8**, even tho some sources i found state that those were deprecated(?)

**Comment by Dav1dde** [comment]
What constants are missing? The ones defined in the spec are all there:

```xml
        <extension name="GL_ARB_gpu_shader_int64" supported="gl|glcore">
            <require>
                <enum name="GL_INT64_ARB"/>
                <enum name="GL_UNSIGNED_INT64_ARB"/>
                <enum name="GL_INT64_VEC2_ARB"/>
                <enum name="GL_INT64_VEC3_ARB"/>
                <enum name="GL_INT64_VEC4_ARB"/>
                <enum name="GL_UNSIGNED_INT64_VEC2_ARB"/>
                <enum name="GL_UNSIGNED_INT64_VEC3_ARB"/>
                <enum name="GL_UNSIGNED_INT64_VEC4_ARB"/>
                <command name="glUniform1i64ARB"/>
                <command name="glUniform2i64ARB"/>
                ... more commands
            </require>
        </extension>
```

If an extension is missing, then it is missing from the [spec](https://github.com/KhronosGroup/OpenGL-Registry/blob/main/xml/gl.xml), if you think this is a mistake you can open an issue at the [OpenGL-Registry](https://github.com/KhronosGroup/OpenGL-Registry).

**Comment by KitsuneAlex** [comment]
Something seems to be wrong with my generated GLAD headers then, because i can find none of the above constants in them.
![image](https://user-images.githubusercontent.com/12082168/190856530-b80f1e26-909a-48ab-b863-17ffcec486a1.png)
I generated GLAD2 for OpenGL 4.6 Core, so they should definitly be present..
Imma look a bit further into this and report back.

**Comment by KitsuneAlex** [comment]
Not a mistake in the registry either.. really weird.
![image](https://user-images.githubusercontent.com/12082168/190856789-cc538fcf-b0e7-4720-9df8-5f75dbaff414.png)

**Comment by Dav1dde** [comment]
@KitsuneAlex did you enable the extension when generating your headers? Why do you expect them to be part of the core?

**Comment by KitsuneAlex** [comment]
Yes, i enabled all extensions under the Core profile. I am developing a graphics abstraction, i want access to all the possible extensions. That's why this is odd to me.

**Comment by KitsuneAlex** [comment]
Select GL4.6 -> Select Core profile -> Select all extensions -> Generate loader -> Get headers is my course of actions here.

**Comment by Dav1dde** [comment]
Can you paste the comment in the beginning of the header file?:

```c
/**
 * Loader generated by glad 2.0.0-beta on Sat Sep 17 12:36:54 2022
 *
 * Generator: C/C++
 * Specification: gl
 * Extensions: 1
 *
 * APIs:
 *  - gl:core=4.6
 *
 * Options:
 *  - ALIAS = False
 *  - DEBUG = False
 *  - HEADER_ONLY = False
 *  - LOADER = False
 *  - MX = False
 *  - MX_GLOBAL = False
 *  - ON_DEMAND = False
 *
 * Commandline:
 *    --api='gl:core=4.6' --extensions='GL_ARB_gpu_shader_int64' c
 *
 * Online:
 *    http://glad.sh/#api=gl%3Acore%3D4.6&extensions=GL_ARB_gpu_shader_int64&generator=c&options=
 *
 */
```

The one I just generated does have the extension. Are you doing it through the website or locally? Do you have pre-downloaded `gl.xml` in your working directory when calling glad?

**Comment by KitsuneAlex** [comment]
I did everything using the webtool. This is really confusing me right now, i validated both GLAD and GLAD2 headers i freshly generated, and they're present in there too. Imma check the gl.h file i have currently in my project, since that one's causing all the trouble.

**Comment by KitsuneAlex** [comment]
The one i've currently got in my project is missing the definition, which should be under GL_ARB_gpu_shader_fp64 somewhere..
![image](https://user-images.githubusercontent.com/12082168/190857282-ce5df583-7d9a-49eb-8ce6-cb0c5972ddf8.png)
The fresh one however;
![image](https://user-images.githubusercontent.com/12082168/190857308-9a9f88e7-24fa-4968-b33b-1931948672c5.png)

The only difference with the way i generated was i was using pointer aliasing for the header that's causing issues, the other one i left that disabled.

**Comment by Dav1dde** [comment]
Please just include the header (as text), it has the exact time of generation and options used, the only thing which really can be used to reproduce the issue.

**Comment by KitsuneAlex** [comment]
```
/**
 * Loader generated by glad 2.0.0-beta on Sat Sep 10 22:05:30 2022
 *
 * Generator: C/C++
 * Specification: gl
 * Extensions: 124
 *
 * APIs:
 *  - gl:core=4.6
 *
 * Options:
 *  - ALIAS = True
 *  - DEBUG = False
 *  - HEADER_ONLY = False
 *  - LOADER = True
 *  - MX = True
 *  - MX_GLOBAL = False
 *  - ON_DEMAND = False
 *
 * Commandline:
 *    --api='gl:core=4.6' --extensions='GL_AMD_draw_buffers_blend,GL_AMD_multi_draw_indirect,GL_APPLE_flush_buffer_range,GL_APPLE_vertex_array_object,GL_ARB_ES2_compatibility,GL_ARB_ES3_1_compatibility,GL_ARB_base_instance,GL_ARB_blend_func_extended,GL_ARB_buffer_storage,GL_ARB_clear_buffer_object,GL_ARB_clear_texture,GL_ARB_clip_control,GL_ARB_color_buffer_float,GL_ARB_compute_shader,GL_ARB_copy_buffer,GL_ARB_copy_image,GL_ARB_debug_output,GL_ARB_direct_state_access,GL_ARB_draw_buffers,GL_ARB_draw_buffers_blend,GL_ARB_draw_elements_base_vertex,GL_ARB_draw_indirect,GL_ARB_draw_instanced,GL_ARB_framebuffer_no_attachments,GL_ARB_framebuffer_object,GL_ARB_geometry_shader4,GL_ARB_get_program_binary,GL_ARB_get_texture_sub_image,GL_ARB_gl_spirv,GL_ARB_gpu_shader_fp64,GL_ARB_imaging,GL_ARB_indirect_parameters,GL_ARB_instanced_arrays,GL_ARB_internalformat_query,GL_ARB_internalformat_query2,GL_ARB_invalidate_subdata,GL_ARB_map_buffer_range,GL_ARB_multi_bind,GL_ARB_multi_draw_indirect,GL_ARB_multisample,GL_ARB_multitexture,GL_ARB_occlusion_query,GL_ARB_point_parameters,GL_ARB_polygon_offset_clamp,GL_ARB_program_interface_query,GL_ARB_provoking_vertex,GL_ARB_robustness,GL_ARB_sample_shading,GL_ARB_sampler_objects,GL_ARB_separate_shader_objects,GL_ARB_shader_atomic_counters,GL_ARB_shader_image_load_store,GL_ARB_shader_objects,GL_ARB_shader_storage_buffer_object,GL_ARB_shader_subroutine,GL_ARB_sync,GL_ARB_tessellation_shader,GL_ARB_texture_barrier,GL_ARB_texture_buffer_object,GL_ARB_texture_buffer_range,GL_ARB_texture_compression,GL_ARB_texture_multisample,GL_ARB_texture_storage,GL_ARB_texture_storage_multisample,GL_ARB_texture_view,GL_ARB_timer_query,GL_ARB_transform_feedback2,GL_ARB_transform_feedback3,GL_ARB_transform_feedback_instanced,GL_ARB_uniform_buffer_object,GL_ARB_vertex_array_object,GL_ARB_vertex_attrib_64bit,GL_ARB_vertex_attrib_binding,GL_ARB_vertex_buffer_object,GL_ARB_vertex_program,GL_ARB_vertex_shader,GL_ARB_vertex_type_2_10_10_10_rev,GL_ARB_viewport_array,GL_ATI_draw_buffers,GL_ATI_separate_stencil,GL_EXT_blend_color,GL_EXT_blend_equation_separate,GL_EXT_blend_func_separate,GL_EXT_blend_minmax,GL_EXT_copy_texture,GL_EXT_direct_state_access,GL_EXT_draw_buffers2,GL_EXT_draw_instanced,GL_EXT_draw_range_elements,GL_EXT_framebuffer_blit,GL_EXT_framebuffer_multisample,GL_EXT_framebuffer_object,GL_EXT_geometry_shader4,GL_EXT_gpu_shader4,GL_EXT_multi_draw_arrays,GL_EXT_point_parameters,GL_EXT_polygon_offset_clamp,GL_EXT_provoking_vertex,GL_EXT_shader_image_load_store,GL_EXT_subtexture,GL_EXT_texture3D,GL_EXT_texture_array,GL_EXT_texture_buffer_object,GL_EXT_texture_integer,GL_EXT_texture_object,GL_EXT_texture_storage,GL_EXT_timer_query,GL_EXT_transform_feedback,GL_EXT_vertex_array,GL_EXT_vertex_attrib_64bit,GL_INGR_blend_func_separate,GL_KHR_debug,GL_KHR_robustness,GL_NVX_conditional_render,GL_NV_conditional_render,GL_NV_explicit_multisample,GL_NV_geometry_program4,GL_NV_point_sprite,GL_NV_transform_feedback,GL_NV_transform_feedback2,GL_NV_vertex_program,GL_NV_vertex_program4,GL_OES_single_precision,GL_SGIS_point_parameters' c --alias --loader --mx
 *
 * Online:
 *    http://glad.sh/#api=gl%3Acore%3D4.6&generator=c&options=ALIAS%2CLOADER%2CMX
 *
 */
 ```
Here you go. It seems the extension is missing from the list above, but how is that possible if i only use **Add All**? I never selected a single one by hand.

**Comment by KitsuneAlex** [comment]
Could've something on the site itself caused this? Like the extension list not loading entirely before i hit Add All? but if so, why didn't the missing one's show up after a moment?

**Comment by KitsuneAlex** [comment]
Also i am assuming the extensions to be in Core because in the registry they're listed as **gl|glcore**

**Comment by Dav1dde** [comment]
There are about 500 extensions missing from your list. What you did was select no extensions and enable aliasing, which automatically merges in extensions which went core or have aliases to core symbols. If I do that now, I get the same amount of extensions you have enabled (124).

**Comment by KitsuneAlex** [comment]
So my stupid ass must've missed that there was no extensions selected after all.. Maybe because i hit F5 one too many times. I don't know honestly. Sorry for wasting your time on this.

**Comment by Dav1dde** [comment]
> Also i am assuming the extensions to be in Core because in the registry they're listed as **gl|glcore**

That does not mean they are in core, simply that the extension is supported by OpenGL (and OpenGL Core, which you can pretty much disregard, this is just required to model the spec), but not e.g. by OpenGL ES. Core itself does not come with extensions, but it does get confusing when extensions get merged into core.

**Comment by Dav1dde** [comment]
> So my stupid ass must've missed that there was no extensions selected after all.. Maybe because i hit F5 one too many times. I don't know honestly. Sorry for wasting your time on this.

No worries, glad we could figure it out and it's working for you now!

**Comment by KitsuneAlex** [comment]
> > Also i am assuming the extensions to be in Core because in the registry they're listed as **gl|glcore**
> 
> That does not mean they are in core, simply that the extension is supported by OpenGL (and OpenGL Core, which you can pretty much disregard, this is just required to model the spec), but not e.g. by OpenGL ES. Core itself does not come with extensions, but it does get confusing when extensions get merged into core.

Got you :)
