### ISSUE TITLE
Macos glad1 vbo

### ISSUE THREAD

**Issue by SkySnows** [Dav1dde/glad#380]
Compat_profile GLFW_OPENGL_COMPAT_PROFILE on MAC. Compat_profile GLFW_OPENGL_FORWARD_COMPAT on ios. Compatat header and C file generated in glad URL. The triangle can be drawn on Windows, but it cannot be drawn on MAC, and error 1282 is reported

**Comment by Dav1dde** [comment]
This has nothing to do with glad, this just means there is a bug in your code. Maybe you're missing a VAO, VAO's are (or used to be) required on OSX.

**Comment by SkySnows** [comment]
To use GLAD on MacOS, you must bind VBO to VAO, while using VAO

**Comment by Dav1dde** [comment]
This has nothing to do with glad. This is a pure OpenGL issue. You would have this problem with any loader.

**Comment by SkySnows** [comment]
Thank you very much for your answer. This problem will not exist on Windows, but on MacOS.
