### ISSUE TITLE
Compilation issue on platform wasm-emscripten

### ISSUE THREAD

**Issue by haasn** [Dav1dde/glad#387]
I have no idea what this is about. But I [ran into this error](https://code.videolan.org/haasn/vlc/-/jobs/1179227), maybe you have an idea?

```
In file included from ../src/opengl/loader_gl.c:2:
In file included from ../src/opengl/common.h:28:
src/opengl/include/glad/egl.h:974:65: error: typedef redefinition with different types ('__eglMustCastToProperFunctionPointerType (*)(const char *)' (aka 'void (*(*)(const char *))(void)') vs 'void *(*)(const char *)')
typedef __eglMustCastToProperFunctionPointerType (GLAD_API_PTR *PFNEGLGETPROCADDRESSPROC)(const char * procname);
                                                                ^
src/opengl/include/glad/gl.h:5470:32: note: previous definition is here
  typedef void* (GLAD_API_PTR *PFNEGLGETPROCADDRESSPROC)(const char *name);
                               ^
2 warnings and 1 error generated.
```

**Comment by Dav1dde** [comment]
Can you upload me the files somewhere? `gl.h` should not have an EGL symbol. It might be redefined because of a GLES loader, that's the only thing I can think of.

**Comment by Dav1dde** [comment]
Can you try guarding the second `PFNEGLGETPROCADDRESSPROC` with:

```c
#ifndef GLAD_EGL_H_
 typedef void* (GLAD_API_PTR *PFNEGLGETPROCADDRESSPROC)(const char *name); 
#endif
```

The one at: 
```
src/opengl/include/glad/gl.h:5470:32: note: previous definition is here
  typedef void* (GLAD_API_PTR *PFNEGLGETPROCADDRESSPROC)(const char *name);
```

**Comment by Dav1dde** [comment]
Sorry these comments are all a bit random, I'll check properly and actually take a look in your repo after work.

**Comment by Dav1dde** [comment]
@haasn can you check 0ef9e4e? If it's working I can release 2.0.1 for you

**Comment by Dav1dde** [comment]
Proper fix in d5e41c6

**Comment by haasn** [comment]
> Only for emscripten. And I assume you include both gl.h and egl.h in the same file and you're on a header only build?

These are all correct guesses.

> Proper fix in [d5e41c6](https://github.com/Dav1dde/glad/commit/d5e41c6f4da7acb4405097041d1e1f616c578063)

Thanks, I will check

**Comment by haasn** [comment]
@Dav1dde it worked. feel free to tag a release, then

**Comment by Dav1dde** [comment]
Done
