### ISSUE TITLE
Missing python-setuptools dependency in requirements.txt?

### ISSUE THREAD

**Issue by haasn** [Dav1dde/glad#389]
I noticed that glad depends on `python3-setuptools` to function properly. Should this not be added to `requirements.txt`, so tools like `py2pack` pick it up correctly?

**Comment by Dav1dde** [comment]
It's time to replace `pkg_resources` with the newer versions of [importlib.resources](https://docs.python.org/3/library/importlib.html#module-importlib.resources) and [importlib.metadata](https://docs.python.org/3/library/importlib.metadata.html).

**Comment by Dav1dde** [comment]
@haasn There is no more dependency on setuptools, but this requires at least Python 3.8. 

There is still the fallback to setuptools for < 3.8
