### ISSUE TITLE
GLAD_DIRECTORY vs. GLAD_DIR

### ISSUE THREAD

**Issue by Destranix** [Dav1dde/glad#392]
https://github.com/Dav1dde/glad/blob/f237a2bfcec0d9b82b90ec9af4af265c40de7183/cmake/CMakeLists.txt#L186

Is there a difference between GLAD_DIRECTORY and GLAD_DIR and why is GLAD_DIRECTORY created on the linked line and not GLAD_DIR though GLAD_DIR is the non-existing directory?

**Comment by Dav1dde** [comment]
This looks like a bug
