### ISSUE TITLE
WORKING_DIRECTORY does not contain Python module glad

### ISSUE THREAD

**Issue by Destranix** [Dav1dde/glad#393]
https://github.com/Dav1dde/glad/blob/f237a2bfcec0d9b82b90ec9af4af265c40de7183/cmake/CMakeLists.txt#L235-L247

How is this supposed to work? By using "WORKING_DIRECTORY" we are moving to the build directory as the manual says:

> Execute the command with the given current working directory. **If it is a relative path it will be interpreted relative to the build tree directory corresponding to the current source directory.**

https://cmake.org/cmake/help/latest/command/add_custom_command.html

But then we try to execute the glad python module, that though is located in the source directory.

**Comment by Dav1dde** [comment]
It's not relative, it's absolute. Please include an actual broken reproducable setup if you think this is a bug.

**Comment by Destranix** [comment]
It causes problems if GLAD_SOURCES_DIR is set manually and not to an absolute path.
Solution seems to be either to tell users not to do that or converting the path to an absolute path in the CMakeList.txt.

**Comment by Dav1dde** [comment]
I decided to document to use an absolute path, making it relative using `cmake_path` just has the same issue of potentially doing the wrong thing.
