### ISSUE TITLE
glNamedFramebufferTextureMultiviewOVR is not being defined when using OVR_multiview extension

### ISSUE THREAD

**Issue by patrickdown** [Dav1dde/glad#407]
glNamedFramebufferTextureMultiviewOVR is not getting defined when using OVR_multiview extension and OpenGL 4.5

https://registry.khronos.org/OpenGL/extensions/OVR/OVR_multiview.txt

    [[ If OpenGL 4.5 or ARB_direct_state_access is supported ]]

    void NamedFramebufferTextureMultiviewOVR( uint framebuffer, enum attachment,
                                              uint texture, int level,
                                              int baseViewIndex, sizei numViews );

**Comment by Dav1dde** [comment]
This is not defined in the spec:

```xml
        <extension name="GL_OVR_multiview" supported="gl|glcore|gles2">
            <require>
                <enum name="GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_NUM_VIEWS_OVR"/>
                <enum name="GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_BASE_VIEW_INDEX_OVR"/>
                <enum name="GL_MAX_VIEWS_OVR"/>
                <enum name="GL_FRAMEBUFFER_INCOMPLETE_VIEW_TARGETS_OVR"/>
                <command name="glFramebufferTextureMultiviewOVR"/>
            </require>
        </extension>
```

Usually these constraints are modelled like this:
```xml
            <require comment="Supported only if GL_EXT_direct_state_access, ARB_direct_state_access, or OpenGL 4.5 are supported">
                <command name="glEGLImageTargetTextureStorageEXT"/>
            </require>
```

You can report this at the [OpenGL-Registry](https://github.com/KhronosGroup/OpenGL-Registry).
