### ISSUE TITLE
Using glad on Windows

### ISSUE THREAD

**Issue by dmurdoch** [Dav1dde/glad#415]
As I mentioned in #412, I am trying to update the rgl project to use glad to load newer OpenGL functions.  For now I'd be quite happy to get to OpenGL 2.0, but I've built the glad loader to ask for 2.1, since that should always be available on MacOS.

In #412 I was asking about getting it to work on MacOS; it was failing to load because I didn't have a current GL context.  It's now working perfectly on MacOS and a Linux system I tried, but now I'm trying to get it to work on Windows and am having  similar-looking issues.

I am pretty sure I have made a GL context current, but code like this:

```
if ( ( glrcHandle = wglCreateContext( dcHandle ) ) ) {
  if (wglMakeCurrent(dcHandle, glrcHandle)) {
    if (gladLoadGL((GLADloadfunc)wglGetProcAddress)) {
      success = true;
    } else
    ...
```
is failing:  within `gladLoadGL`, `glad_glGetString = (PFNGLGETSTRINGPROC) load(userptr, "glGetString");` is always returning NULL. 

I'm not using glad to load WGL.  At one point I did try generating a WGL loader, but had the same sort of issue somewhat earlier, when trying to load WGL.   Is there some obvious error in what I'm doing?  If not, any suggestions for tracking down the problem?

**Comment by Dav1dde** [comment]
Iirc OpenGL 1.1 symbols on Windows are only exposed from the dll, so you have to get them via `LoadLibraryA` and `GetProcAddress`. So you have to pass a loader to glad which resolves from `wglGetProcAddress` *and* the `opengl.dll`. 

[Here](https://github.com/Dav1dde/glad/blob/glad2/example/c/wgl.c) is an example which might help.

**Comment by dmurdoch** [comment]
Thanks again.  Yes, that was the issue, and the solution is pretty easy.  Rather than defining my own loader, I just used `gladLoaderLoadGL()` in Windows after I noticed it was using the approach you describe.
