### ISSUE TITLE
BUILD_SHARED_LIBS doesn't work

### ISSUE THREAD

**Issue by rafalmaziejuk** [Dav1dde/glad#421]
When library type is not specified explicitly in 'glad_add_library' call and BUILD_SHARED_LIBS is set to ON then 'GG_SHARED' is not set. In this case glad SHARED library configuration doesn't work.

https://github.com/Dav1dde/glad/blob/3b95bf4f9a7a034374092d625e391ddac43fe66f/cmake/CMakeLists.txt#L279

PR with exemplary fix: https://github.com/Dav1dde/glad/pull/418

**Comment by Dav1dde** [comment]
Thanks, should be fixed now!
