### ISSUE TITLE
REPRODUCIBLE produces files in Mac format

### ISSUE THREAD

**Issue by ghuser404** [Dav1dde/glad#423]
In glad2 MSVC on Windows complains about khrplatform.h/vk_platform.h being in Mac format and fails the build with `/permissive-`.

**Comment by Dav1dde** [comment]
What does that mean, mac format?

**Comment by ghuser404** [comment]
Line endings. On Mac they are CRLF.

**Comment by Dav1dde** [comment]
Both of these files are `LF` in the Repo.

**Comment by ghuser404** [comment]
Maybe you see them as LF because you're cloning the repo and it automatically converts them from CR to LF on your computer but they are actually kept in CR. Could that be the case?

**Comment by ghuser404** [comment]
OK, so I figured this is happening because you are converting binary file data into utf-8 to replace cpp-style comments. In glad1 this wasn't happening and binary data was going straight into the file as is. In fact, I tried that in glad2 and it actually gave me a UNIX-style fine (with LFs). I found a link where someone is also having a problem with `decode('utf-8')`.
https://stackoverflow.com/questions/491921/unicode-utf-8-reading-and-writing-to-files-in-python

Maybe we can replace the comments by parsing the binary format, without calling `decode('utf-8')`?

Here is the code that I'm talking about:
```
def _add_additional_headers(self, feature_set, config):
    if config['HEADER_ONLY']:
        return

    for header in self.ADDITIONAL_HEADERS:
        if header.name not in feature_set.types:
            continue

        path = os.path.join(self.path, 'include/{}'.format(header.include))

        directory_path = os.path.split(path)[0]
        if not os.path.exists(directory_path):
            os.makedirs(directory_path)

        if not os.path.exists(path):
            content = self._read_header(header.url)
            with open(path, 'w') as dest:
                dest.write(content)

def _read_header(self, url):
    if url not in self._headers:
        with closing(self.opener.urlopen(url)) as src:
            header = src.read().decode('utf-8')

        header = replace_cpp_style_comments(header)
        self._headers[url] = header

    return self._headers[url]
```

**Comment by Dav1dde** [comment]
Thanks for digging into this, we have to decode the bytes here into Utf-8 to get a string, running a Regex over bytes isn't supported iirc. The file should be read in binary mode, so this should be correct and yield the correct data. I suspect the  `with open(path, 'w') as dest:` might be the culprit and this should be opened with Utf-8 encoding `with open(path, 'w', encoding='utf-8') as dest:`. Without it, it falls back to [`locale.getencoding()`](https://docs.python.org/3/library/locale.html#locale.getencoding). 

Can you see if replacing `open(path, 'w')` with `open(path, 'w', encoding='utf-8')` fixes your issue?

**Comment by ghuser404** [comment]
I tried doing `open(path, 'w', encoding='utf-8')`, but unfortunately that doesn't help 😞

**Comment by ghuser404** [comment]
Right... I see what's happening. My glad repo is cloned in CRLF format, and when `string.decode('utf-8')` is called, it converts `LF` into `CRLF`. In the end I get `CRCRLF`.

Wonder if there is an as-is (UNIX style) decode.

**Comment by Dav1dde** [comment]
No Python does not convert line endings when decoding. Git probably converts LF to CRLF when you check out the repo (`autocrlf` git setting) on Windows.

Can you upload the problematic file (not copy paste)?

**Comment by Dav1dde** [comment]
I can't reproduce your issues. The files are written with system newlines, ` CRLF` on windows. When running `python -m glad --out-path build --api "vulkan" --extensions="" --reproducible c` on Windows 10, the files correctly contain a single `CRLF`.

**Comment by ghuser404** [comment]
Do you clone repo in `LF` or `CRLF` format on Windows?

**Comment by Dav1dde** [comment]
Mh this is weird, the first newlines are correct then the later ones are broken:
![image](https://user-images.githubusercontent.com/255721/229835285-ca4dfe7e-3b7e-4e18-b03c-d00598ca6bf2.png)

Red = Broken, Blue = Correct

**Comment by Dav1dde** [comment]
Mh I think the regex is broken

**Comment by ghuser404** [comment]
The very first one is just CR. Then CRLF. And then everything is broken. But this is because of cpp-style comment replacement in python MULTILINE mode.

You can clone repo in CRLF format and run glad command, then you'll be able tor reproduce this issue.

**Comment by Dav1dde** [comment]
@ghuser404 can you try https://github.com/Dav1dde/glad/commit/1377964bbb8f30e489e18a016b4b4ef46b5646e4? That seems to have fixed it for me.

**Comment by ghuser404** [comment]
@Dav1dde This doesn't fix it. In fact, you actually broken cpp-style comments replacement. See file attached. 😔 
[vk_platform.zip](https://github.com/Dav1dde/glad/files/11150348/vk_platform.zip)

**Comment by Dav1dde** [comment]
oops, should be actually fixed now

**Comment by ghuser404** [comment]
That fixes it for me too! Very good job, thanks! 🙌
