### ISSUE TITLE
add argument names to function signatures

### ISSUE THREAD

**Issue by sivaplaysmC** [Dav1dde/glad#427]
adding arguement names to signatures will be of great use , as it allows the programmer 
to know what the function actually needs
eg : 
in `glBindBuffers` , it will be comfortable if the function glad_glBindBuffer was defined as
`glBindBuffer(GLenum target  , GLsizeiptr size... )`

instead of the current
`glBindBuffer(GLenum , GLsizeiptr ... )`

also since the arguement names are available in the xml spec , 
i also look forward to contirbute towards this issue .

**Comment by Dav1dde** [comment]
Let me know if you still need pointers or have questions
