### ISSUE TITLE
How to use glad on mobile platform with opengles2.0

### ISSUE THREAD

**Issue by yihuang** [Dav1dde/glad#43]
I'm developing with opengles2.0 for mobile platform(ios/android). I've generated glad with command `python main.py --out-path glloader/gles2 --api gles2=2.0 --generator c --spec gl` , but there is only `gladLoadGLES2Loader`, which accepts `GLADloadproc load` as argument, what should I pass to it on android and iOS?

**Comment by Dav1dde** [comment]
Under Android you should have access to `eglGetProcAddress`, under iOS, I have no idea, sorry.
