### ISSUE TITLE
Q: How to build glad2?

### ISSUE THREAD

**Issue by apivovarov** [Dav1dde/glad#431]
I tried the following
```
cmake -B build -S cmake

cmake --build build
```
No errors, but the build process did nothing

`make install` does not work too.

conan2 and vcpkg have 0.1.36 only.

How to build and install glad2 to linux/mac?

**Comment by apivovarov** [comment]
ok, looks like I need to use [webservice for glad2](https://glad.sh/) to generate `glad.zip` and use `include/glad/gl.h` and `src/gl.c` from the zip.

**Comment by Dav1dde** [comment]
Closing since there is a Question/Discussion here: https://github.com/Dav1dde/glad/discussions/432
