### ISSUE TITLE
The head guard of glad/gl.h won't work as it should when header only is selected in glad2 generator

### ISSUE THREAD

**Issue by kiroeko** [Dav1dde/glad#433]
Problems arise when multiple sources refer to header files in a specific order.
<img width="241" alt="s" src="https://github.com/Dav1dde/glad/assets/12566988/269879ce-2205-4dce-b9e1-f9584ab3ae1b">

**Comment by Dav1dde** [comment]
This is on purpose and follows the same pattern what the STB* libs use https://github.com/nothings/stb - e.g. `stb_image`.

Include glad with `GLAD_GL_IMPLEMENTATION` in a singular `.c` file as the last include:
```
#include ...
#include ...
#include ...
#define GLAD_GL_IMPLEMENTATION
#include <glad/gl.h>
```

This could be your `main.c` or a separate source file which only includes glad and nothing else.
