### ISSUE TITLE
Missing vulkan_video_codecs_common.h required by the vk_video headers

### ISSUE THREAD

**Issue by TheMagehawk** [Dav1dde/glad#434]
After glad2 Vulkan generation is completed, the header files in the vk_video include directory miss the header **vulkan_video_codecs_common.h**:

![image](https://github.com/Dav1dde/glad/assets/84444787/f6e708ad-1116-4608-a72d-7c7b1ab0ab73)

Following glad2 configuration was used:

```
glad_add_library(glad STATIC EXCLUDE_FROM_ALL API gl:core=4.6 vulkan=1.3)
```

The issue only occures when not using the flag `REPRODUCIBLE`. What effect does it have on the generation?

Looking at the Vulkan Headers Repository, they have pushed a commit last week (21st July 2023) which includes that header file in **vulkan_video_codec_h264std.h** and **vulkan_video_codec_h265std.h** ([Commit Link](https://github.com/KhronosGroup/Vulkan-Headers/commit/9c37439a7952c204150863fc35569dd864dbd599)):

![image](https://github.com/Dav1dde/glad/assets/84444787/cbc58697-0e92-458a-b01d-117a9a299eae)

The Vulkan Docs Repository added that header file to the video.xml ([Commit Link](https://github.com/KhronosGroup/Vulkan-Docs/commit/2c1e07a72b43f53cc7866c55ae32afe97d933621)):

![image](https://github.com/Dav1dde/glad/assets/84444787/e3ff9a51-071e-4390-ada8-f1315edff7cf)

Since the glad2 Generator only loads the vk specification from the vk.xml which doesn't include that missing header file, we are left with that include error. Taking the video.xml file into account would hopefully fix this issue.

**Comment by Dav1dde** [comment]
I filed an upstream bug, I hope they resolve this issue in the spec and I wont have to start generating the headers myself or manually 'fix' this dependency in a post-processing step.
