### ISSUE TITLE
Glad.h missing

### ISSUE THREAD

**Issue by petrasvestartas** [Dav1dde/glad#439]
Hi,

I used to import glad like this (version https://github.com/Dav1dde/glad/archive/v0.1.29.zip):
#include <glad/glad.h>

But currently there is no glad file anymore in the same 0.1.29 zip
Why?

**Comment by Dav1dde** [comment]
You need to generate the files you need from the website (see Readme) or run the code you downloaded. What github let's you download is only the source code.
