### ISSUE TITLE
RFE: please start making github releases

### ISSUE THREAD

**Issue by kloczek** [Dav1dde/glad#440]
Is it possible next time on release new version make the github release to have entry on https://github.com/Dav1dde/glad/releases? 🤔

I'm asking because only on make gh release is spread notification about new release to those who have set watch->releases.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/

**Comment by Dav1dde** [comment]
I'll have to look into it, but is a good idea!

**Comment by Dav1dde** [comment]
Will create releases now 👍 : https://github.com/Dav1dde/glad/releases/tag/v2.0.5

**Comment by kloczek** [comment]
Thank you very much 😄 👍 
I see that my automation just started processing email automation trying automatically upgrade rpm build procedure.
