### ISSUE TITLE
The automatically generated C branch is at 4.5?

### ISSUE THREAD

**Issue by nodev** [Dav1dde/glad#45]
Although the readme says 4.5.

**Comment by Dav1dde** [comment]
The branches are dead and not updated anymore, the only reason they still exist is because there are submodules pointing to them.

You can use [glad.dav1d.de](http://glad.dav1d.de) to generate the files for you.

**Comment by nodev** [comment]
But that's exactly why that branch was useful. To, provide updated generator without downloading Python or using web generator.

**Comment by Dav1dde** [comment]
That's a wrong use of glad, the main reason why glad is so powerful is that generates the files you need and you just copy them into your project, it's not meant to be an external dependency you link against, just compile it with your sources.
 The branch is basically the opposite of that.
