### ISSUE TITLE
<KHR/khrplatform.h> not found on OpenBSD, alpinelinux and others?

### ISSUE THREAD

**Issue by haasn** [Dav1dde/glad#459]
See https://github.com/haasn/libplacebo/issues/246

Not sure what's going on here, it seems that this header does not exist on some platforms. Maybe it needs to be made conditional somehow. The issue poster over there suggests extracting the include path from `gl.pc`, but I am not convinced this is the best solution.

**Comment by brad0** [comment]
Well I mention gl.pc as a means of pulling in the appropriate header path, since the headers in question are from OpenGL / Mesa.

Yes, the issue is glad looking for the OpenGL headers.

**Comment by Dav1dde** [comment]
> Not sure what's going on here, it seems that this header does not exist on some platforms.

I had that before there was also issues where the platform provided one was outdated and didn't have the necessary symbols, that's why I started including it in the glad output. A header only build embeds it and normal one generates also the dependencies. Should just be able to take the entire glad output.

**Comment by brad0** [comment]
The headers very much exist on the platforms. That isn't the issue.

But headers have to be able to be found, not make assumptions as is typical of a Linux build environment.

glad/egl.h has..

```
#ifndef __eglplatform_h_
#define __eglplatform_h_

/*
** Copyright 2007-2020 The Khronos Group Inc.
** SPDX-License-Identifier: Apache-2.0
*/

/* Platform-specific types and definitions for egl.h
 *
 * Adopters may modify khrplatform.h and this file to suit their platform.
 * You are encouraged to submit all modifications to the Khronos group so that
 * they can be included in future versions of this file.  Please submit changes
 * by filing an issue or pull request on the public Khronos EGL Registry, at
 * https://www.github.com/KhronosGroup/EGL-Registry/
 */

#include <KHR/khrplatform.h>
```

**Comment by Dav1dde** [comment]
I don't understand the problem, glad gives you the necessary header dependencies, you just add them to the include path, like you add glad to the include path.

**Comment by bl4ckb0ne** [comment]
@Dav1dde you can see the error here https://gitlab.alpinelinux.org/alpine/aports/-/jobs/1299859/raw

**Comment by Dav1dde** [comment]
Okay, it can't find the header, then there is a missing include.

 Not sure how this is related to glad, glad recognizes the dependency and also outputs the necessary header, it has no control over the compiler include flags.

**Comment by haasn** [comment]
> glad gives you the necessary header dependencies

Where does it put this information?

**Comment by nekopsykose** [comment]
> you can see the error here [gitlab.alpinelinux.org/alpine/aports/-/jobs/1299859](https://gitlab.alpinelinux.org/alpine/aports/-/jobs/1299859)  

in this specific case `<KHR/khrplatform.h>` would exist if you had `mesa-dev` installed as a makedep (because that path can then be found from the default `/usr/include` incpath). whether that's intended or not i can't say (does glad depend on the system-provided headers of this?), but it's very easy to fix the build there

**Comment by Dav1dde** [comment]
> Where does it put this information?

Either the include directory contains the headers or it doesn't:

```
include/glad/gl.h
include/KHR/khrplatform.h
```

**Comment by Dav1dde** [comment]
@nekopsykose again, no, glad does specifically include all necessary headers in it's output, just check the output directory.

![image](https://github.com/Dav1dde/glad/assets/255721/af0f9512-2121-4201-9d7b-81dde051c45d)

**Comment by Dav1dde** [comment]
Okay I see, you're generating a header only EGL build and eglplatform now depends on khrplatform but the include is not removed by glad.

**Comment by Dav1dde** [comment]
Too bad CI didn't catch this, there is a test which would fail, but the test environment has the header installed :(

I'll release a new glad version in the next minutes, sorry for the troubles.

**Comment by bl4ckb0ne** [comment]
Thanks!

**Comment by brad0** [comment]
Thanks.
