### ISSUE TITLE
Fail to use GL_NV_geometry_shader_passthrough bug.

### ISSUE THREAD

**Issue by tigert1998** [Dav1dde/glad#462]
Recently, I have been trying to use the GL_NV_geometry_shader_passthrough  extension to accelerate cascaded shadow mapping. But I found that the passthrough geometry shader cannot be linked using the OpenGL context loaded by glad2. I think it's very likely to be the bug of glad. Here's a minimal GLSL code snippet to illustrate the bug:

```glsl
// model.vert
#version 460 core

uniform mat4 uMVP;

layout (location = 0) in vec3 aPosition;
layout (location = 1) in vec2 aTexCoord;

out vOutputs {
    vec3 position;
    vec2 texCoord;
} vOut;

void main() {
    vOut.position = aPosition;
    vOut.texCoord = aTexCoord;
    gl_Position = uMVP * vec4(aPosition, 1);
}

```

```glsl
// model.geom
#version 460 core

#extension GL_NV_geometry_shader_passthrough : require
#extension GL_NV_viewport_array2 : require

layout (triangles) in;
layout (viewport_relative) out int gl_Layer;

layout (passthrough) in gl_PerVertex {
    vec4 gl_Position;
} gl_in[];

layout (passthrough) in vOutputs {
    vec3 position;
    vec2 texCoord;
} vOut[];

void main() {
    gl_ViewportMask[0] = 7;

    gl_Layer = 0;
}
```

```glsl
// model.frag
#version 460 core

in vOutputs {
    vec3 position;
    vec2 texCoord;
} vOut;

out vec4 fragColor;

void main () {
    fragColor = vec4(vOut.texCoord, 0, 1);
}
```

This shader can be compiled and linked using the OpenGL context loaded in this repo: https://github.com/nvpro-samples/gl_ssao/tree/master, which is an official NV code repository. But it fails to link using glad loaded OpenGL environment. `glGetProgramInfoLog` gives the following link error:

```
Link info
---------
max_vertices layout qualifier must be declared in at least one of the GLSL geometry shaders
```

This error message is absolutely wrong because a passthrough geometry shader cannot be specified with a `max_vertices` layout. To know more about this extension, you can read this document: https://registry.khronos.org/OpenGL/extensions/NV/NV_geometry_shader_passthrough.txt.

I am using Windows 11, OpenGL 4.6 and an RTX 4060 graphics card.

**Comment by Dav1dde** [comment]
This is unlikely a glad bug, glad just loads function pointers and that worked, since you're getting an error from your driver.

**Comment by tigert1998** [comment]
Thank you for your quick reply. But how can two OpenGL contexts have different behaviors when compiling the same shader?

**Comment by Dav1dde** [comment]
I don't know what you're doing, there is very likely a difference, to rule out glad you can take the working example and replace the loader with glad, if it breaks we at least have a rough example to minimize.

**Comment by tigert1998** [comment]
Yes, you are right. It turns out that this issue has nothing to do with GLAD. I forgot to set the program to be in the compatibility profile.
