### ISSUE TITLE
Provide a way to automatically obtain the code without the need to manually download it from a web page. 

### ISSUE THREAD

**Issue by Song-Tianxiang** [Dav1dde/glad#468]
Suppose I want to use GL 3.3 core, can we get `glad` without having to open a browser and download it from a web page, such as providing a fixed URL https://glad/gl/3.3/core, and then we can get a zip file containing the `glad` code we need?

I want to do this because I really want to isolate my own source code and dependencies in the build system, and let the build system help me obtain the dependencies.(I want to use `Meson`).

Is it not feasible to provide a fixed URL to get `glad`? Why haven't we done this?

Also, I know we can get `glad` without opening a browser with the help of `cmake`, but I think it's ugly, especially the need to install a python dependency. If we could provide a fixed URL, the cmake build would be very simple.(I guess). I am not very familiar with build systems, and if I have misunderstood anything, I apologize.

**Comment by Dav1dde** [comment]
You're supposed to generate manually, either via the webpage or the python cli and then just include the generated code in your repository, only regenerate when you need new extensions or features.
