### ISSUE TITLE
Incrroect encoding when python read file

### ISSUE THREAD

**Issue by star-hengxing** [Dav1dde/glad#469]
https://github.com/Dav1dde/glad/blob/1ecd45775d96f35170458e6b148eb0708967e402/glad/files/__init__.py#L22-L31

If `resource_exists` failed, script will use `open` to read file, but local host encoding. So I got the error:

```
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal multibyte sequence
```

Here are some of my suggestions.

- It's not recommended to use `pkg_resources`.

https://setuptools.pypa.io/en/latest/pkg_resources.html
> Use of pkg_resources is deprecated in favor of importlib.resources, importlib.metadata and their backports (importlib_resources, importlib_metadata). Some useful APIs are also provided by packaging (e.g. requirements and version parsing). Users should refrain from new usage of pkg_resources and should work to port to importlib-based solutions.

- Use `PYTHONWARNDEFAULTENCODING=1` to fix potential encoding errors.

**Comment by Dav1dde** [comment]
Can you test again with the latest changes to master, would be good to know if the issues is actually fixed now.

> It's not recommended to use pkg_resources.

Now it is, I think last I looked into it I needed 3.9 to make it actually work. Should update, but just a small refresher, this code technically still supports and works on Python 2.7. 3.9 is out now, so no reason to not actually use it if it's available.

**Comment by star-hengxing** [comment]
It work fine, thanks.
