### ISSUE TITLE
Provide it as a rust crate

### ISSUE THREAD

**Issue by rawhuul** [Dav1dde/glad#475]
While it's quite good, there's some friction involved when using this as user need to install a Python module first to generate Rust bindings. It would be more beneficial to offer a crate that directly provides these bindings and receives regular updates from the generator being run in Github CI/CD.

**Comment by rawhuul** [comment]
It would be also good edition to the website to generate Rust bindings and one can directly use it

```rust
mod glad {
    include!("./glad.rs");
}
```

**Comment by Dav1dde** [comment]
The idea of glad was always to provide exactly the feature set you need and not more, so this clashes a bit with the idea of having a static crate which contains everything.

An idea could be to hide everything behind feature flags or cfgs and the user selects the features from the crate in their `Cargo.toml`, kind of like `web-sys` is doing.

**Comment by rawhuul** [comment]
> An idea could be to hide everything behind feature flags or cfgs and the user selects the features from the crate in their Cargo.toml, kind of like web-sys is doing.

Yes, it is doable that way but it will need making the generator feature aware

**Comment by Dav1dde** [comment]
The current idea is, glad generates a crate and you can just include that in your local workspace.

Btw you can use the [website](https://glad.sh) to generate the crate and you don't need Python installed locally.

**Comment by rawhuul** [comment]
Yeah, thanks for this, its pretty cool. Can it be automated using curl by hitting specific endpoint?

**Comment by Dav1dde** [comment]
Ideally you don't do that, it's just a tiny server and I don't wanna give any guarantees on uptime and stable API, also you may end up getting caught by cloudflare.

The recommended workflow is to download, add it to your git repo and update whenever you want more features, glad generates all files 'stable' which should give you very nice diffs whenever you regenerate with a new feature set.

**Comment by rawhuul** [comment]
Thanks, fair enough.
