### ISSUE TITLE
Can you help a python newbie?

### ISSUE THREAD

**Issue by Lucretia** [Dav1dde/glad#479]
Hi, can you take a look at [this](https://github.com/Lucretia/glad/tree/add-ada) and see why 

```python
    for entry_point in entry_points(group=entry_point):
```

In plugin.py is skipping it?

**Comment by Dav1dde** [comment]
Hey, generally you'd make a separate Python package with it's own setup.py which adds the entrypoint 'globally' for this Python installation and glad will pick it up through the entrypoint.

You can validate whether it was correctly installed by just opening the Python interpreter and running `__import__('importlib.metadata').entry_points(group='glad.generator')` which should return your registered entrypoint.

Note to make this work you must actually install the package first.

**Comment by Lucretia** [comment]
So, you don't want to extend it to new languages?

I'm new to python, I've got glad in a venv, ```<path-to>/glad/.venv/```, so I'm not sure what you mean.

**Comment by Dav1dde** [comment]
> So, you don't want to extend it to new languages?

The idea of the plugin system is, that it can be separate from the main repo. I will not merge anymore languages I cannot maintain into the main repo, but the idea of the plugin system is that it doesn't have to be merged (I do plan to include working plugins on the website by just installing the plugin).

The [setuptools docs](https://setuptools.pypa.io/en/latest/userguide/entry_point.html#dynamic-discovery-of-services-and-plugins) describe how entrypoints work and how they need to be setup.

**Comment by Lucretia** [comment]
You definitely need more documentation on how to extend this then because I can't see much in the way of docs.

**Comment by Dav1dde** [comment]
There is a [Wiki Page](https://github.com/Dav1dde/glad/wiki/Extending-Glad).

**Comment by Lucretia** [comment]
It's very sparse.

**Comment by Dav1dde** [comment]
Feel free to improve it. It's a wiki afterall.
