### ISSUE TITLE
Add support for Vulkan

### ISSUE THREAD

**Issue by NamelessPerson** [Dav1dde/glad#48]
Adding initial support for the Vulkan API would be super helpful and awesome

**Comment by Dav1dde** [comment]
I have a kind of working modified parser for Vulkan, but I haven't really had time to figure out how the loading of Vulkan functions/extensions works, hints, pullrequests etc. welcome.

**Comment by MrVallentin** [comment]
Just tuning in but I've made [vkel (Vulkan Extension Loader)](https://github.com/MrVallentin/vkel).

If I may, I would love to make it an addon for glad, or what you would call it.

**Comment by Dav1dde** [comment]
Vulkan support is now complete in the glad2 branch, including all the features of GL: multi-context, global multi-context, alias, loader, header only.
