### ISSUE TITLE
Compile error when using OpenGL debug header

### ISSUE THREAD

**Issue by ceeac** [Dav1dde/glad#480]
OS: Arch Stable
Version: `extra/glad 2.0.6-3`

 Steps to reproduce:
 - Generate OpenGL 3.3 Core header:
   `$ glad --out-path glad/ --api gl:core=3.3 --extensions=GL_ARB_separate_shader_objects,GL_KHR_debug c --header-only --loader --debug`
 - Try to compile minimal C executable with GCC with `-Werror=old-style-definition`

Result:
```
glad/gl.h: In function ‘gladInstallGLDebug’:
glad/gl.h:7228:6: error: old-style function definition [-Werror=old-style-definition]
 7228 | void gladInstallGLDebug() {
      |      ^~~~~~~~~~~~~~~~~~
glad/gl.h: In function ‘gladUninstallGLDebug’:
glad/gl.h:7647:6: error: old-style function definition [-Werror=old-style-definition]
 7647 | void gladUninstallGLDebug() {
      |      ^~~~~~~~~~~~~~~~~~~~
```

`gladInstallGLDebug()` should be `gladInstallGLDebug(void)` for C; same for `gladUninstallGLDebug`.

**Comment by Dav1dde** [comment]
Thanks, seems like I missed the `void` here https://github.com/Dav1dde/glad/blob/2ae8255a60f3ca529a4db079161c3f8c120f178d/glad/generator/c/templates/base_template.c#L168 and a few lines below for the `Uninstall.

**Comment by Dav1dde** [comment]
Should be fixed now.
