### ISSUE TITLE
Vulkan + SDL first steps

### ISSUE THREAD

**Issue by mihaly-sisak** [Dav1dde/glad#481]
Hello all!

I am very new to Vulkan, coming from OpenGL. I tried to understand the generated GLAD2 code, and how I am supposed to use it, but it is very function pointer heavy and I would like to ask for clarification.

The Vulkan example provided uses the `gladLoaderLoadVulkan` interface, and if my understanding is correct, with SDL2 I need to use the `gladLoadVulkan` interface.

SDL provides a function [SDL_Vulkan_GetVkGetInstanceProcAddr](https://wiki.libsdl.org/SDL2/SDL_Vulkan_GetVkGetInstanceProcAddr) which I need to use as the loader function. And I need to use the Vulkan functions to get to select the device so I need to call:

```
// init SDL
gladLoadVulkan(NULL, SDL_Vulkan_GetVkGetInstanceProcAddr());
// select the device
gladLoadVulkan(device, SDL_Vulkan_GetVkGetInstanceProcAddr());
// use Vulkan
```

I see that volk populates the function pointers first with `vkGetInstanceProcAddr(instance, "vk_function_string")` then with `vkGetDeviceProcAddr(device, "vk_function_string")`. 

I do not see the same in GLAD2. Am I not noticing it trough the function pointers? Is it needed? Volk readme states a 7% overhead if it is not done, is is true? Should I just use `gladLoaderLoadVulkan`? I see that it is called like:

```
gladLoaderLoadVulkan(NULL, NULL, NULL);
gladLoaderLoadVulkan(demo->inst, demo->gpu, NULL);
gladLoaderLoadVulkan(demo->inst, demo->gpu, demo->device);
```
Will it cause issues with SDL? The loader also gets `vkGetDeviceProcAddr` from the shared object, not using `vkGetInstanceProcAddr` to get it. Will this cause issues?

**Comment by Dav1dde** [comment]
> The Vulkan example provided uses the gladLoaderLoadVulkan interface, and if my understanding is correct, with SDL2 I need to use the gladLoadVulkan interface.

Yes that's the preferred method, although the builtin loader should work just fine.

> I do not see the same in GLAD2. Am I not noticing it trough the function pointers? Is it needed? Volk readme states a 7% overhead if it is not done, is is true? Should I just use gladLoaderLoadVulkan? I see that it is called like:

If you use SDL, the SDL loader is supposed to resolve the function pointers and taking care of calling `vkGetDevicePointer`. That's also why you need to call the loader multiple times.

If you use the builtin loader, that's what glad does: 

```c
static GLADapiproc glad_vulkan_get_proc(void *vuserptr, const char *name) {
    struct _glad_vulkan_userptr userptr = *(struct _glad_vulkan_userptr*) vuserptr;
    PFN_vkVoidFunction result = NULL;

    if (userptr.vk_device != NULL && glad_vulkan_is_device_function(name)) {
        result = userptr.get_device_proc_addr(userptr.vk_device, name);
    }

    if (result == NULL && userptr.vk_instance != NULL) {
        result = userptr.get_instance_proc_addr(userptr.vk_instance, name);
    }

    if(result == NULL) {
        result = (PFN_vkVoidFunction) glad_dlsym_handle(userptr.vk_handle, name);
    }

    return (GLADapiproc) result;
}
```

**Comment by mihaly-sisak** [comment]
Sadly I could not find anything about SDL resolving the pointers, it loads some vulkan function definitions internally, but I can not figure out how it is exposed.

I modified the loader code like this, works like a charm:
```
static const char* GLOBAL_FUNCTIONS[] = {
    "vkEnumerateInstanceVersion", 
    "vkEnumerateInstanceExtensionProperties", 
    "vkEnumerateInstanceLayerProperties",
    "vkCreateInstance",
};

static int glad_vulkan_is_global_function(const char *name) {
    // https://registry.khronos.org/vulkan/specs/1.3-extensions/man/html/vkGetInstanceProcAddr.html#_description
    int i;
    int length = sizeof(GLOBAL_FUNCTIONS) / sizeof(GLOBAL_FUNCTIONS[0]);

    for (i=0; i < length; ++i) {
        if (strcmp(GLOBAL_FUNCTIONS[i], name) == 0) {
            return 1;
        }
    }

    return 0;
}

struct _glad_vulkan_userptr {
    VkInstance                vk_instance            = NULL;
    VkDevice                  vk_device              = NULL;
    PFN_vkGetInstanceProcAddr get_instance_proc_addr = NULL;
    PFN_vkGetDeviceProcAddr   get_device_proc_addr   = NULL;
};

static GLADapiproc glad_vulkan_get_proc(void *vuserptr, const char *name) {

    struct _glad_vulkan_userptr userptr = *(struct _glad_vulkan_userptr*) vuserptr;

    if ((userptr.vk_device != NULL) && glad_vulkan_is_device_function(name)) {
        return (GLADapiproc) userptr.get_device_proc_addr(userptr.vk_device, name);
    }

    if (userptr.vk_instance != NULL) {
        return (GLADapiproc) userptr.get_instance_proc_addr(userptr.vk_instance, name);
    }

    if (glad_vulkan_is_global_function(name)) {
        return (GLADapiproc) userptr.get_instance_proc_addr(NULL, name);
    }

    return (GLADapiproc) NULL;
}

static struct _glad_vulkan_userptr glad_vulkan_build_userptr(VkInstance instance, VkDevice device) {
    struct _glad_vulkan_userptr userptr;
    userptr.vk_instance            = instance;
    userptr.vk_device              = device;
    userptr.get_instance_proc_addr = (PFN_vkGetInstanceProcAddr) SDL_Vulkan_GetVkGetInstanceProcAddr();
    userptr.get_device_proc_addr   = (instance == NULL) ? (NULL) : 
        (PFN_vkGetDeviceProcAddr) userptr.get_instance_proc_addr(instance, "vkGetDeviceProcAddr");
    return userptr;
}

int gladLoaderLoadVulkan( VkInstance instance, VkPhysicalDevice physical_device, VkDevice device) {

    int version = 0;

    struct _glad_vulkan_userptr userptr = glad_vulkan_build_userptr(instance, device);

    if (userptr.get_instance_proc_addr != NULL) {
        version = gladLoadVulkanUserPtr( physical_device, glad_vulkan_get_proc, &userptr);
    }

    return version;
}
```

**Comment by mihaly-sisak** [comment]
Sorry, I misclicked
