### ISSUE TITLE
nim glGetShaderInfoLog/glGetProgramInfoLog type error

### ISSUE THREAD

**Issue by morganholly** [Dav1dde/glad#484]
so im not sure where the code is to fix it in a PR myself, and maybe im doing something wrong, but the glGetShaderInfoLog/glGetProgramInfoLog calls gave me SIGBUS crashes, which went away when i changed the input type from cstring to ptr cstring and passed the address instead of the cstring directly

**Comment by Dav1dde** [comment]
@johnnovak Can you maybe help here?

**Comment by johnnovak** [comment]
`cstring` maps to the `char *` C type. See [here](https://nim-lang.org/docs/manual.html#types-cstring-type):

> For the C backend the cstring type represents a pointer to a zero-terminated char array compatible with the type char* in ANSI C. Its primary purpose lies in easy interfacing with C. 

Relevant examples from my nim-glfw project:

### Original glfw C definitions

```c
GLFWAPI GLFWwindow* glfwCreateWindow(
    int width, int height, const char* title, GLFWmonitor* monitor, GLFWwindow* share);

GLFWAPI const char* glfwGetWindowTitle(GLFWwindow* window);

```

### Nim C FFI mappings

```nim
type
  Window*  = ptr object
  Monitor* = ptr object

proc glfwCreateWindow*(
   width: cint; height: cint; title: cstring; monitor: Monitor; share: Window): Window {.cdecl.}

proc glfwGetWindowTitle*(window: Window): cstring {.cdecl.}
```
---

These are the C signatures of the functions in question:

```c
void glGetProgramInfoLog(
 	GLuint program,
  	GLsizei maxLength,
  	GLsizei *length,
  	GLchar *infoLog);
```

```c
void glGetShaderInfoLog(
 	GLuint shader,
  	GLsizei maxLength,
  	GLsizei *length,
  	GLchar *infoLog);
```

The corresponding C mappings seem correct to me, `infoLog` should be a `cstring`.

```nim
type
  GLuint* = uint32
  GLsizei* = int32

  glGetProgramInfoLog*: proc (program: GLuint, bufSize: GLsizei, length: ptr GLsizei, infoLog: cstring) {.stdcall.}

  glGetShaderInfoLog*: proc (shader: GLuint, bufSize: GLsizei, length: ptr GLsizei, infoLog: cstring) {.stdcall.}
```

I think there's something else wrong with your program and `ptr cstring` somehow masks the error/crash, but I doubt you're getting correct results. Using `ptr cstring` for `infoLog` most certainly _cannot_ be correct, so maybe post a minimal example program here that reproduces the crash then we can go from there.

**Comment by morganholly** [comment]
hm yeah that does seem like just plain cstring should be correct

**Comment by morganholly** [comment]
oh and now it works. wild. i have no clue what changed, maybe i was always doing addr variable and somehow had a massive brain fart

**Comment by morganholly** [comment]
no clue what i was doing wrong, closing
