### ISSUE TITLE
“No space left on device” error when downloading from the  webservice

### ISSUE THREAD

**Issue by Zhangzhw58** [Dav1dde/glad#487]
## Description:
I encountered an error while trying to download files from `https://gen.glad.sh` and `https://glad.dav1d.de` 
The error message is as follows:
```
Error:
[Errno 28] No space left on device: '/usr/src/app/temp/tmpcctgm7y5glad'
```

## Reproduction Steps:
1. Go to https://gen.glad.sh/.
2. Configure the options:
  - Language: C/C++
  - Specification: OpenGL
  - Profile: Core
  - gl: Version 3.3
  - Options: loader
  - The other options remain default
3. Click the download button.

I suspect this might be due to the temporary file directory on the server being full. Could you please check if there is sufficient disk space and clear any unnecessary temporary files?

## Attachments:
![屏幕截图 2024-09-20 143634](https://github.com/user-attachments/assets/523a338d-6f1c-4107-b1b4-f65160f83e08)
![屏幕截图 2024-09-20 143408](https://github.com/user-attachments/assets/3e61a6b0-3329-4bb5-a621-5d126f4bd7c1)

**Comment by Dav1dde** [comment]
Thanks should be fixed!
