### ISSUE TITLE
Error while generating from glad.sh (Error: loader/vulkansc.h)

### ISSUE THREAD

**Issue by Gabriellavoura** [Dav1dde/glad#495]
I encountered an error while trying to generate files from https://gen.glad.sh

## Error Message
The error message is as follows:
```
Error:
loader/vulkansc.h
```
## Steps to Reproduce:
1. Go to [glad.sh](https://gen.glad.sh/).
2. Select the Vulkan SC API (version 1.3).
3. In the options section, only the "loader" checkbox was selected.
4. Click "Generate."

### Expected Result:
Successful generation of the loader and Vulkan SC files.

### Actual Result:
Generation fails with the error message above.

## Attachments:
Selected settings: Only the "loader" checkbox was marked in the options section.
![image](https://github.com/user-attachments/assets/8f655d4f-22e3-47da-94dd-d1fea33dc510)

### Error message:
![image](https://github.com/user-attachments/assets/317be138-3cc0-4674-a898-152c8b255e07)

**Comment by Dav1dde** [comment]
Yeah `vulkansc` currently has no loader support. I am curious, are you actually interested in using Vulkan SC?

**Comment by Gabriellavoura** [comment]
No, I'm not planning to use vulkansc .  I was just exploring the tool and came across the error. I apologize for any inconvenience, and thank you for maintaining this awesome tool! 😃
