### ISSUE TITLE
Support header-file-only library generation

### ISSUE THREAD

**Issue by raysan5** [Dav1dde/glad#52]
Would it be possible to add support for header-file-only generation for GLAD? I mean, similar to the [stb libraries](https://github.com/nothings/stb).

It would be very useful to just drop glad.h into the project and avoid pipeline modification.

[Here](https://github.com/raysan5/raylib/blob/develop/src/external/glad.h) it is a sample I'm working on; I created the GLAD header-file-only myself manually.

**Comment by Shimmen** [comment]
I think this is a great idea. I never really want to put the glad-files in with the rest of my code, but the alternative for now is just a tad too complicated.

I think that simplicity is the one features of glad that makes it stand above rest (like GLEW). Having just a header file to import would make it even more simple and better.

However, I imagine compiling the whole file @raysan5 has made takes some time, especially if it's included in several files. Quite often I just want like a GLuint declared for my header file. Maybe a complimentary ```glad_types.h``` would be good. Personally I'm not worried about many files, but rather ```.c``` files.

**Comment by raysan5** [comment]
Hi @Shimmen, I'm using OpenGL 3.3 core profile glad version, originally, `glad.h` was already ~14K LoC and `glad.c` was ~7.6K LoC. Once unified, `glad.h` is ~22K LoC and compiling time with GCC 4.7.2 takes about 2-3 seconds in my [dev workstation](https://www.zotac.com/product/mini_pcs/pi320).

**Comment by Shimmen** [comment]
I'm considering making a pull request. Do you want it to be an option to only have a header file and should it be default?

**Comment by Dav1dde** [comment]
Hey, that's awesome! 

I am still thinking if that option makes sense, as previously pointed out the header file would be really large and slow down the compilation process by quite a bit. I am also not sure if splitting the header into multiple header files is a good idea.

Then again, having the option probably doesn't hurt, the header-only option wouldn't be the default though.

**Comment by raysan5** [comment]
I used the web tool to just select the extensions I needed (basic OpenGL 3.3 Core) and then I created a header only file; it was around 5K LoC and it compiles in milliseconds (unnoticeable any delay).

**Comment by Dav1dde** [comment]
Just a heads up, the glad2 Branch supports a header only option now!

`python -m glad --out-path=build --api="gl:core=" --extensions= c --mx --header-only`

**Comment by Dav1dde** [comment]
Just a heads up, the glad2 branch supports a header only option now!

`python -m glad --out-path=build --api="gl:core=" --extensions= c --header-only`

**Comment by elmindreda** [comment]
Modern preprocessors are very fast so when `GLAD_IMPLEMENTATION` isn't defined there would be virtually no performance impact.

**Comment by raysan5** [comment]
Great addition @Dav1dde! Thank you very much for the update! :)

**Comment by ricanteja** [comment]
Any news on when this functionality will be hitting the website or will that be when version 2 is officially launched? Thanks!

**Comment by Dav1dde** [comment]
I don't have an ETA. 

If you want to play around with it, the glad2 branch should produced working C-Code. API slightly changed: `gladLoadGL` is the only way to load a GL context and it always requires to be passed a loader function.

**Comment by IntellectualKitty** [comment]
I was hoping we could get a status update on when this might make it to the website.  I love the web service!  I think it's great!  Header-only support would make it perfect.  Thanks!

**Comment by Dav1dde** [comment]
http://glad2.dav1d.de currently hosts the glad2.dav1d.de branch, it is functional but with no fixed API. The glad2 does support header only. If you find bugs, I am happy to fix them.

**Comment by maek** [comment]
I believe I found some issues with this:

1. The header guard `__glad_gl_h_` should be closed at the end of the file, not just after the glad.h part
2. You should define all functions as `inline` otherwise you are breaking ODR, i.e. it is not possible to include it more than once

**Comment by Dav1dde** [comment]
Thanks, yeah the header only still needs some improvements.

@elmindreda pointed me to (just so I don't forget): https://github.com/nothings/stb/blob/master/docs/stb_howto.txt#L9

**Comment by Dav1dde** [comment]
Works in glad2.

**Comment by elimerl** [comment]
For the lazy: You have to #define GLAD_GL_IMPLEMENTATION before including gl.h when using header-only libraries. GLAD_IMPLEMENTATION does not work. Then again this took 15 seconds of looking at the header so whatever
