### ISSUE TITLE
[webservice] Support selecting multiple Specification extensions

### ISSUE THREAD

**Issue by raysan5** [Dav1dde/glad#53]
Using the web service I noticed you have to choose between OpenGL, EGL, WGL, GLX to add extensions to the list, when you change the Specification, the list is reseted.

It would be great to be able to add OpenGL extensions together with, for example, WGL extensions.

**Comment by Dav1dde** [comment]
Yes this would be a good enhancement, for now you need to do everything separately (as you need to do with the command line tool). I am going to reopen this ticket over at Dav1dde/glad-web.
