### ISSUE TITLE
GL_STACK_OVERFLOW and GL_STACK_UNDERFLOW seem to be undefined

### ISSUE THREAD

**Issue by Kazade** [Dav1dde/glad#58]
I've just generated an OpenGL 2.1 glad zip from the web service (I'm trying to switch a quite large project away from GLEW) and it appears GL_STACK_OVERFLOW and GL_STACK_UNDERFLOW are undefined. In fact, this is the section in glad.h where they should be...

```
#define GL_NO_ERROR 0
#define GL_INVALID_ENUM 0x0500
#define GL_INVALID_VALUE 0x0501
#define GL_INVALID_OPERATION 0x0502
#define GL_OUT_OF_MEMORY 0x0505
```

Notice that it jumps from 0x0502 to 0x0505 :)

**Comment by Dav1dde** [comment]
I cannot reproduce the issue, I generated C/C++, 2.1 OpenGL on http://glad.dav1d.de - Can you paste how you generated the loader (should be in the comment at the beginning of the file) e.g. ` --profile="compatibility" --api="gl=2.1" --generator="c" --spec="gl" --extensions=""`

**Comment by Kazade** [comment]
Ah! Select "core" profile (I guess this shouldn't make a difference on 2.1)

**Comment by Dav1dde** [comment]
It should not and does not in the `glad2` branch where the profile behaviour is properly implemented. Unfortunately that's how it is, not going to fix it in this branch (too much work), soon there will be glad 2.0 ;)
