### ISSUE TITLE
Discussion: Multi-context context loading

### ISSUE THREAD

**Issue by nigels-com** [Dav1dde/glad#60]
Hello and official greetings from the land of GLEW.

With the 2.0.0 release of GLEW support for GLEW MX was dropped due to complications involving core context support.  It seems to me a better arrangement for a multi-context (MX) GLEW layered on top of GLEW, rather than existing as a mutant variant of it.  There hasn't been an outcry over GLEW 2.0.0, but I've still been browsing here and there for some kind of migration path for GLEW MX applications.

The broad notion that appeals to me for GLEW MX 2 is to layer a per-context struct-of-function pointers on top of GLEW (or whatever other native function loader) and simply generating code for populating the appropriate state from the vanilla GLEW function pointers and extension flags.  It seems that _glad_ might be an appropriate solution for generating GLEW MX, as an alternative back-end.  This also has the advantage of being able to mix single-threaded (main thread) and multi-threaded code into same codebase.

There would be some complication in terms of glad accepting the GLEW-style extension specifications.(The XML is only a subset of what GLEW supports)  Perhaps the more ideal arrangement is for glad to natively support multi-context use cases, is that already the case?  In that case I'd be happy to recommend glad as the MX migration path beyond GLEW 1.13.0.

Some other discussion is here:
https://github.com/nigels-com/glew/issues/38
- Nigel

**Comment by Dav1dde** [comment]
Hi!

I am not sure if I understand. GLEW 2.0 will not have MX support, instead the idea is to have GLEW MX 2 using GLEW. GLEW MX 2 organizes all functions from GLEW in structs then uses GLEW to initialize them using `glewGetProcAddress`?

So far glad does not have multi context support but I am working on a "glad 2.0" which will include multi context support (at least for C) similar to [glxw](https://github.com/rikusalminen/glxw) ([generated glxw.c](http://glxw.dav1d.de/src/glxw.c)):

```
GladGLContext context;
gladLoadGL(&context, (GLADloadproc) glfwGetProcAddress))
context.glGetError()

// not sure about context switching for globals
gladSetContext(&context);
```

**Comment by QUSpilPrgm** [comment]
Multi context support would be awesome. I would have been mostly interested in a version without globals because I have to use the different contexts multithreadedly. Right now I am using kind of a hack. I am just relying on the driver that all function pointers are the same between contexts.

**Comment by nigels-com** [comment]
Rather than `glewGetProcAddress` or other string-based lookup, I was thinking of a simply a pointer-by-pointer copy from the global GLEW function pointers into a client-managed struct.  Indeed along the lines of glxw, but perhaps even simpler.

If/when there are advances in glad, I'll be following with interest.

**Comment by Dav1dde** [comment]
> Rather than glewGetProcAddress or other string-based lookup, I was thinking of a simply a pointer-by-pointer copy from the global GLEW function pointers into a client-managed struct. Indeed along the lines of glxw, but perhaps even simpler.

That would be possible but sounds like a bad solution.

> If/when there are advances in glad, I'll be following with interest.

I have a somewhat working implementation, still unsure about certain things, how the --mx API would look:

```c
GladGLContext init_glad_context() {
    // obviously static GladGLContext context; works as well
    GladGLContext *context = malloc(sizeof(GladGLContext)); 
    gladLoadGL(context, (GLADloadproc) glfwGetProcAddress));
    return context;
}

// preferred way of doing it:
glfwMakeCurrent(glfw_context_1);
context1 = init_glad_context();
context1->glClear();

glfwMakeCurrent(glfw_context_2);
context2 = init_glad_context();
context2->glClear();

// --mx-global enabled during generation
glfwMakeCurrent(glfw_context_1)
gladSetGLContext(context1);
glClear();

glfwMakeCurrent(glfw_context_2)
gladSetGLContext(context2);
glClear();
```

**Comment by Dav1dde** [comment]
Seems to work pretty well now, including the global aliasing.
