### ISSUE TITLE
glShaderSource is inconsistent with the specification

### ISSUE THREAD

**Issue by MoodyMoon** [Dav1dde/glad#61]
The declaration for `glShaderSource` stated in OpenGL ES 2.0 specification is

`void glShaderSource(GLuint shader, GLsizei count, const GLchar * const *string, const GLint *length);`

but the generated declaration is this instead

`void glShaderSource(GLuint shader, GLsizei count, const GLchar** string, const GLint* length)`

Note that the 3rd parameter is missing a `const` keyword.

I have not looked at generated files for other OpenGL versions, just OpenGL ES 2.0.

**Comment by Dav1dde** [comment]
Fixed it, thank you very much!

This issue still exists for D and Volt but I don't consider that an urgent problem right now.
