### ISSUE TITLE
Enhance gladLoadGLES2Loader?

### ISSUE THREAD

**Issue by teburt** [Dav1dde/glad#62]
In some implementations of EGL, eglGetProcAddress will load both core and extension functions. But this isn't always the case and the spec says it's just for extension functions. In this situation - I noticed it with ANGLE on Windows - a different function is needed to load core functions.

The consequence is that when using EGL, the GLADloadproc passed into gladLoadGLES2Loader needs to know what is an extension function and what is not. It's actually a lot more simple if GLAD makes this determination, since it already knows what is a core function and what is an extension. 

Just wanted to suggest adding a second signature to gladLoadGLES2Loader that accepts two functions, one for loading core functions and one for extension functions. Then the load_GL_ES_VERSION_* functions use one parameter, while the load_GL_* use the other.

I haven't looked at making the changes to the generator yet though. Does the glad2 branch handle this differently?

**Comment by Dav1dde** [comment]
Hey, thanks for the report!

I was under the assumption eglGetProcAddress is able to load everything, adding a second parameter for another loader which is only used for extensions is defenitely possible. Can you link me to the documentation of such a function?

**Comment by teburt** [comment]
I actually don't know of such a function. There is wglGetProcAddress/xglGetProcAddress/aglGetProcAddress for Windows/Linux(x11)/OSX, but I believe that's just for desktop GL. 

On Windows I have to open the GLES library with LoadLibrary and then use GetProcAddress. On iOS dlsym seems to work for everything since they don't use EGL. 

I had imagined that whoever uses GLAD would have to wrap a system call and pass that as the function.

**Comment by Dav1dde** [comment]
I completely misread your question and confused myself with it. 

I am aware of this problem, but this can easily be worked around:

>eglGetProcAddress returns the address of the extension function named by procname. procname must be a null-terminated string. The pointer returned should be cast to a function pointer type matching the extension function's definition in that extension specification. A return value of NULL indicates that the specific function does not exist for the EGL implementation.

It returns NULL if the function could not be found so a loader could look something like this:

```
void* loader(const char *name) {
    void* result = eglGetProcAddress(name);
    if (result == NULL) {
        result = dlsym(lib, name);
    }
    return result;
}
```

That's actually how the internal glad loader for OpenGL works (a fallback to dlsym). But usually you want to use the loader provided by your context creation library: SDL -> `SDL_GL_GetProcAddress`, glfw -> `glfwGetProcAddress`. 

I am considering including a loader function for OpenGL ES (as there is for OpenGL).

PS: There is also https://www.khronos.org/registry/egl/extensions/KHR/EGL_KHR_get_all_proc_addresses.txt

**Comment by teburt** [comment]
I might hesitate to use that workaround in production code. I have seen that some EGL implementations return non-NULL if you pass a string that isn't the name of a known extension. E.g. if you misspell the extension name it returns non-null. I expect some vendors didn't bother to return NULL, even when the name is part of the core spec.

**Comment by Dav1dde** [comment]
Still thinking about it.

Then this should work, dlsym first:
```void* loader(const char *name) {
    void* result =  dlsym(lib, name);  
    if (result == NULL) {
        result = eglGetProcAddress(name);
    }
    return result;
}```

That's how libepoxy is doing it.

**Comment by teburt** [comment]
Ok, I see. Something like that would do - especially since GLAD only calls loader() on either client API functions or those returned from glGetString(GL_EXTENSIONS)
