### ISSUE TITLE
open_gl() returns 0 even if libGL == NULL, is this intended?

### ISSUE THREAD

**Issue by 10se1ucgo** [Dav1dde/glad#63]
EDIT: Nevermind, it returns 1 on success and 0 on failure. That seems to go against what I've seen before ;-;

**Comment by Dav1dde** [comment]
Yes. It follows GLFW (glfwInit), also the glad2 Branch returns the loaded Version as ’major * 10 + minor’ and 0 on failure.

**Comment by 10se1ucgo** [comment]
Ah okay, my bad. I'm used to non-zero meaning an error has occurred. Thanks for clearing that up.
