### ISSUE TITLE
Adding install target to cmake

### ISSUE THREAD

**Issue by Maigo** [Dav1dde/glad#65]
Would it be possible to add install targets to the cmake build? I did a quick try to include this library as an external project dependency in a local project, but as glad does not build as a standard library with install (instead using parent scope sets, which does not work for external projects), I've currently hit somewhat of a wall.

could be solved (?) by something as simple as:

```
install(TARGETS glad ARCHIVE DESTINATION lib)
install(FILES ${GLAD_HEADERS} DESTINATION include)
```

assuming the header(s) could be accessed separately from the source(s).

**Comment by Dav1dde** [comment]
I am all open for improvements, unfortunately I am not really firm with cmake. If you want to make a PR I will happily accept it, just make sure to include in the description how I can test it.

**Comment by Maigo** [comment]
That makes two of us :) but I'll give it a go when I have some time over. Thanks.

**Comment by Socapex** [comment]
This works, you just need to define GLAD_INSTALL=On

`ExternalProject_Add(glad_ext
	GIT_REPOSITORY https://github.com/Dav1dde/glad.git
	GIT_TAG v0.1.14a0
	CMAKE_ARGS ${CMAKE_ARGS}
		-DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_BINARY_DIR}
		-DCMAKE_PREFIX_PATH=${CMAKE_CURRENT_BINARY_DIR}
		-DGLAD_PROFILE="core"
		-DGLAD_API="gl=4.1"
		-DGLAD_INSTALL=On
)
`

**Comment by Maigo** [comment]
Closing this issue as it has been resolved, as noted above. :)
