### ISSUE TITLE
fatal error: typedef redefinition with different types on OSX

### ISSUE THREAD

**Issue by Algorithmus** [Dav1dde/glad#70]
As explained in [this issue](https://github.com/bkaradzic/bgfx/issues/215#issuecomment-86517772), it seems OSX already includes GLsizeiptr and a few others. The same problem happens with glad.h as well. The workaround appears to be to use long instead of ptrdiff_t. [Here](https://github.com/tpaviot/oce/pull/380/files)'s another example.

**Comment by Dav1dde** [comment]
Thanks, I will have to look into this and why these types already exist...

**Comment by BastiaanOlij** [comment]
Ran into this issue as well, any updates on this?

**Comment by Dav1dde** [comment]
Trying to look into this issue this weekend, hopefully I can find a way to reproduce it without having access to an OSX instance.

**Comment by BastiaanOlij** [comment]
Cheers :)

**Comment by Dav1dde** [comment]
The fix looks like this:

```c
#if defined(__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__) && (__ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ > 1060)
typedef long GLintptr;
#else
typedef ptrdiff_t GLintptr;
#endif
```

OSX Versions > 10.6 (starting with 10.7) only have 64 bit support, unfortunately I cannot test this on an OSX device, please report back if it actually works as intended.

**Comment by Algorithmus** [comment]
I put those changes in glad.h. Works for me.

**Comment by Dav1dde** [comment]
Awesome, thanks!
