### ISSUE TITLE
unused function 'has_ext' 

### ISSUE THREAD

**Issue by hannorein** [Dav1dde/glad#72]
I'm getting a compiler warning of an unused function `has_ext`. I know I can just ignore the warning or turn it off, but do you think one could somehow avoid including a static function if it is actually not used anywhere in the file?

With these settings:

    http://glad.dav1d.de/#profile=compatibility&language=c&specification=gl&api=gl%3D3.3

I'm getting this warning:

```
glad.c:75:12: warning: unused function 'has_ext' [-Wunused-function]
static int has_ext(const char *ext) {
```

**Comment by Dav1dde** [comment]
Good point, die function shouldn't be there without extensions.

**Comment by dcousens** [comment]
Any progress on this?
I suspect the issue that https://github.com/Dav1dde/glad/blob/f19c005f04da7c305dd7b55df1bc54d6c6296d3f/glad/lang/c/generator.py#L199 just needs to wrapped in a check that extensions are actually needed,  right?

**Comment by Dav1dde** [comment]
Unfortunately that doesn't work without changing other parts, opted for the simpler `(void)&has_ext;`, I don't like it but current glad code is just too messy to properly fix it, that's something for glad2.
