### ISSUE TITLE
executing my code gives  symbol lookup error undefined symbol: glad_glGenTextures

### ISSUE THREAD

**Issue by nikhilrayaprolu** [Dav1dde/glad#74]
on executing my code I am facing this error
`./sample2D: symbol lookup error: /usr/local/lib/libftgl.so.2: undefined symbol: glad_glGenTextures`

```
all: sample2D

sample2D: Sample_GL3_2D.cpp glad.c
        g++ -o sample2D Sample_GL3_2D.cpp glad.c -lGL -lglfw -lGLU -lftgl -ldl -std=c++11

clean:
        rm sample2D

```

this is my Makefile

**Comment by Dav1dde** [comment]
I need to know how you built glad and see your source.

Also I would like to not use this bugtracker as support forum, you can find me on `chat.freenode.net#OpenGL`.

**Comment by Dav1dde** [comment]
Closing, op removed the SO question and doesn't provide anymore feedback.
