### ISSUE TITLE
Add version modules to D/Volt bindings

### ISSUE THREAD

**Issue by Wallbraker** [Dav1dde/glad#75]
Right now in the gl module imports all symbols from the types/func/ext... modules.

If you add one for each version of OpenGL you generating separate bindings would not be required.

For instance one could import `amp.gl.v33` in one piece of the code to make sure it only uses OpenGL 3.3, and in another part of the code base import `amp.gl.v45`. I don't know if we want a module for each extension?

**Comment by Wallbraker** [comment]
Woohoo, thanks! :D

**Comment by Dav1dde** [comment]
> Woohoo, thanks! :D

Bad news, I never got around to adding Volt and D back, I just dont have the time to support this anymore :(

**Comment by Wallbraker** [comment]
Ah, no worries totally understandable.
