### ISSUE TITLE
Can't find gladLoadGL function

### ISSUE THREAD

**Issue by sasmaster** [Dav1dde/glad#81]
Hi.I downloaded the sources from the online generator but I don't see gladLoadGL() function there.

**Comment by Shimmen** [comment]
Did you specify glad to generate a loader or not? If you specified that it shouldn't generate its own loader it instead generated the function `gladLoadGLLoader`, where you pass in the loader procedure.

**Comment by sasmaster** [comment]
Yes, I did.And it generated still without that func.

**Comment by Shimmen** [comment]
Interesting. What version of glad are you using? From the master branch, some release, or from the web version? And what language?

**Comment by sasmaster** [comment]
Web.Just went to the web page,configured the loader and generated.

**Comment by Shimmen** [comment]
In the top of the glad.h and glad.c files is a comment looking somewhat like this:

    OpenGL loader generated by glad 0.1.13a0 on Wed Mar 15 14:00:02 2017.

    Language/Generator: C/C++
    Specification: gl
    APIs: gl=3.3
    Profile: core
    Extensions:
        
    Loader: True
    Local files: False
    Omit khrplatform: False

    Commandline:
        --profile="core" --api="gl=3.3" --generator="c" --spec="gl" --extensions=""
    Online:
        http://glad.dav1d.de/#profile=core&language=c&specification=gl&loader=on&api=gl%3D3.3

Could you post an example of how yours look like?

**Comment by sasmaster** [comment]
OpenGL ES loader generated by glad 0.1.13a0 on Wed Mar 15 09:49:44 2017.

    Language/Generator: C/C++
    Specification: gl
    APIs: gles2=2.0
    Profile: compatibility

**Comment by sasmaster** [comment]
As a sidenote - I generated for ES2.0-3.0

**Comment by Shimmen** [comment]
I haven't used glad for GLES, but looking at the generated glad.h I see a function with the definition `GLAPI int gladLoadGLES2Loader(GLADloadproc)`. I assume that's the equivalent for GLES. There is no function for loading with a built-in loader though and it doesn't seem to respect the toggle for it in the web generator. I don't know if that's expected or a bug, but it's pretty strange.

**Comment by Dav1dde** [comment]
`gladLoadGL` only exists for the GL API, there is no such function for GLES. As @Shimmen correctly pointed out you need to use `int gladLoadGLES2Loader(GLADloadproc)` and supply your own loader, if you're using GLFW this would be `glfwGetProcAddress` and for SDL `SDL_GL_GetProcAddress`.

There is no `gladLoadGLES` since there is no easy way to implement it (I would need to load the GLES.dll/so for EGL < 1.5 and get a `eglGetProcAddress` from somewhere).

**Comment by knitterJ** [comment]
You probably wanted to run getting started program from https://www.glfw.org/docs/latest/quick_guide.html.
It seems that gl.h, that contains gladLoadGL( GLADloadfunc load) can be generated only from second version of Glad - Glad2 gl API https://gen.glad.sh/. In the first version of Glad this function is declared differently. From the basic stuff, never forget to include gl.c linker file in your project folder and the compilation process.

**Comment by bhavithc** [comment]
Just you need to use `gladLoadGL((GLADloadfunc)glfwGetProcAddress)` instead of `gladLoadGLLoader`
