### ISSUE TITLE
Typo "WIN32" instead of "_WIN32"?

### ISSUE THREAD

**Issue by ericroy** [Dav1dde/glad#86]
Hi there,

This code is checking if `WIN32` is defined, but shouldn't it be checking `_WIN32`?
https://github.com/Dav1dde/glad/blob/4014836cb06e86058b1e82b4b1777f511e31ef11/glad/lang/c/loader/__init__.py#L108

**Comment by Dav1dde** [comment]
It looks like a mistake to me and it should be _WIN32 indeed, @BtbN can you confirm?

Good catch!

**Comment by BtbN** [comment]
I'm pretty sure both work, but _WIN32 might be the safer and standard option indeed.

**Comment by Dav1dde** [comment]
Thanks, I will change it to _WIN32 then, WIN32 doesn't seem to be officially be defined.

https://msdn.microsoft.com/en-us/library/b0084kay(VS.80).aspx

**Comment by ericroy** [comment]
Awesome, thanks for the quick fix!
