### ISSUE TITLE
GL_ARB_gl_spirv not listed

### ISSUE THREAD

**Issue by dv343** [Dav1dde/glad#87]
I tried to use http://glad.dav1d.de/ to generate OpenGL 4.4 headers with the GL_ARB_gl_spirv extension included, but it is not listed.

**Comment by Dav1dde** [comment]
That was a bug https://github.com/Dav1dde/glad-web/commit/13f8674c9602d1288b5de9437cf618e835fcac4e - luckily? in a version which was not yet deployed, which still downloaded the specifications from Khronos SVN (these are not really maintained anymore).

Bug fixed and re-deployed, it's listed now :).

Thanks for reporting!
