### ISSUE TITLE
How to provide support for extensions not present in the Registry?

### ISSUE THREAD

**Issue by 10110111** [Dav1dde/glad#90]
I'd like to make use GLAD in my application which uses [GLX_MESA_swap_control](http://cgit.freedesktop.org/mesa/mesa/plain/docs/MESA_swap_control.spec), but GLAD can't generate headers aware of this extension. How can I make it work?

**Comment by Dav1dde** [comment]
Sorry for answering late, I must have missed the issue. 

That seems like a bug in the [Specification](https://github.com/KhronosGroup/OpenGL-Registry/blob/master/xml/glx.xml), I opened an issue for it: https://github.com/KhronosGroup/OpenGL-Registry/issues/94
