### ISSUE TITLE
Add Support for inline functions, rather than macros

### ISSUE THREAD

**Issue by pixeljetstream** [Dav1dde/glad#91]
Instead of 
#define glFunc glad_glFunc
create inline function
inline void glFunc(...) { glad_glFunc(...) }

helps intellisense/syntax coloring in IDEs, may also add assert in inline function whether glad_glFunc is non nullptr

**Comment by Dav1dde** [comment]
I am gonna think about this, but this is not a high priority atm, IDEs should be powerful enough to properly resolve macros in 2017, for the assert part, this is possible through a glad-debug build.

**Comment by Flamefire** [comment]
Not a good idea. You won't be able to do something like `if(glFunc)`

**Comment by Dav1dde** [comment]
I don't think this is a good idea, it would only be a thing to trick your IDE but actually using the glad build would fail horribly.

**Comment by duzenko** [comment]
Why not
```
GLAPI PFNGLRECTIPROC glRecti ;
```
instead of
```
GLAPI PFNGLRECTIPROC glad_glRecti;
#define glRecti glad_glRecti

```
?

**Comment by Flamefire** [comment]
@duzenko Because that would lead to conflicts when the libopengl is loaded as you'd now have 2 symbols with the same name --> BOOM

**Comment by duzenko** [comment]
> libopengl

What is libopengl, why would I need to load it, and why do I need glad if I'm already using it?

**Comment by Dav1dde** [comment]
@duzenko you might not be using it, but this affects any library you link with. If any library links with `libgl` it will end up getting the symbol from glad. Now until glad is loaded these symbols are `null`, meaning this will cause segmentation faults.

**Comment by Dav1dde** [comment]
> More importantly, is there any glad option to switch to define-less header?

No.
