### ISSUE TITLE
Initialize glad_* and GLAD_* to zero

### ISSUE THREAD

**Issue by pixeljetstream** [Dav1dde/glad#92]
To get robust behavior when glad wasn't loaded yet

**Comment by Dav1dde** [comment]
Can you show me an example where that would help? What's a more robust behaviour? As far as I am aware most C compilers initialize to 0 anyways (am I wrong here?)

Also apologies for answering so late.

**Comment by elmindreda** [comment]
[Initialization](http://en.cppreference.com/w/c/language/initialization) of global variables to zero or NULL is guaranteed by the standard.

**Comment by Dav1dde** [comment]
Thanks!
