### ISSUE TITLE
Duplicate functions in version 3.0 and 3.1

### ISSUE THREAD

**Issue by vassvik** [Dav1dde/glad#93]
Based on the files generated by the webservice, using version 4.5 core:

The last 3 entries in `load_GL_VERSION_3_1` are duplicates of entries in `load_GL_VERSION_3_0`. All 3 are part of the 3.0 spec, it seems.

**Comment by Dav1dde** [comment]
This is possibly a bug in the specification. I checked with the function name `glGetIntegeri_v`. Looking it up in the XML it is defined in the 3.0 section and in the 3.1 section.

```xml
    <feature api="gl" name="GL_VERSION_3_0" number="3.0">
        <require>
[...]
            <command name="glGetBooleani_v"/>
            <command name="glGetIntegeri_v"/>
            <command name="glEnablei"/>
[...]
        </require>
    </feature>
    <feature api="gl" name="GL_VERSION_3_1" number="3.1">
[...]
            <command name="glBindBufferBase"/>
            <command name="glGetIntegeri_v"/>
        </require>
    </feature>
```

If you want to report the bug you can open an issue here: https://github.com/KhronosGroup/OpenGL-Registry
