### ISSUE TITLE
EGL generator doesn't provide runtime flags for extensions

### ISSUE THREAD

**Issue by mefesto** [Dav1dde/glad#96]
I recently used GLAD for EGL (1.4) and required a couple extensions:
 - EGL_KHR_create_context
 - EGL_KHR_debug

Those particular extensions aren't very important but just used as an example. I was expecting things to work like GLAD for OpenGL where I can check the runtime extension flags to see if the device the app is running on supports them and augment behavior accordingly. So I expected the be able to do this:

```cpp
    if (GLAD_EGL_KHR_debug) { /* setup debug stuff */ }
```

But it seems that the glad_egl.h doesn't declare an extension variable for this purpose. Is this a bug or, for EGL, are users expected to do something else?

Thanks

**Comment by Dav1dde** [comment]
Hey, yeah this currently doesn't work, I have the generation of these flags for EGL turned off, I don't remember why I did it - Seems like an oversight (-> bug).

If it is an easy fix, I might add it, otherwise if you feeling lucky you can try the glad2 branch (which has these flags).

**Comment by Dav1dde** [comment]
I am gonna close this as wontfix now, this will be supported in glad2.
