### ISSUE TITLE
How to require only the extensions my system supports?

### ISSUE THREAD

**Issue by computersarecool** [Dav1dde/glad#97]
Hi,
If I use the Web service and I "add all" of the extensions - when I use the resulting file does the header `#define` macros for only the extensions available on my system?

In other words, If i try to do `#ifdef GL_EXT_memory_object`  and I requested that extension but it is not available on my platform, will it be defined (incorrectly)?

**Comment by Dav1dde** [comment]
The defines just allow you to check at compile time which extensions (and opengl versions) are potentially available. After loading/initilaizing glad you can check with `GLAD_<name of extension>` if the extension is available at runtime (= supported by the driver and loaded).

In your example:

```c
// [initialize glad]
// ...

if (!GLAD_GL_EXT_memory_object) {
    die("GL_EXT_memory_object not supported!");
}
```

I hope this answers your question.

**Comment by computersarecool** [comment]
It does. Thanks!
